- lib/drizzlepac/acsData.py
- lib/drizzlepac/adrizzle.py
- lib/drizzlepac/astrodrizzle.py
- lib/drizzlepac/buildmask.py
- lib/drizzlepac/buildwcs.py
- lib/drizzlepac/catalogs.py
- lib/drizzlepac/createMedian.py
- lib/drizzlepac/drizCR.py
- lib/drizzlepac/imageObject.py
- lib/drizzlepac/mapreg.py
- lib/drizzlepac/mdzhandler.py
- lib/drizzlepac/nicmosData.py
- lib/drizzlepac/outputimage.py
- lib/drizzlepac/processInput.py
- lib/drizzlepac/runastrodriz.py
- lib/drizzlepac/staticMask.py
- lib/drizzlepac/stisData.py
- lib/drizzlepac/tweakreg.py
- lib/drizzlepac/tweakutils.py
- lib/drizzlepac/updatehdr.py
- lib/drizzlepac/util.py
- lib/drizzlepac/wcs_functions.py
- lib/drizzlepac/wfc3Data.py
- lib/drizzlepac/wfpc2Data.py
Get rid of ``numpy`` deprecation warnings about array comparisons to None. In addition, I have pythonified code by removing comparisons to True/False + a few cosmetic changes.
This addresses issue https://github.com/spacetelescope/drizzlepac/issues/17
> Replace comparisons to None, True, and False

- setup.cfg
See also: https://github.com/spacetelescope/drizzlepac/issues/31#issuecomment-278527868
> Bumped version to 2.1.8

- lib/drizzlepac/processInput.py
This addresses a Python 3 compatibility issue described in https://github.com/spacetelescope/drizzlepac/issues/41
> Switch from string.uppercase to string.ascii_uppercase

- lib/drizzlepac/buildmask.py
- lib/drizzlepac/imgclasses.py
- lib/drizzlepac/processInput.py
- lib/drizzlepac/resetbits.py
- lib/drizzlepac/sky.py
Update ``drizzlepac`` to use latest ``bitmask`` functions - see https://github.com/spacetelescope/stsci.tools/pull/29
> Update drizzlepac to the latest bitmask in stsci.tools

- setup.cfg
> Update 2.1.8 -> 2.1.9

- lib/drizzlepac/sky.py
Addresses issue https://github.com/spacetelescope/drizzlepac/issues/46
> Make bitmask changes backward compatible: adding 'sky.py' missed in the previous PR

- lib/drizzlepac/processInput.py
Fixes issue https://github.com/spacetelescope/drizzlepac/issues/51
> Fix incorrect use of 'input' to get user input in Python 2.7

- setup.cfg
Increase version after https://github.com/spacetelescope/drizzlepac/pull/60 for release.
> Version bump to 2.1.14

- lib/drizzlepac/util.py
- lib/drizzlepac/wcs_functions.py
This PR addresses issues https://github.com/spacetelescope/drizzlepac/issues/62 and https://github.com/spacetelescope/drizzlepac/issues/63.
> Fix WCS merge logic, CRPIX computations, and enhance rounding stability

- doc/source/release_notes.rst
- setup.cfg
> Bump version 2.1.16 -> 2.1.17

- lib/drizzlepac/createMedian.py
- lib/drizzlepac/minmed.py
Fixes bugs introduced in https://github.com/spacetelescope/drizzlepac/pull/107
> Fix function parameter names

- doc/source/release_notes.rst
- lib/drizzlepac/astrodrizzle.help
- lib/drizzlepac/astrodrizzle.py
- lib/drizzlepac/tweakreg.help
- lib/drizzlepac/tweakreg.py
- lib/drizzlepac/util.py
Implements option 2 from https://github.com/spacetelescope/drizzlepac/issues/111#issuecomment-373817151 as this option is what @mackjenn wants AND it will not affect the pipeline according to this comment: https://github.com/spacetelescope/drizzlepac/issues/111#issuecomment-373784459
> Swap defaults for configobj

- doc/source/release_notes.rst
Added link to github issue in the release notes.
> Update release notes

- LICENSE.txt
> Add BSD 3-Clause license

- Jenkinsfile
Basic Jenkinsfile for smoke-testing builds.
Testing will be integrated later when it is ported away from pandokia.
> Initial commit of Jenkinsfile

- Jenkinsfile
- MANIFEST.in
- doc/source/release_notes.rst
- setup.py
Minor touch-ups before making a release.
> Prepare 2.2.0

- drizzlepac/ablot.py
- drizzlepac/adrizzle.py
- drizzlepac/astrodrizzle.py
- drizzlepac/findobj.py
- drizzlepac/tweakutils.py
- setup.py
Not saying this is the way to go, and I haven't run the test suite, but these changes build in py2 and py3 and allow doc creation in my setup with the current master. Check if it works for you and in rtd.
> EXP: updating package imports

- drizzlepac/ablot.py
- drizzlepac/adrizzle.py
- drizzlepac/astrodrizzle.py
- drizzlepac/findobj.py
- drizzlepac/tweakutils.py
- setup.py
Reverts spacetelescope/drizzlepac#130
Changes in #130 crashes astrodrizzle.
> Revert "EXP: updating package imports"

- src/arrdrizmodule.c
- src/cdrizzlemap.c
Get rid of C compiler warnings.
> Fix C compile warnings

- src/arrdrizmodule.c
- src/cdrizzleblot.c
Further reduce number of compile warnings in C modules.
> Reduce C compile warnings

- CHANGELOG.rst
Add a changelog record for https://github.com/spacetelescope/drizzlepac/pull/142
> Add CHANGELOG entry for setup improvement

- drizzlepac/catalogs.py
- drizzlepac/mapreg.py
- setup.py
> Switch to frozen stregion instead of `astropy/pyregion`

- CHANGELOG.rst
- drizzlepac/tweakutils.py
This should address https://github.com/spacetelescope/drizzlepac/issues/161
> Change color scheme of 2D hist plots to viridis

- src/arrdrizmodule.c
> Use SimpleNew - reduce numpy deprecation warnings

- drizzlepac/astrodrizzle.py
This should address the issue of confusion of numbering of steps in the documentation and GUI, see https://github.com/spacetelescope/drizzlepac/issues/196.
CC: @stsci-hack @samanthalh
> Do not number items in the list of steps

- JenkinsfileRT
Latest release of CI utils library changed this naming convention.
> Correct miniconda dir in PATH definition

- drizzlepac/runastrodriz.py
The code used to run `astrodrizzle` in the HST calibration pipeline, `runastrodriz.py`, required `astrodrizzle` to actually update the input files using `updatewcs`.  
This set of changes not only explicitly runs `updatewcs` on all calibrated input images, but also defines input file lists necessary for aligning them to GAIA in the pipeline and sets up the basic logic for performing that alignment when the code is ready.  
These current changes, though, do not result in any changes in the processing results (either within the files or in what files are created).
> Logic updated in runastrodriz to call updatewcs separately

- CHANGELOG.rst
- drizzlepac/__init__.py
- drizzlepac/alignimages.py
- drizzlepac/hlautils/analyze.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/hlautils/astroquery_utils.py
- drizzlepac/hlautils/bitmask.py
- drizzlepac/hlautils/catalog_utils.py
- drizzlepac/hlautils/get_git_rev_info.py
- drizzlepac/hlautils/updatehdr.py
- drizzlepac/runastrodriz.py
hlapipeline source code added to the drizzlepac package.
> Initial load of hlapipeline

- drizzlepac/alignimages.py
See [HLA-197](https://jira.stsci.edu/browse/HLA-197) for more details.
> Astrometric catalog "GSC241" has been replaced with "GAIADR1" in alignimages.py.

- JenkinsfileRT
@jhunkeler or @rendinam Does this look correct? I want to run those tests with all STScI maintained packages installed from master.
> test with  dependencies  from the master branches

- tests/resources.py
Small change to tolerances for regression testing to make them more robust.
> Revise tests to better use tolerances

- drizzlepac/alignimages.py
- drizzlepac/hlautils/astrometric_utils.py
This attempts to address problems identified in JIRA HLA-187 as well as problems with jbvb04020 (fitQual exception).
> Try to fix some exceptions

- CHANGELOG.rst
- drizzlepac/alignimages.py
- drizzlepac/hlautils/analyze.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/hlautils/astroquery_utils.py
- drizzlepac/hlautils/get_git_rev_info.py
- drizzlepac/hlautils/updatehdr.py
Updated the logutil invocation in all files which will write logging to write to both stdout and a file.
> Fixed STDOUT logging.

- Jenkinsfile
- JenkinsfileRT
Revival of #195 sans `stsci.convolve`.
> TST: Unpin pytest. Enable RT auto-notify on failure.

- drizzlepac/catalogs.py
Fixes a bug seen in the regression tests on boyle introduced by PR #230.
> Fix bug from #230

- pyproject.toml
This should now be possible thanks to https://github.com/spacetelescope/stsci-bot/pull/11. 🤞
> Configure stsci-bot to ignore milestone for this repository

- CHANGELOG.rst
- src/arrdrizmodule.c
This PR fixes pointer arithmetic error on void pointers as reported in https://github.com/spacetelescope/drizzlepac/pull/258
> Fix VS compiler errors due to pointer arithmetic

- azure-pipelines.yml
- setup.cfg
`7084` violations and counting.
Closes #152
> Implement PEP8 check

- README.md
A botched rebase removed this from #253
> Add azure badge

- CHANGELOG.rst
- drizzlepac/imgclasses.py
- drizzlepac/tweakutils.py
This PR ports bug fix from https://github.com/spacetelescope/tweakwcs/pull/69 to `drizzlepac`. It also changes the logic to no longer ignore the value of `tolerance` set by the user when `use2dhist` is enabled. Unfortunately C code was left as is for compatibility purposes (while no longer used functions in `tweakutils` are being deprecated).
> Improve 2D-histogram intitial shift estimation algorithm

- drizzlepac/hlautils/testutils.py
Fix a bug where the code crashed when trying to find the environment variable ASTROMETRY_STEP_CONTROL when it had not been defined by the user yet.  Also, added 'force' parameter in order to allow the user to refresh local copy of the data which appears to be necessary after applying the subsequent headerlets.
> Fix envvar bug, and added force parameter

- CHANGELOG.rst
- drizzlepac/alignimages.py
Merge this change into hla-staging to allow for PR to be reviewed and testing to be done before it goes onto master.
> Always return filtered table

- CHANGELOG.rst
- drizzlepac/imageObject.py
This PR fixes the bug described in #319.
CC: @jhunkeler
> Bug fix in the automatic computation of the IVM weights

- doc/source/conf.py
- doc/source/hla.rst
- doc/source/index.rst
- drizzlepac/hlautils/astrometric_utils.py
This PR fixes the docstrings in astrometric_utils.
I built the sphinx documentation locally to see how they are but there are general issues with the sphinx configuration of drizzlepac that prevent it from displaying properly (I think, or I did something wrong).
In any casee it builds, just doesn't look good.
> fix docstrings in astrometric_utils

- drizzlepac/alignimages.py
- drizzlepac/hlautils/analyze.py
- Fixes issues related to the disastrous merge that doomed [PR 325](https://github.com/spacetelescope/drizzlepac/pull/325).
[HLA-227](https://jira.stsci.edu/browse/HLA-227)
1. Added summary table that displays basic fit into for each astrometric catalog/fit method combination run.
2. Added 'fit method' to filtered_table
3. Added fit method as new headerlet primary extension field 'FITMETH'
4. Added fit method to headerlet wcsname.
> Display algorithm name at the end of alignimages run and in headerlet file (UPDATED)

- drizzlepac/alignimages.py
**NOTE**: Do not merge until PR #328 is merged in. the branch to be merged in this PR was originally branched off the branch from PR #328.
- This branch addresses ticket [HLA-231](https://jira.stsci.edu/browse/HLA-231).
**Changes**:
- filtered_table field 'fit_qual' now populated with correct value
- filtered_table field 'processMsg' now populated with correct value
> Hla 231 incorrect filtered table fields

- drizzlepac/hlautils/analyze.py
modified code to make sure field "compromised" is in filtered_table by default
> HLA 234: Add 'compromised' field in filtered_table by default

- README.md
> DOC: Add RT link to README

- conftest.py
- drizzlepac/alignimages.py
- drizzlepac/hlautils/analyze.py
- drizzlepac/hlautils/astroquery_utils.py
- drizzlepac/hlautils/get_git_rev_info.py
- drizzlepac/hlautils/testutils.py
This set of changes should include all the changes that were made to the hla_staging branch without contamination from master.  All subsequent PRs for the hla-staging branch should start from this PR after it has been merged.
All changes from the following closed PRs were verified and included in this PR: #304, #307, #308, #315, #317, #318, #321, #323, #327, #328, #330, #332, #333, #334.
> Repaired hla_staging branch manually

- drizzlepac/alignimages.py
This will replace #331 which was not based on hla-staging branch.
> Update to FWHM based on hla-staging branch instead

- drizzlepac/alignimages.py
This simple bug fix addresses the syntax problem with comparing an object to None.
> Fix table pep8

- setup.cfg
- tests/hla/test_apriori.py
Changes to correctly handle different instruments reference files and to update the test datasets to ones which more easily demonstrate the effects of the a priori solutions.  
These changes should address the problems seen in the regression tests with failures due to reference file problems.
> Updated datasets for this test

- tests/hla/test_apriori.py
https://github.com/spacetelescope/drizzlepac/pull/354 merged a set of tests that do not pass:
I am disabling these tests until they are fixed.
> Disable hla apriori tests

- doc/source/index.rst
Change name of products from 'Enhanced' to 'Advanced' as per HSTMO request.
> Change to Advanced Products

- drizzlepac/alignimages.py
Reset the limit on what RMS ratio would represent a valid solution from 10% to 100% of minimum RMS value.
> Update RMS limit to reasonable value

- CHANGELOG.rst
Remove numerous HLA-pipeline-related "bug fix" messages for a feature that have not yet been released. Instead, list all PRs that make up the new ``'Enhanced Pipeline Products'``.
> Merge all HLA-related logs into a single statement

- CHANGELOG.rst
- drizzlepac/sky.py
This PR fixes second error reported in #376 
CC: @mackjenn
> Fix MDRIZSKY not found for non-overlapping images

- drizzlepac/hlautils/pipeline_poller_utils.py
Fixed the bug introduced on previous commit in changing the input raw_filter to lower-case.
> Fix bug: Interpret poller from pipeline

- drizzlepac/hlautils/se_source_generation.py
This code generates the source generation catalogs for the `total` (white light) detection products, as well as the `filter`-specific catalogs for each `total` product.
> [WIP] Generation of SExtractor-like source generation catalogs

- drizzlepac/runhlaprocessing.py
This adds a working 'main()' function for the new 'runhap' bin interface to use.
> Add main for runhap to call

- drizzlepac/runhlaprocessing.py
DSB has requested that the command line interface return the status value for the process.
> Return status value

- LICENSE.txt
> DOC: Update year on license

- drizzlepac/hlautils/analyze.py
- drizzlepac/hlautils/se_source_generation.py
- drizzlepac/hlautils/sourcelist_generation.py
- drizzlepac/runhlaprocessing.py
A requirement for pipeline operations of this code is that a manifest file be generated to report the filenames of all the products produced from the input file.  This manifest needs to include not only the drizzle products, but also any headerlet files and source catalogs created as well.
> Create manifest file

- pyproject.toml
@mcara , I think this will make the bot does what you want.
> Customize stsci-bot behavior

- pyproject.toml
> Fix Azure by updating pyproject.toml

- drizzlepac/runastrodriz.py
- tests/hla/test_pipeline.py
Correct problems and add another test for handling non-CTE corrected singletons in the pipeline.
> Correct logic in runastrodriz for CTE singletons

- drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n6.json
- drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_any_n6.json
- drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_blue_n2.json
- drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_blue_n6.json
- drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n6.json
reset 'build' = True, 'clean' = true and removed 'input' 'output' from ALL ACS astrodrizzle json files in hap_pars/.
> updated ACS astrodrizzle json files

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/poller_utils.py
- drizzlepac/hlautils/product.py
The "if debug" was swallowing important error information so the statement was removed from hapsequencer.py.  Additional log statements (way points) were added to hapsequencer, poller_utils, and product.
> Added more logging to hapsequencer and removed "if debug"

- CHANGELOG.rst
- drizzlepac/updatehdr.py
This PR fixes issues #437 and #438
> Fix crash in update_from_shiftfile due to np.loadtxt

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/product.py
Added the trailer files (*trl.txt) to the output manifest for use by operations.
> Added trailer file to manifest

- MANIFEST.in
My apologies. I'm not sure how I managed to remove `pytest_cache` from the file.
> Fix errant deletion in MANIFEST.in

- drizzlepac/runsinglehap.py
Update version ID in runsinglehap to denote delivered dev version.
> Update version string

- drizzlepac/hlautils/catalog_utils.py
> Remove always-empty "TotMag(0.15)" and "TotMagErr(0.15)" from filter-product point-catalogs

- drizzlepac/runastrodriz.py
This set of changes addresses issues found during testing of HSTDP 2019.5, including:
- making sub-directories 'apriori' and 'aposteriori' dataset specific in name to support processing multiple datasets in the same directory as done under Condor (demonstrated and tested using j9r384030)
- fixing logic to recognize when drizcorr should be turned off due to lack of calibrated products (only raw) to process (demonstrated and tested using j9bc59wfq and j9r384fmq)
- correcting a syntax error in a string definition for an error case. (demonstrated and tested using ibbq01040)
- Restored correct behavior when all input exposures are bad, such as EXPTIME==0 for all in an ASN (demonstrated and tested using ibvz01010)
> Fix 2019 5

- drizzlepac/runastrodriz.py
Try again to get the new version of rmtree into runastrodriz.  Tested on jd5702030 and jc8x53010.
> New version of rmtree

- drizzlepac/runastrodriz.py
Another attempt at getting this code to successfully remove the sub-directories.
> More tweaks to try to remove directories

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/catalog_utils.py
- drizzlepac/hlautils/hla_flag_filter.py
- drizzlepac/hlautils/product.py
Added more columns containing photometry information for the Segment catalog. It is expected there will be some additional fixups due to changes in other outstanding issues being worked.  The code should be run in debug mode as a bug found where a needed image FITS file is being deleted prematurely is being addressed in a different PR.
- Changed sys.exit() to sys.exit(1) in hla_flag_filter.py (hla_nexp_flags()).
- Ensure the "Flag" column of all catalogs are updated with the modified flag values.
- Changed some logging from log.info to log.debug due to the large amount of output.
- Cleanup.
> Add segment columns

- drizzlepac/hlautils/cell_utils.py
This set of changes addresses problems uncovered when running this code on single exposures; namely,
- clip to shape of output WCS in order to avoid rounding errors made when defining output WCS
- ignore exposures which were not run through updatewcs (does not have WCSNAME defined)
These changes were tested on the datasets which demonstrated the original problems: jdrz9eygq and its ASN jdrz9e010 for the clipping problem, and  jdxr02iaq (ASN: jdxr02010) for the EXPTIME==0 exposures.
> Ignore bad data now and clip to output array shape

- drizzlepac/hlautils/cell_utils.py
These changes create masks for images and cells 10X faster than using ndimage.
> Use PIL to generate masks

- drizzlepac/hlautils/hla_flag_filter.py
Fix a silly typo introduced in earlier PR...
> Fixed typo

- drizzlepac/align.py
- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/product.py
Finally got the code to correctly manage the alignment reference catalogs generated during processing.
> Finally cleaning up reference catalogs correctly

- drizzlepac/align.py
- drizzlepac/alignimages.py
- drizzlepac/hapcatalog.py
- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/hlautils/analyze.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/hlautils/astroquery_utils.py
- drizzlepac/hlautils/catalog_utils.py
- drizzlepac/hlautils/ci_table.py
- drizzlepac/hlautils/config_utils.py
- drizzlepac/hlautils/get_git_rev_info.py
- drizzlepac/hlautils/hla_flag_filter.py
- drizzlepac/hlautils/hla_flag_filter_HLAClassic.py
- drizzlepac/hlautils/poller_utils.py
- drizzlepac/hlautils/processing_utils.py
- drizzlepac/hlautils/product.py
- drizzlepac/hlautils/se_source_generation.py
- drizzlepac/hlautils/sourcelist_generation.py
- drizzlepac/hlautils/testutils.py
- drizzlepac/runsinglehap.py
This PR addresses Issue #517.  Additional changes are pending feedback from individuals in operations testing.
> Added code to vet the poller input images viability for drizzling

- drizzlepac/hapsequencer.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_total_pre2012.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_total_pre2012.json
This PR resolves a issue raised by Jen Mack about dataset /internal/hladata/single_visit/jd9510 in [https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=hstdms&title=Astrometry+Testing](https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=hstdms&title=Astrometry+Testing)
> skystat updated from "mode" to "median" in all astrodrizzle *any_total*.json files

- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/runastrodriz.py
A number of bugs were found in initial testing of the new pipeline processing astrometry code for the HSTDP2019.5 quick-fix.  This PR addresses them as well as possible.
> Correct quick fix2019 5

- drizzlepac/hlautils/poller_utils.py
The sort_poller_table() sorts the rows of the poller information using PHOTFLAM as the primary key and the exposure time as the secondary key.
This fix addresses Issue #521.
> Issue521 sort poller

- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/runastrodriz.py
These are the exact same (approved) changes found in #561, except that these changes are intended to be used to update v3.1.4 without the rest of the changes made since 3.1.4 was made available for testing.
> Close files in align in v3.1.4

- CHANGELOG.rst
- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/runastrodriz.py
This 'cherry-picks' the changes from #555 into the 3.1.4x branch for testing as part of the 2019.5.1 quick-fix.
> Merge #555 into 3.1.4x branch

- drizzlepac/hlautils/cell_utils.py
- drizzlepac/hlautils/product.py
> Add SVM footprint keywords to product headers

- drizzlepac/tweakback.py
> Correct problem in tweakback

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/product.py
Retain alignment reference catalog at the end of processing and include the filename in the manifest file.
> Retain alignment reference catalog at the end of processing

- drizzlepac/imgclasses.py
> proposed bug fix for 2dhist int bin number requirement

- CHANGELOG.rst
- drizzlepac/imgclasses.py
@stsci-hack @srodney This PR effectively undoes #583 but is very similar in nature. It simply implements the same algorithm as in `tweakwcs` IMO is somewhat "safer" in the sense that it would err on the side of increasing the histogram and including more points.
This PR addresses the issue #582
> Fix crash due to float number of bins passed to histogram2d

- drizzlepac/hlautils/catalog_utils.py
Fixed a bug in creation of SBC catalogs. There is no CCDGAIN keyword in the FITS headers of SBC data as it is a MAMA detector!
> Do not look for CCDGAIN keyword in SBC FITS headers.

- drizzlepac/runastrodriz.py
This small PR includes changes to 'runastrodriz.py' to address:
- logic for turning on/off applying apriori WCSs through updatewcs just the same as was being done for aposteriori (align_to_gaia) processing
- putting the deletion of the sub-directories used for alignment into a try...except block to protect against instances where the OS does not allow a directory to be deleted yet.  
These changes only affect WHAT gets done during pipeline processing, without affecting the results for data that was already successfully processed.  It will result in the sub-directories being left behind during pipeline processing IF and ONLY IF it would have errored out before.  It should also now allow all data added to the SkipAlignment table used by the pipeline to process just like it did before the …
> HSTDP 2019.5.2 quick-fix

- CHANGELOG.rst
- drizzlepac/imgclasses.py
> Fix a bug in how minobj is used

- drizzlepac/hlautils/astrometric_utils.py
Verification of images which are mostly blank (like ibsl31030) get skewed by the noise in the background, as peaks in the noise end up being identified as sources in the overlap region.  This results in the computations of the differences being greater than the threshold for success, even though it is perfectly fine blank sky.  
This code recognizes 'blank' images as any image where the median of the sigma_clipped_stats is less than the RMS, which would put the median very close to 0 in most cases.  The code then median smooths the image with a 5x5 kernel and subtracts the originally computed background, then clips as 0.  This effectively removes the background from computation in the differences and allows any real sources to provide the only differences.
> Refine overlap diff for blank images

- drizzlepac/hlautils/astrometric_utils.py
Bug fix for computation of background to determine blank fields.
> Bug fix for overlap computation on blank fields

- JenkinsfileRT
Make use of new feature introduced here https://github.com/spacetelescope/jenkins_shared_ci_utils/pull/75 to accomplish this.
> Map stored token value on to a var that codecov honors.

- drizzlepac/align.py
- drizzlepac/devutils/alignment_viewer.py
- drizzlepac/hlautils/quality_analysis.py
- drizzlepac/runastrodriz.py
Update the alignment_viewer module to produce JSON products as an additional code-readable summary of the processed datasets.
> Fix various bugs

- setup.py
> Add PyYAML to the setup.py which is needed for HAP SVM processing.

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/svm_quality_analysis.py
Added a routine to the quality analysis module which compares the magnitude values between the Point and Segment catalogs for all filter level products.
> Added the compare_photometry() routine to the svm_quality_analysis.py module.

- drizzlepac/hlautils/get_git_rev_info.py
Initialize the return variable of the function get_rev_id() so the code does not crash.
> Ensure return variable is initialized.

- drizzlepac/hlautils/quality_analysis.py
Fix error found during HSTDP 2020.2rc1 testing of caldp_astrometry_drz_rc1 release.
> Fix an error condition for QA code

- drizzlepac/hlautils/quality_analysis.py
Adds logic to catch error case in QA code for pipeline processing to address Exception seen during pipeline testing of the code.
> Add error logic for pipeline QA code

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/svm_quality_analysis.py
- drizzlepac/wcs_functions.py
- Added new routine, report_wcs, to the quality tests.  This new test compares the crval, crpix, scale, and orientation between the various WCS solutions in the FLT/FLC images.
- Added call for new SVM quality test, as well as some text clean up in hapsequencer.
- Fixed a small bug/typo in wcs_functions.
> Added an additional test to svm_quality_analysis.py.

- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/runastrodriz.py
* Resolve HSTDP2020.2 WCS exceptions
* Fix HDRNAME and only apply hlet when hlet has been made
* Remove extraneous HDRNAME keyword from SCI headers
* Remove NoDetect warnings, fix typos
> Resolve HSTDP2020.2 WCS exceptions (#655)

- drizzlepac/align.py
- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/hlautils/catalog_utils.py
- drizzlepac/hlautils/cell_utils.py
- drizzlepac/hlautils/hla_flag_filter.py
- drizzlepac/hlautils/quality_analysis.py
This simply 'cherry-picks' updates for 'HSTDP2020.2rc2' into the release branch, as originally intended.
> Move rc2 to 318x

- drizzlepac/hlautils/photometry_graphics.py
Prototype graphics generation code for the SVM quality assessment using Bokeh.  This module is specifically designed for reading the photometry data and generating two plots, and also incorporates a preliminary JSON harvester written by Warren.  This module serves as a "proof of concept" experiment and is addressing JIRA HLA-322.
> Prototype Bokeh graphic to support SVM quality assessment data

- drizzlepac/hlautils/diagnostic_utils.py
- drizzlepac/hlautils/svm_quality_analysis.py
* see [JIRA ticket #348](https://jira.stsci.edu/browse/HLA-348)
**Summary of changes**
drizzlepac/hlautils/diagnostic_utils.py:
* added optional arguments "descriptions" and "units" to  HapDiagnostic.add_data_item() so that user can specify dictionaries containing more detailed descriptions and units of the elements of the data item being added
* updated read_json_file() to read in and return information stored in the new "descriptions" and "units" sections of the json files.
drizzlepac/hlautils/svm_quality_analysis.py: 
* added "descriptions" and "units" inputs in add_data_item() calls in the find_gaia_sources() test.
>  update diagnostic_utils.py to accept new inputs

- drizzlepac/haputils/svm_quality_analysis.py
The SVM Quality Analysis tests have been updated to use the "descriptions" and "units" parameters of the add_data_item() method, as well as minor clean-ups.
This issue is associated with Jira HLA-330.
> Updated SVM Quality Analysis tests

- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/quality_analysis.py
A series of errors were uncovered during the 06-17-2020 tests of the astrometry QA code.  These changes were based on the errors identified using 'jb7h07010' that reproduced the problems uncovered in the 06-17 tests.
> Fix cal QA errors found during testing

- drizzlepac/haputils/pandas_utils.py
- drizzlepac/haputils/wcs_graphics.py
- Modified pandas_utils.py to initialize and use the proper methods that be used for dataframes.
- Created the initial standalone version of wcs_graphics.py.
The current version of wcs_graphics.py is a standalone program.  In the coming Sprint a structure is to be build to accommodate and streamline the generation of graphics.
> Generated standalone version of wcs_graphics.py

- drizzlepac/haputils/quality_analysis.py
This set of changes implements the logic to only generate relative astrometric residuals for datasets which have an _a posteriori_ WCS solution determined by runastrodriz.  
When merged, this PR will close #700 along with Jira Ticket HLA-379.
> Only determine astrometric residuals for aposteriori WCSs

- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/quality_analysis.py
Pipeline Q&A vector plots were added to the set of plots being generated for the standard pipeline astrometry testing.  The code for creating vector plots in Bokeh comprises the bulk of the changes. 
In addition, though, the fitting was also updated to enforce a limit on the minimum number of objects to be included in the fit at 6, instead of the default value of 3 that comes with tweakwcs.
> Add pipeline Q&A vector plots

- drizzlepac/adrizzle.py
Simple fix for typo/oversight in adrizzle's teal interface.
> Fix WCSUTIL import from #710

- azure-templates.yml
Try removing these packages from the CI environment in an attempt to alleviate errors.
> Remove stsci.disttools and d2to1 from azure pipeline env.

- drizzlepac/haputils/diagnostic_utils.py
See JIRA ticket [HLA-336](https://jira.stsci.edu/browse/HLA-336)
**Summary of changes**
- diagnostic_utils.HapDiagnostic._instantiate(): Added code to remove the following sets of keywords from self.out_dict['header']: 
- D*VER
- D*GEOM
- D*DATA
- D*DEXP
- D*OUDA
- D*OUWE
- D*OUCO
- D*MASK
- D*WTSC
- D*KERN
- D*PIXF
- D*COEF
- D*OUUN
- D*FVAL
- D*WKEY
- D*SCAL
- D*ISCL
> Filter out specific drizzle-generated header keywords so that they will not be included in the "header" sections of SVM QA json files.

- drizzlepac/haputils/astrometric_utils.py
The functions for obtaining the astrometric catalog source positions from the web-service were updated to use the EPOCH parameter to obtain positions of the sources at the time of the observations.  This set of changes was implemented strictly for GAIADR2 catalog searches and any subsequent GAIA catalogs as they are the only ones with proper motions.  
In the process, the interpretation of the web-service results was changed from using the Python base 'csv' package to using
astropy.tables to directly interpret the results, vastly simplifying the code in the process.  The primary interface, create_astrometric_catalog, was also updated to allow the user to get ALL the columns from the web-service upon request, with the default being only to return the subset of columns needed for pipeline …
> Use EPOCH for GAIADR2 catalog positions

- doc/.rtd-environment.yml
- setup.py
No longer a dependency as of #440 .
> Remove pysynphot as dependency

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Implementation of a diagnostic which determines when to use the RickerWavelet2DKernel (aka MexicanHat) based upon information provided by R.White, as well as the implementation of the new kernel (photutils) and reworking of the code to accommodate the changes.
> Update to Segmentation SVM processing via use of RickerWavelet kernel for crowded fields

- drizzlepac/haputils/svm_quality_analysis.py
Updated svm_quality_analysis module to generate additional data for the output
JSON files to support requested diagnostic information (delta-mag vs mag and sky
separation vs mag). Updates done in the compare_ra_dec_crossmatches() function.
> Updated svm_quality_analysis module to generate additional data

- drizzlepac/haputils/quality_analysis.py
- drizzlepac/haputils/svm_quality_analysis.py
See JIRA ticket [HLA-399](https://jira.stsci.edu/browse/HLA-399).
**Summary of updates**
- svm_quality_analysis.py: wrapped calls to individual test subroutines in run_quality_analysis() in try/except logic to add fault tolerance.
- quality_analysis.py: wrapped calls to individual test subroutines in run_all() in try/except logic to add fault tolerance
> PIPELINE and SVM Q&A: Capture exceptions generated by the PIPELINE and SVM quality analysis routines

- drizzlepac/haputils/svm_quality_analysis.py
Improved comparison of sources found based on the white light image by protecting
against the cases where no sources are found and no catalog is actually written.
This allows the collection of data for the JSON files to continue as only the comparison
is skipped versus the entire evaluation function.
Name of the output number of sources JSON file was updated to match the convention
used by the majority of the other tests.
> Improved JSON data collection for "number of sources" statistics

- setup.py
A less controversial version of #778 by removing the things that you definitely are not using. Also see #777 
cc @jhunkeler and @rendinam
> MNT: Remove nose and move scikit-image dependencies

- drizzlepac/runastrodriz.py
Pipeline processing could end up with any of a number of possible outcomes for the image WCS definition.  This change inspects the updated input FLT and FLC files (whatever are present) and updates or adds the WCSTYPE keyword for ALL WCS solutions in the SCI headers.  This insures that all alternate WCS solutions, as well as the PRIMARY WCS, have defined WCSTYPE keywords.  
Closes #766 .
> Update all WCSs with correct WCSTYPE keyword value

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/processing_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
These code changes implement trimming of the source catalogs from both the filter products and the total product based on a Flag value < 5.
> Trim source catalogs based on Flag value 

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Modified segmentation algorithm to use exclusion mask defined inHAPCatalogBase to remedy false source detections.  Combine some diagnostic output generation and some clean up.  Reset the negative threshold value to 0.0.
> Refine segmentation algorithm

- drizzlepac/haputils/catalog_utils.py
Add code to write a "regions" file (*.reg) for use with ds9 in the segment write_catalog method to capture the trimmed data for overplot. Retain the previous "regions" file which is created just after all "sources" have been identified.  This file is now
*_all.reg.
> Write the Segment "regions" file (*.reg) for use with ds9 after the catalog sources have been trimmed

- azure-templates.yml
- drizzlepac/hapsequencer.py
- setup.py
Implements environment variables for SVM catalog generation.  If no environment variables are found, it will default to generating the catalogs for that detector.  
This addresses [HLA-444](https://jira.stsci.edu/browse/HLA-444) and will close #843 .
> Implement env variables for catalog generation

- drizzlepac/devutils/comparison_tools/interdetector_sourcelist_crossmatch.py
- See [JIRA ticket HLA-439](https://jira.stsci.edu/browse/HLA-439)
- See Git issue #826 
**SUMMARY**
- This is just the simple addition of interdetector_sourcelist_crossmatch.py to the codebase. Nothing more.
> Add interdetector crossmatch statistics utility "interdetector_sourcelist_crossmatch.py" to comparison_utils

- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/poller_utils.py
- drizzlepac/haputils/product.py
The names of the input FLC files along with the output drizzle products had problems with the names being inconsistent.
These changes should close #830 .
> Make mvm names consistent

- doc/source/catalog_generation.rst
The catalog generation is currently being updated to:
- add information regarding the Segmentation portion of the algorithm,
- move the preliminary descriptions (background determination, masks, etc.) which apply to both point and segment algorithms to the beginning of the document, and
- re-number/re-order the sections.
> Update of catalog generation documentation

- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/poller_utils.py
- drizzlepac/haputils/product.py
These changes are intended to define both the 'fine' and 'coarse' layers for WFC3/IR sky cells.  
Closes #819 and [HLA-434](https://jira.stsci.edu/browse/HLA-434)
> Add FINE and COARSE IR SkyCell layers

- drizzlepac/haputils/poller_utils.py
Relevant JIRA Tickets/Git issues:
- JIRA ticket [HLA-388](https://jira.stsci.edu/browse/HLA-388)
- Git issue #728 
Summary of changes:
- poller_utils.py:
- added code to build_poller_table() so that it can process MVM poller files with the new format.
-Added logic to build_poller_table() to check that each file listed in the poller file exists in the current working directory. If a file is missing, it's copied over from the path specified in the poller file. Failing that, an exception is raised.
> Manage MVM input data

- CHANGELOG.rst
- drizzlepac/acsData.py
- drizzlepac/imageObject.py
- drizzlepac/nicmosData.py
- drizzlepac/processInput.py
- drizzlepac/stisData.py
- drizzlepac/wfc3Data.py
- drizzlepac/wfpc2Data.py
* Rename common static mask file
* Insure static mask name is lower-cased
* update change log
> Rename static mask (#876)

- drizzlepac/imageObject.py
Add this PR to the release branch.
> Create more specific static mask name (#888)

- CHANGELOG.rst
Updated the log file to reflect the final release of 3.2.0.
> Update log file for 3.2.0 final release

- drizzlepac/astrodrizzle.help
- drizzlepac/imagefindpars.help
- drizzlepac/refimagefindpars.help
Disappointingly, I got the simple arithmetic wrong (:
> Fix arithmetic in the docstring for dqbits

- CHANGELOG.rst
Update version information after 3.2.0 release.
> Update version info from 3.2.x

- CHANGELOG.rst
- drizzlepac/adrizzle.py
- drizzlepac/astrodrizzle.py
- drizzlepac/hapsequencer.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/outputimage.py
- drizzlepac/runastrodriz.py
- drizzlepac/util.py
These changes add a new keyword, _DRIZPARS_, to the Primary header of the final drizzle product which provides the filename of the trailer file (or logfile) that contains the processing comments generated when creating the drizzle product.  
In addition, the `adrizzle.py` module was cleaned up to meet the latest Flake8 standards.
> Add DRIZPARS keyword to drizzle header

- doc/source/catalog_generation.rst
- doc/source/conf.py
- doc/source/singlevisit.rst
Updated the Single visit Mosaic user documentation.
> Updated the SVM user documentation

- drizzlepac/hapsequencer.py
In particular, when the active WCS solution is being replaced, the current active solution (and any alternative WCS solutions from the same distortion model) are saved as headerlet extensions (if they are not duplicates according to their
HDRNAME).  Duplicates are deleted.
> Improved the way WCS solutions are manipulated for visits with Grism/Prism data

- drizzlepac/haputils/cell_utils.py
The SREGION computation from #951 was susceptible to a number of error conditions.  These changes completely replace that algorithm with one based on wcs.calc_footprint() (and related edge pixel) positions to avoid those previous error conditions.  This new version not only improved on the vertices identified in the previous PR, but uses an algorithm which is not susceptible to as many error conditions.  
The vertices are based on edges defined by the corners (and mid-points of each outer edge) of each input chip and where they intersect the total footprint.   
This code was tested against all the datasets listed in #951 as well as data from visit ia0m04 which triggered the exceptions in testing on 1082 datasets.
> New SREGION computation based on WCS footprint

- drizzlepac/hapsequencer.py
Code currently appears to be working fine now with traps for exceptions.  I just need to understand why some of the exceptions are being raised in the first place.  Examining the headerlet code in stwcs.
> Debugging issues with archiving and restoring WCS solutions from headerlets

- drizzlepac/haputils/catalog_utils.py
Updates made to the Point and Segment catalogs to make them more consistent in terms of column units, descriptions, and formats.  This references Jira HLA-507.  The X and Y column names (X-Center vs X-Centroid) were explicitly NOT changed at this time.  These name propagate to other modules.  Also, the issue with nulls/nans/"" was not addressed.
> Updates to catalog columns

- drizzlepac/haputils/astrometric_utils.py
Requests for astrometric catalogs up until now have resulted in catalogs automatically corrected for the epoch of the observations.  This set of changes enables more control over what epoch the user can request for the astrometric catalog, specifically allowing the user to get the native epoch of the catalog.  These changes also remove the code that was limiting the returned catalog to only sources with measured proper motions, as many sources, in the GAIA catalog at least, don't have proper motions due to being external galaxies or globular clusters, yet they are perfectly valid.
> Enable user epoch selection in creating GAIA catalogs

- drizzlepac/align.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
- JIRA Ticket [HLA-509](https://jira.stsci.edu/browse/HLA-509)
- Git issue #979 
- PR #1002 
- Added subroutine align.determine_fit_quality_mvm_interface() which runs align.determine_fit_quality() and returns all the return values of align.determine_fit_quality() along with a boolean value "is_good_fit" indicating if the fit is good or not. 
- Moved the hard-coded global variables at the top the script to the "determine_fit_quality" sections of the *_alignment_all.json parameter files; Refactored impacted lines of code in align.perform_align(), align.determine_fit_quality() and align.determine_fit_quality_mvm_interface() accordingly.
- This PR provides the necessary code for @mdlpstsci's PR #1002 to move forward.
> Determine success criteria for MVM alignment fitting

- drizzlepac/hapmultisequencer.py
- drizzlepac/hapsequencer.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
WIP: Modified align_to_gaia() method of the FilterProduct. Automatically, tries to perform matching and fit using a method list and catalog list. The first satisfactory fit is used.  Need the evaluation criteria for a "successful" fit, and possibly put some values into a configuration file.
> WIP: Modified align_to_gaia() method of the FilterProduct to use logic provided by Astrometry WG

- drizzlepac/haputils/product.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
Implemented looping over catalogs, methods, and fit geometries where the fit geometries are the inner-most loop.  The same align_to_gaia method is used for both SVM and MVM.  Modified configuration files to support the looping.
> Modified to have a single align_to_gaia method which loops over catalogs, fit methods, and fit geometries

- drizzlepac/haputils/astrometric_utils.py
A simple set of additions to increase the useful information reported in the logs in the event that the astrometric catalog web service does not work as expected and returns an error.
> Add more diagnostic info to logs

- drizzlepac/updatehdr.py
Minor refactoring of the code in `updatewcs_with_shift` to make it more robust to a situation when an "in-memory HDUList" is provided as input in which case their `filename()` member can return `None`. There is a remote possibility it may `fix` #1022 
> Refactor code in updatewcs_with_shift

- drizzlepac/align.py
This moves the initialization of the fit from outside the iterations over fitgeoms and fit type to inside so that the same starting WCS is used for each alignment attempt.
> Initialize fit for each attempt

- drizzlepac/buildmask.py
> Switch to using astropy's bitmask module.

- drizzlepac/align.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/astroquery_utils.py
- drizzlepac/haputils/testutils.py
- tests/hap/test_align.py
- tests/hap/test_randomlist.py
Update some nightly regression tests to be consistent with current master.
> Update some nightly regression tests

- drizzlepac/haputils/hapcut_utils.py
VERY MUCH WIP.  Create utilities to: (1) find files in the region of interest, (2) download the files, and (3) make cutouts from the files.
> Initial version of MVM tools: find files in the region of interest,

- drizzlepac/haputils/astrometric_utils.py
Fix problems with source identification in astrometric_utils caused by changes in #1096, with the errors manifesting as failures in the nightly RT results.
> Fix amutils after update to PHOTUTILS 1.1.0

- LICENSE.txt
- pyproject.toml
- setup.cfg
Try to get package to build under PIP.
> Update pyproject to use oldest-supported-numpy

- drizzlepac/haputils/make_poller_files.py
**Relevant Ticket**
-  [HLA-572](https://jira.stsci.edu/browse/HLA-572)
**Summary of changes**
This PR addresses issues raised by @mdlpstsci  regarding a couple of UX bugs in make_poller_files.py. Fixes/improvements include the following:
- Added additional logic to throw an exception if users don't specify a skycell name when creating a MVM poller file
- Added additional logic to throw an exception if users don't specify a properly formatted skycell name when creating a MVM poller file
- Refactored the fits file location subroutine to make it more flexible and the logic more robust.
- Assorted docstring improvements and updates
> Improve make_poller_files.py

- CHANGELOG.rst
Update change log to reflect all changes in the code since v3.2.0 was released.
> Update change log for v3.3.0

- pyproject.toml
Get numpy requirement sorted out for release.
> Fix numpy requirement for release

- drizzlepac/hapsequencer.py
Fixed a bug which caused the proper naming of the output manifest file to be botched.  The manifest filename is now properly constructed if the main input is a poller file (no specific filename format expected), a user-defined filename
containing a list of files, or a Python list.  In the latter two cases, the manifest filename is constructed by interrogating
the primary header of the first file for information.  In the poller file case, the total data product has a manifest filename attribute which is used.  If something goes completely amiss, the manifest filename will be "manifest.txt".  In all other cases the manifest filename will be of the form instrument_programID_obsetID_manifest.txt (e.g.,wfc3_b46_06_manifest.txt).
> Fixed a bug which caused the proper naming of the output manifest

- drizzlepac/hapsequencer.py
- Moved initialization of grism and ramp lists, as well as the found_data indicator before the call to poller_utils.  Moving the list initialization ensures no exception will be generated upon exit.
- Do not add the "no_data_trl" (no data being processed trailer file) to the product_list.
- Only append the the astrodriz trailer file to the total trailer file if data_found = True.
- Updated comments as necessary.
> Create an empty manifest file for datasets which do not process (e.g., Grism/Prism only)

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
Updated release branch with changes from:
- #1174 
- #1175 
- #1178
- #1181
> Cherrypick rc6

- drizzlepac/devutils/analyze_mvm_gaia_alignment.py
- drizzlepac/devutils/comparison_tools/compare_sourcelists.py
- drizzlepac/haputils/comparison_utils.py
**Relevant JIRA tickets and Github issues**
- [HLA-405](https://jira.stsci.edu/browse/HLA-405)
- #769 
**High-Level Summary**
- Created _analyze_mvm_gaia_alignment.py_, a script that statistically quantifies how well aligned sources in a given MVM product are to GAIA sources in the FOV by statistically characterizing the differences and the X, Y and RA/DEC positions of GAIA sources as reported by astrometric_utils to the positions of sources  found by DAOFIND based on said GAIA sources
- Made a handful of backwardly compatible changes to comparision_utils.py and compare_sourcelists.py to support the functionality of analyze_mvm_gaia_alignment.py
> Create tool to quantify the quality of the alignment to GAIA sources in MVM products

- tests/hap/test_svm_ibqk07.py
- tests/hap/wfc3_bqk_07_input.out
PyTest test_svm_ibqk07 which is a WFC3 dataset using both IR and UVIS detectors, though the IR and UVIS have different WCS solutions.
> Adding a new WFC3 test for both UVIS and IR images and catalogs.

- tests/hap/test_svm_ibyt50.py
- tests/hap/wfc3_byt_50_input.out
Adding WFC3 PyTest test - IR and UVIS detectors.  Each detector has two exposures using a single filter.
> Adding WFC3 PyTest  - IR and UVIS

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/processing_utils.py
These changes insure that blank total products generate empty catalogs instead of throwing an Exception.
> Add logic to create empty catalogs for blank data

- drizzlepac/haputils/processing_utils.py
These changes fix the logic used to add the HAPEXPNAME column to the HAP drizzle products, a problem introduced by changes made in #1205.  
The logic was modified to use the TotalProduct class method '.find_member()' to get the HAPProduct instance associated with the input image so that it can have the right information for the column.  Additional logic is also implemented to correctly handle (rare?) cases when no exposures can be found (naming mismatch?) to avoid re-creating the problems that triggered the need for #1205.
These changes were tested using data from visits **j94sk1** and **ja1x36**.
> Fix logic for adding HAPEXPNAME to HDRTAB table

- drizzlepac/runastrodriz.py
Logic needed to be changed to limit the check for consistent WCSs (implemented in #1187) to only the most current IDCTAB, not WCSs based on older calibrations.  This check is needed to avoid imprinting mis-alignment stemming from different zero-points of the different WCSs, a problem seen while developing #1187.
> Prevent WCS consistency update from overwriting latest idctab

- drizzlepac/haputils/cell_utils.py
Fixes https://github.com/spacetelescope/drizzlepac/issues/1223
> Remove guppy import

- drizzlepac/haputils/testutils.py
- tests/hap/test_apriori.py
Pulling change to pytest test from master to the release branch.
> Update apriori test to be more explicit with errors (#1233)

- pyproject.toml
Modified toml specifically to use "oldest-supported-numpy".
> Update toml file to for NumPy support

- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/processing_utils.py
A custom algorithm has been implemented specifically for use in identifying sources in SBC data for the purposes of alignment.  This algorithm takes advantage of the fact that SBC data has no cosmic-rays by applying the Laplacian-of-Gaussian operator to the image and selecting the subsequent peaks as sources.  This results in a vast majority of the actual sources getting identified without relying on comparisons to PSFs (model or empirical).  Increasing the number of valid sources identified in SBC exposures provides an opportunity for the alignment algorithm to find matches to sources from astrometric catalogs, while passband differences will still result in confusion in cross-matching leading to failures to align the exposure.  Still, these changes can only benefit alignment of SBC …
> Improve source detection for SBC data 

- drizzlepac/align.py
- drizzlepac/buildwcs.py
- drizzlepac/hapmultisequencer.py
- drizzlepac/hapsequencer.py
- drizzlepac/mapreg.py
- drizzlepac/photeq.py
- drizzlepac/pixreplace.py
- drizzlepac/pixtopix.py
- drizzlepac/pixtosky.py
- drizzlepac/resetbits.py
- drizzlepac/runastrodriz.py
- drizzlepac/skytopix.py
- drizzlepac/tweakback.py
- drizzlepac/tweakreg.py
- drizzlepac/updatenpol.py
Fixes the problems with version imports described in #1270 .
> Change to using relative version imports

- conftest.py
- tests/hap/svm_input.lst
- tests/hap/test_alignpipe_randomlist.py
- tests/hap/test_pipeline.py
- tests/hap/test_randomlist.py
- tests/hap/test_run_svmpoller.py
- tests/hap/test_svm_j97e06.py
- tests/hap/test_svm_wfc3ir.py
Remove the "skip" to enable the tests to execute.  PyTest criterion may have been modified to make the test succeed or be more general.
> Modified three tests to remove the "skip" to enable the tests to execute

- pyproject.toml
- setup.cfg
* Update requirements to allow astropy 5.0 use
* Removed pyproject restrictions on astropy
> Update requirements to allow astropy 5.0 use (#1280)

- CHANGELOG.rst
* Update Release Notes for v3.4.0 release
* Add notes on new features
* Keep all updates
* Add updated list of PRs to release notes
* Address review comments
* Fixed typos
> Add release notes for v3.4.0

- drizzlepac/ablot.py
- drizzlepac/adrizzle.py
- drizzlepac/astrodrizzle.py
- drizzlepac/buildmask.py
- drizzlepac/buildwcs.py
- drizzlepac/createMedian.py
- drizzlepac/drizCR.py
- drizzlepac/imagefindpars.py
- drizzlepac/mapreg.py
- drizzlepac/photeq.py
- drizzlepac/pixreplace.py
- drizzlepac/pixtopix.py
- drizzlepac/pixtosky.py
- drizzlepac/refimagefindpars.py
- drizzlepac/resetbits.py
- drizzlepac/skytopix.py
- drizzlepac/staticMask.py
- drizzlepac/tweakback.py
- drizzlepac/tweakreg.py
- drizzlepac/updatenpol.py
- drizzlepac/util.py
* Reset tasknames to work with TEAL
* Set basename without packagename
> Reset tasknames to work with TEAL (#1285)

- setup.cfg
Further restrict the markupsafe dependency.
> Lower markupsafe dependency again (#1290)

- .github/workflows/publish-to-pypi.yml
See spacetelescope/action-publish_to_pypi#18
> skip building wheels on i686

- .github/workflows/publish-to-pypi.yml
Revise publish script to use modified version of template.
> Use modified publish script for release

- azure-templates.yml
- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/comparison_utils.py
- drizzlepac/haputils/get_git_rev_info.py
- drizzlepac/haputils/product.py
- drizzlepac/haputils/svm_quality_analysis.py
- drizzlepac/wcs_functions.py
- tests/hap/test_svm_ibqk07.py
- tests/hap/test_svm_ibyt50.py
- tests/hap/test_svm_j97e06.py
Update 3.4.1 release candidate branch for rc4 release with:
- Refine HAP Pytests success criteria (#1313) 
- Synchronize output WCS specifications for SVM processing (#1312)
- Smooth out determination of S_REGION vertices (#1315)
- Ignore git information for installations in conda envs (#1309)
> Update for rc4

- setup.cfg
> Restrict version of Photutils to < 1.4.0.

- CHANGELOG.rst
This simply added release notes to describe the public release of v3.4.1.
> Add release notes for 3.4.1final

- CHANGELOG.rst
Add release notes for v3.4.1 final (public release).
> Add release notes for 3.4.1final (#1328)

- .github/workflows/publish-to-pypi.yml
Update the github actions script for publishing to pypi.
> Pull changes from #1299 to master

- drizzlepac/hapsequencer.py
These changes add logic to the code used to archive WCS solutions when selecting the common WCS to use in visits containing Grism/Prism exposures to not archive a WCS if the name indicates it is already a duplicate.  A duplicate WCS is one created automatically by STWCS by appending an integer to the end of the WCSNAME.  Unfortunately, these solutions have been saved in the astrometry database and cause this code to throw an Exception.  This code simply recognizes such WCS solutions and, in essence, checks if their 'parent' WCS is already archived instead.   
This code was tested using data from visit jc1b01, one of the visits reported by operations as triggering the Exception during pipeline processing.
> Avoid archiving duplicate WCS solutions in SVM processing

- setup.cfg
This updates the dependencies in 'setup.cfg' so that fixes found in fitsblender and stsci.skypac for recent PRs are installed as well.
> Update installation dependencies for fitsblender and skypac

- drizzlepac/hapmultisequencer.py
- drizzlepac/hapsequencer.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/analyze.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/pars/acs_mvm_header_hap.rules
- drizzlepac/runastrodriz.py
- pyproject.toml
- setup.cfg
Create v3.4.2rc0 release candidate on 3.4.1x based on master, without #1351.
> Generate 342rc0

- drizzlepac/haputils/analyze.py
- drizzlepac/runastrodriz.py
These changes simply back out #1351 from this release branch (for now?).
> Remove implementation of bad_guiding check

- drizzlepac/haputils/mvm_quality_analysis.py
WCS information has been reorganized to be better grouped according to its skycell name and, as a result, it also produces a more compact JSON file.
> Reorganized how information is stored in the JSON files

- azure-templates.yml
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/config_utils.py
This simply adds Python 3.10 tests to the suite run on each PR and build.
> Add Python 3.10 tests

- drizzlepac/haputils/catalog_utils.py
Ensure local gain variables are set for all detectors.
> Ensure the gain variables are defined for all detectors

- CHANGELOG.rst
Update the change log to document changes made since v3.4.2 was released.
> Update change log for v3.4.3

- CHANGELOG.rst
Updates change log to include references for v3.4.2 and v3.4.3.
> Update 343 changelog

- CHANGELOG.rst
* Update change log for v3.4.3 (#1427)
* Fix formatting in change log
> Update 343 changelog (#1428)

- CHANGELOG.rst
Update the change log in preparation for v3.5.0 release candidate.
> Update change log for v3.5.0 release candidate

- CHANGELOG.rst
The release version data was incorrect for v3.5.0.  Updated to the proper date.
> Updated the release date of v3.5.0.

- doc/source/catalog_generation.rst
Added documentation which indicates how to read programmatically the Point and Segmentation catalogs with Astropy or Pandas.
> Documented how to read programmatically the catalog files

- drizzlepac/align.py
- drizzlepac/haputils/astroquery_utils.py
The logic used in `align.check_and_get_data()` failed when some of the files were already present and others were not.  The nightly regression tests rely on this function to make sure the necessary input files are present in the local directory for running the tests.  However, the ASN file was only used to get the specific FLT/FLC files needed for the tests, so they were not present for some tests while the FLT/FLC images were present.  The changes here made sure that if an ASN table was provided by the test as input, and as needed by astroquery to get the data, then that file now gets downloaded and used to make sure all members are present as requested.  If the members were already there, those local copies are still used and not downloaded again from the archive.  
In addition, more …
> Fix logic in astroquery_utils to properly support regression testing

- drizzlepac/align.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/analyze.py
- drizzlepac/haputils/astroquery_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/runastrodriz.py
- drizzlepac/util.py
- tests/wfpc2/test_wfpc2.py
Updates to the release branch 3.5.1x which currently has RC0 and these fixes constitute RC1 and include tickets/hashes in reverse time order (older tickets first as this is how the tickets MUST BE APPLIED to the release branch):
#1485 eb2b2cdc3d6771731d058656aad4fd7625c2ef52
#1487 69647de7556306bb6e10276494a09630676cbb81
#1488 166b231f1ece2214f2cef262bd7dc5b4a3e59944
#1486 2df137e8e73ea4776c29c8620dbc7499e3863c1f
#1490 681852e5a5ac2265c390f83e08b6b1a3f771fcc4
#1489 895d5d48260fee35c000ba6069a17b59f37f0a62
#1491 0523fe78f0a6d548b1342f70208b5511af35bfda
> Create new release candidate 351rc1

- requirements-dev.txt
attempt to resolve `astropy` build errors in Jenkins job `RT DRIZZLEPAC` (https://plwishmaster.stsci.edu:8081/job/RT/job/drizzlepac)
> use nightly wheel for `astropy`

- CHANGELOG.rst
Updated the CHANGELOG.rst file to include all changes relevant to the user since the last release.
> Updated the CHANGELOG.rst file to prepare for release

- pyproject.toml
Removed extraneous characters in pyproject.toml file.
> Fix typo in pyproject.toml.

- pyproject.toml
> Fix typo in pyproject.toml. (#1506)

- pyproject.toml
> Fix another typo in pyproject.toml (#1508)

- drizzlepac/haputils/cell_utils.py
Simple update to the docstring for the SkyCell class to include examples of how to initialize this class interactively.
> Update SkyCell docstring with examples

- JenkinsfileRT
Resolves [SPB-1246](https://jira.stsci.edu/browse/SPB-1246)
This PR attempts to diagnose the issue in [SPB-1246](https://jira.stsci.edu/browse/SPB-1246) by moving the root to be within `clone/tests_output`
> try setting root directory to be within `clone`

- JenkinsfileRT
Reverts spacetelescope/drizzlepac#1515 - it did not solve the issue
> Revert "try setting root directory to be within `clone`"

- pyproject.toml
Add `astrocut` an yet another dependency for the RTD docs build.
> Add astrocut to RTD build

- drizzlepac/align.py
- drizzlepac/devutils/comparison_tools/compare_sourcelists.py
- drizzlepac/devutils/search_skyframes.py
- drizzlepac/haputils/astroquery_utils.py
- drizzlepac/haputils/graph_utils.py
- drizzlepac/haputils/which_skycell.py
Fixed a small batch of DeprecationWarning and SyntaxWarning messages in a effort to begin to clean up the code.
> Fixed some Deprecation and Syntax Warnings

- JenkinsfileRT
Updated Python version and removed deprecated channel.  Added and pinned ci-watson.
> Updated JenkinsfileRT

- requirements-dev.txt
Resolves [SCSB-69](https://jira.stsci.edu/browse/SCSB-69)
Adds `numpy` to the `devdeps` tests
> test against pre-built binaries of `numpy`

- CHANGELOG.rst
- drizzlepac/haputils/cell_utils.py
- drizzlepac/minmed.py
Added two additional fixes from master onto the release branch.
4c27d60 HLA-1029
029935f HLA-1573
> Newcandidate 361rc1

- drizzlepac/haputils/config_utils.py
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n1.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n3.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_total.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2_wfpc2_index.json
Updated JSON files for HAP WFPC2. *_any_1, _any_2, _any_3, _any_4, and _any_total added. *_any_6 removed.
> HLA-1052: Updated WFPC2 drizzle parameters for HAP

- drizzlepac/align.py
> Added or improved some log messages.

- drizzlepac/haputils/catalog_utils.py
Small changes to make_wht_masks() including in-line comments, doc strings, and type hints.
> Added docs to make_wht_masks() in catalog_utils.py

- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/analyze.py
- drizzlepac/haputils/poller_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/runastrodriz.py
Resolves [HLA-1145](https://jira.stsci.edu/browse/HLA-1145)
Closes #
This PR addresses the MVM failure due to HAPProduct constructor mismatch (#1693)
commit 2b91fc5
> HLA-1150: MVM failure due to HAPProduct constructor mismatch (#1693)

- CHANGELOG.rst
[How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)~
> finalize changelog entry

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
- drizzlepac/runastrodriz.py
- pyproject.toml
This change does not affect the default build python version, but does specify a requirement to anyone using the code.
> pyproject.toml specify python_requires >=3.10

- tests/hap/test_svm_hrcsbc.py
- tests/hap/test_svm_ibqk07.py
- tests/hap/test_svm_wfc3ir.py
Resolves [HLA-1215](https://jira.stsci.edu/browse/HLA-1215)
Closes #
Modified PyTests which were actually previously fixed in a different"science" commit.  However, this commit was not part of the "Infrastructure Release Candidate" so I am making small changes so the tests will pass for the Release Candidate.
- [X ] updated or added relevant tests
> Modified PyTests

- CHANGELOG.rst
- tests/hap/test_svm_hrcsbc.py
- tests/hap/test_svm_ibqk07.py
- tests/hap/test_svm_wfc3ir.py
Closes #
Merging latest change on main (794506f) to address PyTest failures in a standalone fix (i.e., not including any other updates) for the Release Candidate of Drizzlepac.  Change from PR#1748 on Drizzlepac main.
> Modified PyTests (#1748) and fixed conflicts on cherry-pick.

- CHANGELOG.rst
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1222](https://jira.stsci.edu/browse/HLA-1222)
Closes #1771
Add an update from main branch to the release branch, as well as update the CHANGELOG.rst for only modifications on this release branch.
SVM: Reconcile removal of bad segments from segmentation image with removal of corresponding rows from the "total" or white light source catalog (#1771)
> HLA-1222: Drizzlepac - new release candidate v3.7.0rc2

- JenkinsfileRT
This PR reverts a small change that was made to the jenkinsRT in #1766 when I was trying to fix the test. This should now work as intended. 
[Jenkins test](https://plwishmaster.stsci.edu:8081/job/RT/job/Drizzlepac-Developers-Pull-Requests/66/)
> Fix jenkins pytests

- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1248](https://jira.stsci.edu/browse/HLA-1248)
Closes #
This first update to the PR is to address outright bugs when generating the RickerWavelet kernel.   In essence, a proper sigma (vs the FWHM) is now provided to the RickerWavelet2DKernel constructor, and the normalization is handled in a new method, _ricker_matched_kernel_, written by R.L. White where the normalization causes the RickerWavelet core to match the Gaussian core.
> HLA-1248: Bug fixes and enhancements for the segmentation catalog wrt the RickerWavelet kernel

- .github/workflows/build.yml
- drizzlepac/__init__.py
- pyproject.toml
- setup.py
Resolves [SCSB-149](https://jira.stsci.edu/browse/SCSB-149)
> ensure extension modules are present in built wheel

- drizzlepac/ablot.py
- drizzlepac/adrizzle.py
- drizzlepac/devutils/comparison_tools/starmatch_hist.py
- drizzlepac/findobj.py
- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/config_utils.py
- drizzlepac/haputils/starmatch_hist.py
- drizzlepac/imgclasses.py
- drizzlepac/pixreplace.py
- drizzlepac/updatehdr.py
resolves [SCSB-151](https://jira.stsci.edu/browse/SCSB-151)
Closes #1799
This PR addresses issues raised by SonarQube at https://plsonarqube.stsci.edu/project/issues?resolved=false&types=BUG&inNewCodePeriod=true&id=drizzlepac
> fix (some) SonarQube issues

- doc/source/conf.py
https://plsonarqube.stsci.edu/security_hotspots?id=drizzlepac
> change instances of `http` to `https`

- CHANGELOG.rst
- drizzlepac/haputils/astrometric_utils.py
Resolves [SCSB-150](https://jira.stsci.edu/browse/SCSB-150)
This PR addresses some `AstropyDeprecationWarning`s occurring in recent CI runs.
[jenkins test](https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FDrizzlepac-Developers-Pull-Requests/detail/Drizzlepac-Developers-Pull-Requests/81/pipeline)
> resolve warnings

- JenkinsfileRT
Resolves [HLA-1266](https://jira.stsci.edu/browse/HLA-1266)
Closes #
Newcandidate 371rc3 - Fixes (by JH) the JenkinsfileRT with regard to codecov.  JH ticket PR#1816.
> Newcandidate 371rc3 - addresses codecov issues

- CHANGELOG.rst
- drizzlepac/haputils/astrometric_utils.py
Closes #
This PR reverts the changes done in #1798 in order to accommodate further thought and testing with the newer functions of Photutils.
> Revert1798 warnings

- CHANGELOG.rst
- JenkinsfileRT
- doc/source/mast_data_products/hap-parameters.rst
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/hla_flag_filter.py
- drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
- pyproject.toml
- tests/hap/test_svm_ibqk07.py
- tests/hap/test_svm_ibyt50.py
Resolves [HLA-1277](https://jira.stsci.edu/browse/HLA-1277)
Closes #
This PR is to document the tagging of Drizzlepac v3.7.1rc5 in preparation for the generation of the HSTDP-2024.2.0 Release Candidate 2.
> Drizzlepac: Preparation and Tagging of Release Candidate RC5

- pyproject.toml
Closes #
Test for RT for new truth files.
> Test for RT, set NumPy<2.0 in dependencies

- doc/source/mast_data_products/astrometry.rst
Resolves [HLA-1283](https://jira.stsci.edu/browse/HLA-1283)
This PR adds an animation as an animated gif to the astrometry section of the readthedocs.
> HLA-1283: Added drizzlepac animation to the docs

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
- CHANGELOG.rst
- JenkinsfileRT
Resolves [HLA-1269](https://jira.stsci.edu/browse/HLA-1269)
Closes #1673
This PR includes new testing for python 3.12 for Jenkins and github actions. Several other tests were added for github actions and both the CI and CI_CRON github actions workflow files were rearrange for consistency and the JenkinsRT file was reorganized for simplicity. 
[Jenkins test](https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FDrizzlepac-Developers-Pull-Requests/detail/Drizzlepac-Developers-Pull-Requests/111/pipeline/339/)
> HLA-1269 Testing with Python 3.12

- drizzlepac/hapmultisequencer.py
- drizzlepac/hapsequencer.py
- drizzlepac/mapreg.py
> fix SonarQube issues

- CHANGELOG.rst
- JenkinsfileRT
- drizzlepac/haputils/deconvolve_utils.py
- tests/hap/base_test.py
- tests/hap/test_pipeline.py
- tests/resources.py
- tox.ini
Closes #
Second Try to generate the Release Candidate 6 onto branch 3.7.1x for Drizzlepac.
> T2 newcandidate 371rc6

- CHANGELOG.rst
- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1295](https://jira.stsci.edu/browse/HLA-1295)
Closes #
HLA-1295: Fixed the computations associated with rejection of catalogs due to cosmic rays #1853 
> Newcandidate 371rc7

- CHANGELOG.rst
Resolves [HLA-1307](https://jira.stsci.edu/browse/HLA-1307)
Closes #
Final release of HSTDP-1307 by SCSB.
> HLA-1307: Commit of updated and final CHANGELOG to 3.7.1x

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
Implemented a bit of cleanup for Python code.
> This ticket is just a bit of tightening up of Python code.

- CHANGELOG.rst
This PR fixes the CHANGELOG file for date of last release, duplicate entry of a change, removes non-user oriented documented change, and inserts a missing PR number for change.
> Fix CHANGELOG 

- CHANGELOG.rst
- doc/source/mast_data_products.rst
- doc/source/mast_data_products/hap_tests.rst
Resolves [HLA-1327](https://jira.stsci.edu/browse/HLA-nnnn)
Closes #1880 
This PR adds new documentation describing the tests for the drizzlepac code. 
[Jenkins test](https://plwishmaster.stsci.edu:8081/job/RT/job/Drizzlepac-Developers-Pull-Requests/131/)
> HLA-1327: Added documentation describing the regression tests

- drizzlepac/haputils/cell_utils.py
The code is currently shrinking the boundary by one pixel. This code change will avoid that issue. The iterations for dilating and eroding the edges will now be the same. 
Several small changes were also contributed by @rlwastro.
> Small change to Rick's Quick Fix

- CHANGELOG.rst
- drizzlepac/haputils/cell_utils.py
- pyproject.toml
Cherry-picked: c3280cf, b37016d, f7fcc33, 20aef65, edcd223
> Newcandidate 3711

- doc/source/mast_data_products/svm_processing.rst
Resolves [HLA-1342](https://jira.stsci.edu/browse/HLA-1342)
This PR adds additional documentation describing the recent changes to the determination of the S_REGIONS. I've included animations/gifs created by @rlwastro and hosted on https://ssb.stsci.edu/alignment/. 
> HLA-1342: Documentation for S_REGION code change

- .github/workflows/ci_cron.yml
- drizzlepac/hapsequencer.py
Similar to PR [#1905](https://github.com/spacetelescope/drizzlepac/pull/1905) ([HLA-1361](https://jira.stsci.edu/browse/HLA-1361)) I am setting the devdeps tests to python 3.12, as dependency conflicts are resulting in failures.
> Set devdep github actions tests to python 3.12 (for cron)

- CHANGELOG.rst
- drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
Resolves [HLA-1385](https://jira.stsci.edu/browse/HLA-1385)
This PR addresses update the alignment parameters for SVM and pipeline products.
> HLA-1385 Configuration Parameter Updates for SVM and Pipeline Products. 

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
- CHANGELOG.rst
Resolves [SCSB-195](https://jira.stsci.edu/browse/SCSB-195)
> build and test with latest supported version of Python

- pyproject.toml
> pin Python for build testing

- doc/source/mast_data_products/catalog_generation.rst
Resolves [HLA-1465](https://jira.stsci.edu/browse/HLA-1465)
Closes #
Added considerable documentation provided by J. Mack to the photometry discussion of the source catalog products.
> HLA-1465: Added documentation photometry discussion of the source catalog products

- CHANGELOG.rst
- drizzlepac/haputils/astrometric_utils.py
- pyproject.toml
Incorporates PR#2014 into release branch.
> Merging PR for adding the parameter sub_shape to the IterativePSFPhotometry, circumventing the need to pin astropy

- tests/hap/test_svm_ci.py
Resolves [HLA-1505](https://jira.stsci.edu/browse/HLA-1505)
Closes #
Create a PyTest to evaluate the Concentration Index (CI) in a Point source catalog to ensure the value stays close to a nominal value. It has been observed that degradation in the results from the IterativePSFPhotometry function can manifest as increasing values of the CI.
> HLA-1505: Create PyTest to evaluate Concentration Index (CI) in a Point Catalog

- CHANGELOG.rst
Closes #
This PR just updates the date of release for Drizzlepac v3.10.0.
> Update CHANGELOG.rst for the date of release for v3.10.0

- requirements-dev.txt
This PR removes pyerfa-dev from devdeps. cc @braingram @zacharyburnett 
No need for change log.
> DEP: Remove pyerfa-dev
