spacetelescope/drizzlepac

- lib/drizzlepac/tweakreg.py
> Fix: TweakReg crashes when a single input image and a reference catalog are provided

- .gitignore
- lib/drizzlepac/tweakutils.py
- setup.cfg
Bonus: Introduces a `.gitignore` to help prevent accidental inclusion of generated files.
> Deprecate astrolib

- setup.cfg
Release removes `astrolib.coords` as a dependency
> Bump version 2.1.5 -> 2.1.6

- lib/drizzlepac/astrodrizzle.help
- lib/drizzlepac/createMedian.help
- lib/drizzlepac/createMedian.py
This PR fixes the issue described in https://github.com/spacetelescope/drizzlepac/issues/12 due to which sky background values are not converted to electrons from native units (as recorded in input image headers) leading to an underestimation of sigma that results in a more aggressive cosmic ray rejection, possibly flagging many good pixels as cosmic rays.
@stsci-hack
> Convert sky background from native input units to electrons for 'minmed' combine type

- lib/drizzlepac/wcs_functions.py
Due to change of the definition of ``rotateCD`` made in https://github.com/astropy/astropy/pull/5189 as well as its deprecation in https://github.com/astropy/astropy/pull/5240, it is necessary that our code has its own ``rotateCD`` that implements previous (to PR https://github.com/astropy/astropy/pull/5189) version of the code.
@stsci-hack @nden please review this PR
> Implement local rotateCD

- lib/drizzlepac/catalogs.py
- lib/drizzlepac/staticMask.py
The ``clobber`` parameter in ``astropy.io.fits`` write functions has been deprecated and it has been replaced with ``overwrite``: see https://github.com/astropy/astropy/pull/5171.
This has caused our code (see, e.g., ``drizzlepac`` - https://github.com/spacetelescope/drizzlepac/issues/15) to issue numerous deprecation warnings.
This PR updates the code in ``stsci.tools`` so that it uses ``overwrite`` for versions of astropy  >= 1.3 and ``clobber`` for verions < 1.3 (for backward compatibility).
This PR addresses issue described in https://github.com/spacetelescope/drizzlepac/issues/15
@stsci-hack Please review this PR.
> Fix deprecated 'clobber' parameter in astropy.io.fits write functions

- lib/drizzlepac/staticMask.py
This PR modifies code so that if there is an existing static mask in the working directory, this mask will be overwritten when code runs. This addresses the issue https://github.com/spacetelescope/drizzlepac/issues/23
> Allow existing static masks to be overwritten

- lib/drizzlepac/updatehdr.py
It seems that I have made a mistake in computation of inverse of a 2x2 matrix (likely due to copy/paste). The typo of ``[0.0]`` (instead of ``[0,0]``) had no effect due to the copy/paste bug. This PR may result in slightly different results in tweakreg though local tests indicate no change in the shifts/rotations obtained by tweakreg and no change in the found WCS parameters (CD matrix, CRVALs).
> fix incorrect 2x2 inverse matrix computation

- lib/drizzlepac/imageObject.py
Current code sets headers and data of HDUs in closed ``HDUList`` to ``None`` **after** the corresponding ``HDUList`` is closed. This causes deprecation warnings in ``drizzlepac`` - see https://github.com/spacetelescope/drizzlepac/issues/14
In this PR I create a dummy ``HDUList`` containing all the HDUs from the original image that replaces the original ``HDUList`` after the original file has been closed.
> Do not modify HDUs after file is closed

- lib/drizzlepac/wcs_functions.py
Currently (see https://github.com/spacetelescope/drizzlepac/issues/34) code attempts to delete original WCS and this results in multiple info messages warning about this. This PR modifies the code not to attempt to delete original WCS. This addresses the issue https://github.com/spacetelescope/drizzlepac/issues/34
> Do not attempt to delete original WCS

- lib/drizzlepac/acsData.py
- lib/drizzlepac/minmed.py
- lib/drizzlepac/stisData.py
This PR solves the issue of negative values under square root that produce warnings reported in https://github.com/spacetelescope/drizzlepac/issues/22. Fundamentally, the code now will set to zero any negative data values before computing Poisson noise.
This PR also removed unnecessary double underscores from variable names + removes extra new lines reported in https://github.com/spacetelescope/stsci.tools/issues/22#issuecomment-277808856
> Zero negative values before computing image's Poisson errors

- lib/drizzlepac/pars/imagefindpars.cfgspc
@stsci-hack This will fix currently disabled (and failing when enabled) ``drizzlepac``'s ``ui/cfg_files`` tests.
@jhunkeler Please enable ``drizzlepac``'s ``ui/cfg_files`` tests.
> Set default 'dqbits' value in imagefindpars.cfgspc to empty string

- lib/drizzlepac/stisData.py
Multiple bugs are affecting the ``getflat()`` method of the ``STISInputImage`` class preventing processing of STIS imaging data.
> Fix multiple bugs in 'getflat' method of 'STISInputImage'

- lib/drizzlepac/processInput.py
- setup.cfg
Depending on input files, ``AstroDrizzle`` needs to create new input files and use them instead of the original input files, e.g., replace ``_c0f.fits`` files with ``_c0h.fits`` files or extract single exposures from "multi-imset STIS ``_flt`` files".
This PR updates ``buildFileListOrig()`` function to run ``stwcs.updatewcs.updatewcs()`` on these new images when so requested.
> Run updatewcs on newly unpacked/created files if requested

- lib/drizzlepac/wfc3Data.py
- lib/drizzlepac/wfpc2Data.py
A long time ago some fellows used to overwrite Python's built-in ``str`` type with string values. This was causing problems in ``drizzlepac`` (see, e.g., https://github.com/spacetelescope/drizzlepac/pull/55). This PR renames ``str`` **variable** to something else to avoid possible conflicts.
> Don't overwrite (or assign string values to the) built-in 'str' type

- lib/drizzlepac/ablot.py
- lib/drizzlepac/adrizzle.py
- lib/drizzlepac/imageObject.py
- lib/drizzlepac/sky.py
As reported in https://github.com/spacetelescope/drizzlepac/issues/58, ``skysub`` option in ``AstroDrizzle`` is broken and setting ``skysub`` to ``False`` does not turn off subtraction of ``MDRIZSKY`` values read from image headers during initialization of ``AstroDrizzle``.
Initially, the capability of turning off sky subtraction was introduced in https://trac.stsci.edu/ssb/stsci_python/ticket/1208 but, unfortunately, it works *only when ``MDRIZSKY`` is not present in image headers.*
This PR fixes the logic for turning off sky subtraction.
> Fix logic for turning off sky subtraction

- lib/drizzlepac/ablot.py
- lib/drizzlepac/outputimage.py
- lib/drizzlepac/wcs_functions.py
This supresses log.INFO messages comping from astropy.wcs in cases which I believe are benign and are safe to ignore. My local testing shows it produces a clean log as desired by some.
> Suppress info messages

- lib/drizzlepac/ablot.py
- lib/drizzlepac/adrizzle.py
- lib/drizzlepac/buildmask.py
- lib/drizzlepac/catalogs.py
- lib/drizzlepac/createMedian.py
- lib/drizzlepac/drizCR.py
- lib/drizzlepac/imageObject.py
- lib/drizzlepac/imgclasses.py
- lib/drizzlepac/irData.py
- lib/drizzlepac/mapreg.py
- lib/drizzlepac/mdzhandler.py
- lib/drizzlepac/nicmosData.py
- lib/drizzlepac/pixreplace.py
- lib/drizzlepac/processInput.py
- lib/drizzlepac/resetbits.py
- lib/drizzlepac/runastrodriz.py
- lib/drizzlepac/sky.py
- lib/drizzlepac/skytopix.py
- lib/drizzlepac/stisData.py
- lib/drizzlepac/tweakback.py
- lib/drizzlepac/tweakutils.py
- lib/drizzlepac/updatehdr.py
- lib/drizzlepac/updatenpol.py
- lib/drizzlepac/util.py
- lib/drizzlepac/wcs_functions.py
- lib/drizzlepac/wfc3Data.py
- lib/drizzlepac/wfpc2Data.py
This PR explicitly turns off memory mapping in fits IO functions. This is done in order to reduce the number of file handles used by ``astrodrizzle``. This PR partially addresses issue https://github.com/spacetelescope/drizzlepac/issues/39.
> Explicitly set memory mapping to False

- lib/drizzlepac/tweakreg.help
Documentation did not explicitly specify that catalog files be white space separated.
> Document that reference catalogs are white-space-separated

- .gitignore
- doc/source/release_notes.rst
- lib/drizzlepac/imageObject.py
This PR should address the problem of ``drizzlepac`` lowering the case of the path of output products - see https://github.com/spacetelescope/drizzlepac/issues/79 for more details.
> Fix drizzlepac lowering the case of paths of output products

- doc/source/release_notes.rst
- lib/drizzlepac/catalogs.py
- lib/drizzlepac/tweakreg.help
- lib/drizzlepac/tweakreg.py
- setup.cfg
TweakReg is ignoring units of user-provided catalogs. Specifically, user-provided catalogs are assumed to be in "pixels" **regardless** of the value of the ``xyunits`` parameters.
This PR adds support for image catalogs with coordinates in degrees.
This bug was first reported by Will Waldron (UAH) who also proposed a solution partially implemented in this PR.
This PR addresses issue https://github.com/spacetelescope/drizzlepac/issues/81
> Add support for user-provided image catalogs in degrees

- doc/source/release_notes.rst
- lib/drizzlepac/tweakreg.py
This bug was reported by Jennifer Mack. When running ``tweakreg`` with ``expand_refcat=True``, the code may crash when trying to ``pop`` an image from a list using a float index. This bug was introduced in [changeset r40216](https://trac.stsci.edu/ssb/stsci_python/changeset/40216/drizzlepac/trunk/lib/drizzlepac/tweakreg.py). The critical change was:
```python
from __future__ import division
```
which resulted integer divisions producing floating point numbers. This resulted in the code crashing at a later point.
This PR modifies the code so that integer division will produce integer results in both Python 2 and 3.
CC: @stsci-hack @bernie-simon
> Make sure integer division stays integer div in Python 3

- doc/source/release_notes.rst
- lib/drizzlepac/catalogs.py
- lib/drizzlepac/imgclasses.py
- lib/drizzlepac/tweakreg.help
- lib/drizzlepac/tweakreg.py
- lib/drizzlepac/tweakutils.py
- setup.cfg
This PR addresses several issues in tweakreg stemming from issues reported by Jennifer Mack as described in https://github.com/spacetelescope/drizzlepac/pull/86 and https://github.com/spacetelescope/drizzlepac/issues/87. When researching the code to fix https://github.com/spacetelescope/drizzlepac/issues/87, additional issues have been uncovered as described in https://github.com/spacetelescope/drizzlepac/issues/88 and https://github.com/spacetelescope/drizzlepac/issues/89. 
This PR fixes issues https://github.com/spacetelescope/drizzlepac/issues/87, https://github.com/spacetelescope/drizzlepac/issues/88, and https://github.com/spacetelescope/drizzlepac/issues/89.
In addition, the following code enhancements have been implemented:
1. when `radec` is filtered out, `xypos` member of the …
> Fix catalog source doubling and catalog filtering

- doc/source/release_notes.rst
- lib/drizzlepac/createMedian.py
This PR should address the issue of unit conversion for either `combine_lthresh` or `combine_hthresh` parameters from the `CREATE MEDIAN IMAGE` step - see https://github.com/spacetelescope/drizzlepac/issues/94 for more details.
> Fix unit conversion for combine thresholds

- doc/source/release_notes.rst
- lib/drizzlepac/imgclasses.py
Modified print format so that scales, skew and rotations are printed with 10 significant digits while shifts are printed with 4 digits after the decimal point. Also now RMS values are reported with only two significant digits.
This PR addresses Vera Platais' desire to have more digits in scale & skew as described in https://github.com/spacetelescope/drizzlepac/issues/97. I chose to output 10 significant digits.
> Increase number of significant digits in scales and rot

- doc/source/release_notes.rst
- lib/drizzlepac/outputimage.py
- setup.cfg
This PR undoes changes from  [this github adaptation](https://github.com/spacetelescope/drizzlepac/commit/fa70e27c77c5c9d1224bb15d26268ca5433af1e9#diff-1ec325ef04e8462150c016437086037cR137) due to which `EXPTIME` was set to 1 in "single sci" image headers. Without correct `EXPTIME` it is impossible to convert single sci images from rates to counts. This PR addresses issue https://github.com/spacetelescope/drizzlepac/issues/93
> Undo changes that make exptime set to 1 in single sci images

- setup.cfg
Add `stsci.skypac` as dependency of `drizzlepac` - see https://github.com/spacetelescope/drizzlepac/issues/105
> Add skypac as dependency of drizzlepac

- doc/source/release_notes.rst
- lib/drizzlepac/createMedian.help
- lib/drizzlepac/createMedian.py
This PR fixes issues https://github.com/spacetelescope/drizzlepac/issues/102 and https://github.com/spacetelescope/drizzlepac/issues/103 by providing a completely redesigned algorithm for splitting `single_sci` images into smaller chunks according to user-specified buffer size. The new algorithm is much more simple than previous algorithm and does not depend  `stsci.tools.nimageiter` module anymore [which should be removed from `stsci.tools`].
I run several tests on Jennifer Mack's data and also on some other (WFPC2) data with varying settings for buffer size and overlap size and everything seems to work as expected.
> Fix sectioning algorithm in Create Median step

- lib/drizzlepac/createMedian.py
- lib/drizzlepac/minmed.py
Update `minmed` code and deprecate old one and switch `createMedian()` to use new `min_med()` and `num_combine()` functions.
This should fix failing `drizzlepac` tests after https://github.com/spacetelescope/drizzlepac/pull/104
> Update minmed code

- lib/drizzlepac/minmed.py
Fixes a small mistake in updated 'minmed' code with large consequences for the create median step. This resulted in multiple regression tests failing.
With fixed code, there are still small differences in some tests (~400 pixels). So, I still expect drizzlepac tests to fail but I may OKify them if the number of differences is small.
> Fix a bug in computation of readnoise_file in minmed

- lib/drizzlepac/astrodrizzle.py
- lib/drizzlepac/tweakreg.py
This PR adresses https://github.com/spacetelescope/drizzlepac/issues/111 by identifying when `configobj` is set to `'defaults'` and then it loads the defaults from the `drizzlepac`'s own `pars` directory instead of user's local `~/.teal/`.
> Make astrodrizzle and tweakreg load defaults from package instead of user's local .teal

- doc/source/release_notes.rst
- lib/drizzlepac/tweakreg.help
Added notes to "release notes" about `configobj` and also updated docstring for `TweakReg` with these changes - see https://github.com/spacetelescope/drizzlepac/pull/112
> Update documentation about configobj and defaults

- setup.py
Fixes the following:
```cmd
C:\Users\jhunk\Miniconda3\envs\driz\lib\site-packages\astropy\wcs\include\wcslib\wcs.h(1743): error C2373: 'wcsset': redefinition; different type modifiers
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\corecrt_wstring.h(620): note: see declaration of 'wcsset'
```
> Fix Windows build failure

- drizzlepac/tweakreg.py
Bug introduced by #116 ::
```python
Traceback (most recent call last):
File "/Users/shared/iraf_conda/bldtmp/pr7S/p/envs/dev/lib/python3.5/site-packages/drizzlepac/util.py", line 218, in wrapper
func(*args, **kwargs)
File "/Users/shared/iraf_conda/bldtmp/pr7S/p/envs/dev/lib/python3.5/site-packages/drizzlepac/tweakreg.py", line 103, in run
__version__,__version_date__,util._ptime()[0]))
NameError: name '__version_date__' is not defined
```
This PR replaces `__vdate__` with `__version_date__`.
> Replace final __vdate__ reference

- setup.py
I forgot about poor old 2.7 while working on the sphinx documentation.
> Allows python2.7 to build; Fixup PEP8

- doc/source/release_notes.rst
- drizzlepac/processInput.py
- drizzlepac/runastrodriz.py
- drizzlepac/wfpc2Data.py
These fixes were needed in order to allow WFPC2 data from the archive to be processed again.
> Fixes to let WFPC2 data process

- doc/source/release_notes.rst
- drizzlepac/tweakreg.py
In https://github.com/spacetelescope/drizzlepac/commit/77fbde16c6de551fb7bbc3b29fa80d78a1e2a8e7#diff-fa6016220e25e86c26d2ae334eb367a2R780 I made a mistake of copy/paste a fix from `astrodrizzle.py` to `tweakreg.py`. However, I missed the fact that input files are provided through the `files` argument in `TweakReg` vs. `input` (yes, same as the built-in method) in `AstroDrizzle` and so I failed to update the fix to work for `TweakReg`. This in effect, introduced a bug in `TweakReg` v.1.4.6. This PR fixes this bug.
> Fix input file bug in TweakReg

- setup.py
CC: @jhunkeler 
In Python 2.7 (my env after updating it) `stsci.image` was `2.2.0` but `drizzlepac` requires `2.3.0`.
> Update setup version requirement for stsci.image

- doc/source/conf.py
- setup.py
- Sphinx
- `conf.py` adds the `.eggs` directory populated by `setup_requires`. This is useful if compiling the docs outside of Conda.
- Setuptools
- Implement `BuildSphinx`  wrapper ripped straight from `stsci-jwst/jwst.git`. The overall logic was modified slightly to prevent a chicken/egg scenario when Sphinx wasn't available. (see the `CMDCLASS` dictionary)
- Implement `InstallCommand` wrapper to ensure C extensions are compiled/available on `sys.path` when importing `drizzlepac` from a path relative to the project. (RTD support)
- Does not touch `develop` since that build mode already performs `build_ext --inplace` by design
- Does not change behavior of `cd doc/source && make html`. Doing this manually still might not work unless you have the correct dependencies pre-installed, either …
> Sphinx brain

- drizzlepac/mdriz.py
Given the state of this module and what it refers to... can it be deprecated?
This is only being fixed so that my import tests will succeed.
https://ssbjenkins.stsci.edu/blue/organizations/jenkins/STScI%2Fdrizzlepac/detail/PR-132/11/pipeline
> mdriz: Fix broken imports

- CHANGELOG.rst
- drizzlepac/createMedian.py
This PR fixes a bug introduced in https://github.com/spacetelescope/drizzlepac/pull/104/files#diff-a8dcc868b4ea304820717b4986c3ae0aR292
> Create median does not print image background value

- drizzlepac/astrodrizzle.py
- drizzlepac/imgclasses.py
- drizzlepac/tweakreg.py
- drizzlepac/util.py
Improve visual appearance of the drizzlepac's log (i.e., spacing between blocks). Output complete `configObj` in `astrodrizzle` and `tweakreg` when `verbose` is `True`.
> Improve visual of the drizzlepac logs. Log full configobj

- CHANGELOG.rst
- drizzlepac/ablot.py
- drizzlepac/adrizzle.py
- drizzlepac/astrodrizzle.py
- drizzlepac/catalogs.py
- drizzlepac/createMedian.py
- drizzlepac/drizCR.py
- drizzlepac/imageObject.py
- drizzlepac/imgclasses.py
- drizzlepac/linearfit.py
- drizzlepac/outputimage.py
- drizzlepac/processInput.py
- drizzlepac/resetbits.py
- drizzlepac/sky.py
- drizzlepac/staticMask.py
- drizzlepac/tweakback.py
- drizzlepac/tweakreg.py
- drizzlepac/tweakutils.py
- drizzlepac/updatehdr.py
- drizzlepac/util.py
- drizzlepac/wcs_functions.py
This PR should address issue https://github.com/spacetelescope/drizzlepac/issues/146. While suspicion that `wcs_functions.py` may not be restoring previous logging level might still be true, now I think the main reason for the observed behavior lies in the call to `log = logutil.create_logger(__name__)` at the top of most modules in the `astrodrizzle`. By default the logger created with `create_logger()` have log level set to `INFO` and so all module-leve loggers are set to ignore `DEBUG`-level messages. This PR creates module-level loggers with `level` se to `NOTSET` and thus effectively using root logger's level which is set in `astrodrizzle.util.WithLogging`.
> Allow use of DEBUG logging level in drizzlepac

- CHANGELOG.rst
- drizzlepac/util.py
This PR implements the fix proposed by @griffin-h in #157.
> Fix undefined errorobj in with_logging

- Jenkinsfile
The CI utilities library that Jenkins uses to provide the convenience syntax used in the Jenkinsfile has been updated to temporarily honor both .build_mode and .name as a step towards transitioning to the new property .name for clarity. Once all projects using the CI utilities are updated, support for the old .build_mode name will be removed.
> Change 'build_mode' to 'name' to reflect utils update.

- setup.cfg
I'm baaaack!
http://www.sphinx-doc.org/en/master/setuptools.html
> TST: Turn Sphinx warning into error

- CHANGELOG.rst
I'm not a fortune teller, so I'm setting the next version to `DEVELOPMENT`. 
Replace the current `DEVELOPMENT` header with the next version and date whenever there is one :)
> Prepare 2.2.5

- CHANGELOG.rst
- drizzlepac/photeq.py
This should fix `numpy` "floating" deprecation warnings described in https://github.com/spacetelescope/drizzlepac/issues/175
> Fix numpy floating deprecation warnings in photeq

- tests/helpers/mark.py
Drizzlepac does not run on Travis anymore as I don't see any `.travis.yml` file in the repo. Having this around is unnecessary?
> Remove unused marker

- Jenkinsfile
- JenkinsfileRT
This builds and tests `drizzlepac` in an environment consisting of all stable packages except for
* `astropy`
* `stwcs`
which are taken from the latest master snapshot provided by astroconda-dev.
For now, this will be run in a special purpose Jenkins job on the RT Jenkins instance.
> Add JenkinsfileRT for use in testing against new astropy.

- Jenkinsfile
Clean up Jenkinsfile to remove unused constructs, standardize dependency sources, and leverage CI utilities library.
> Update Jenkinsfile to rely on ci utils library.

- CHANGELOG.rst
- drizzlepac/drizCR.py
This PR should fix incorrect units in CR-cleaned images created by ``astrodrizzle`` - see #189. Now CR-cleaned images should have the same units as input images.
> Fix incorrect units in CR-cleaned images

- drizzlepac/drizCR.help
- drizzlepac/drizCR.py
- drizzlepac/minmed.py
- setup.py
This PR cleans up core `drizCR.py` code (used for cosmic ray cleaning). In addition, it replaces calls to `stsci.convolve` with calls to `scipy.signal.convolve2d`. In light of this, @pllim , maybe https://github.com/spacetelescope/stsci.convolve/issues/1 is doable assuming no other STScI package  depends on `stsci.convolve`.
> Cleanup CR-cleaning code and remove dependency on stsci.convolve

- drizzlepac/drizCR.py
This corrects problems identified in the regression test 'acs/test_acs_tweak.py' with performing the drizCR step using 'in_memory=True'.  The changes were confirmed to correct the problem with this specific test.
> Changes to fix in-memory use in drizCR

- JenkinsfileRT
and use relative path to invoke `conda` for installation of special-case development packages to prevent the erroneous use of the python interpreter in the base conda environment for execution of applicable `build_cmds` & `test_cmds`, rather than the interpreter provided in the custom environment created for hosting the build.
> Remove unnecessary PATH, HOME overrides

- CHANGELOG.rst
- drizzlepac/runastrodriz.py
These changes allow alignimages to be called from 'runastrodriz' so that the pipeline can align the images.  This initially expects alignimages to be in the HLAPipeline package. 
This requires [hlapipelne PR 72](https://github.com/spacetelescope/hlapipeline/pull/72) in order to work correctly.
> Initial version which calls alignimages

- drizzlepac/alignimages.py
- drizzlepac/runastrodriz.py
The interface to perform_align() could not return any values when wrapped by the util.with_logging decorator.  However, the pipeline relies on the returned table to determine what to do next.  This set of changes restores the interface so that perform_align( ) once again returns the filteredTable.
> Restore API for perform_align function

- CHANGELOG.rst
- drizzlepac/alignimages.py
Logic in alignimages allowed any solution with rms > 0 to be used to update the headers.  However, a default value of 1e+9 mas is used to flag fits which never get performed causing this logic to try to update the headers with invalid/non-existent fits.  
This simply change takes this into account when performing the check for running STEP 7.
> Fix step7 logic

- CHANGELOG.rst
- drizzlepac/alignimages.py
This restores logic originally implemented to flag failed fits with a fitQual=5.  Failed fits were most often due to 'too many coordinates' (i.e., more than 1 source from the image matched to a single GAIA source) which would eventually throw an Exception about 'align_table' not being found.  
Testing by DSB for HSTDP 2019.2 reported such Exceptions for a number of cases, which I was able to reproduce, then resolve with these changes.
> Debug align table

- drizzlepac/alignimages.py
All changes were limited to the perform_align() subroutine call on line 1113 of alignimages.py.
The subroutine call had 2 issues that prevented alignimages.py from being successfully executed from the command line: 
1) The master version subroutine inputs were not formatted correctly.
2) The master version subroutine call was missing the final required input parameter "output".
> Bugfix: Correct perform_align() subroutine call in alignimages.py

- CHANGELOG.rst
- drizzlepac/alignimages.py
Evaluation of test results generated in testing HSTDP 2019.2 indicated that the new a posteriori solutions were NOT getting appended as HDRLET extensions to the original FLC files, where they were being attached to the FLT files.  
So, in order to keep the FLC and FLT files consistent with the same set of WCS solutions, this change explicitly attaches the newly created solution as a HDRLET extension to the image used to compute the solution (typically, the FLC file).
> Add archive hdrlet

- CHANGELOG.rst
- drizzlepac/alignimages.py
Pipeline testing of HSTDP 2019.2 encountered errors which were triggered when alignimages tried to import astroquery.mast.  It is unclear why the pipeline would encounter this problem, and it is not something that has been reproduced locally.  A discussion with Clara (astroquery developer) did not provide any obvious reason for this behavior either.  
Therefore, these changes are being submitted in an attempt to make the use of astroquery effectively optional, with the code simply falling back to relying on what is already in the current directory in case of any problems with using astroquery.  
This PR should not be merged until the problem can be reproduced locally, or at least these changes are confirmed to actually work as intended when problems are forcibly created while also …
> Astroquery import error

- CHANGELOG.rst
- drizzlepac/runastrodriz.py
This updates the `runastrodriz.py` wrapper to make sure that it does NOT overwrite any headerlet file already written out (with much more information) by alignimages (or any other code used).  This will insure that the ancillary information about the fit for each image gets retained in the hlet.fits files and archived properly.
> Update runastrodriz to NOT overwrite hlet file

- CHANGELOG.rst
- drizzlepac/runastrodriz.py
Control over operation of the a posteriori alignment has been added to 'runastrodriz' through use of a new environment variable as well as a new command-line switch.  This will allow the pipeline to turn this capability on/off at will without a new software delivery.
> Implement envvar control of alignment in runastrodriz

- Jenkinsfile
- pyproject.toml
- setup.py
Latest `setuptools` produces the following error during build:
```        
from setuptools import setup, find_packages, Extension, _install_setup_requires
ImportError: cannot import name '_install_setup_requires'
```
This implements `pyproject.toml` (PEP517) as a replacement.
> Fix setuptools

- JenkinsfileRT
RT job partially failing due to not compiling C extensions in-place
> JenkinsfileRT: Use pip arguments that fit context

- CHANGELOG.rst
- drizzlepac/alignimages.py
Update the interpret_fix_rms to be more robust in handling output from tweakwcs, in particular, when the relative alignment algorithm is used.  This update does not depend upon inclusion of the new relative alignment algorithm.
> Fixed interpret_fit_rms to handle relative alignments.

- JenkinsfileRT
Missed by #285 
Should fix failing `no argument: --bigdata`
> JenkinsfileRT: Add ci-watson

- tests/resources.py
- tests/wfpc2/test_wfpc2.py
Added `DGEOFILE` to list passed to `ref_from_image`.
Thanks @stsci-hack
> Fix failing WFPC2 tests

- CHANGELOG.rst
- drizzlepac/alignimages.py
Singletons cannot use the match_relative_fit algorithm because the algorithm requires at least two images - one which servers as the reference and the remaining image(s) are aligned to the reference.
> Ensure singletons do not use the match_relative_fit algorithm

- drizzlepac/alignimages.py
This PR addresses two items raised in #283 : Namely [this one](https://github.com/spacetelescope/drizzlepac/pull/283#discussion_r268901463), and [this one](https://github.com/spacetelescope/drizzlepac/pull/283#discussion_r268903028).
- rolled string to boolean conversion into add_argument() statements that expect "True"/"False" inputs. This eliminates the need for a second line to a call a string to boolean conversion subroutine for each argument expecting a "True"/"False" input.
- converted all upper-case and camelcase variable names to lowercase in the command-line interface section of alignimages.py
-  made some minor logic tweaks to the code that builds input_list in the command-line interface section of alignimages.py
> Streamline command-line interface section of alignimages.py

- CHANGELOG.rst
- drizzlepac/alignimages.py
- drizzlepac/hlautils/analyze.py
- tests/hla/base_classes.py
- tests/hla/base_test.py
- tests/hla/test_align.py
- tests/hla/test_randomlist.py
Added the regression tests for the alignment code to the drizzlepac package.  Modified the alignment tests to use the updated output (astropy table) from the alignment code (alignimages.py/perform_align()) to determine the processing state.  Currently, the output states are: Successful, Unsuccessful, Filtered, and Exception.  These tests were written to satisfy the criterion of 0 < total_RMS < 10 mas, so they are not true regression tests.  One routine, test_extract.py, has not been updated pending information needed from the originator of the test.
An update was required in the alignment code itself to accommodate these tests to (1) resolve issues where full filenames (e.g., *_flt.fits) are used for files which are part of associations, but they are to be used as singletons so they …
> Mods to add/update regression tests for alignment code

- conftest.py
- tests/hla/process_randomlist.py
- tests/hla/test_randomlist.py
In order to run this pytest on a large number of random datasets, the nature of the _random_select_from_csv() routine has been altered at this time to work on the input table in a sequential fashion.  In this case, the input list is actually already randomized.
> Changed the nature of _random_select_from_csv() at this time.

- drizzlepac/alignimages.py
Bug fix introduced when cleaning up for PEP8.  An "==" was incorrectly changed to "is".
> Bug fix - equality check versus same object

- drizzlepac/hlautils/get_git_rev_info.py
- See ticket [HLA-233](https://jira.stsci.edu/browse/HLA-233)
- replaced 'os.system()' calls with 'os.popen()' calls, added for loops to properly parse out information os.popen() calls into log.info() calls.
- added more transparent exception handling
- minor cosmetic improvements.
> Add alignimages.py git repo information to log file

- drizzlepac/alignimages.py
- JIRA ticket [HLA-228](https://jira.stsci.edu/browse/HLA-228)
Switched order of processing loops so the code now loops over fit method, then astrometric catalog, rather then astrometric catalog, then fit method as it previously did. This will ensure that the code will always try match_relative_fit with both possible astrometric catalogs before anything else.
> change processing order so that match_relative_fit is the preferred fit method

- setup.cfg
`results.xml` is invalid and cannot be parsed by `xunit2`.
> junit_xml is not a valid keyword

- tests/hla/test_apriori.py
This code will address the problems with the a priori tests in the nightly regression tests.  These changes are based on the new version of this test developed on the hla-staging branch.
> Fix apriori tests on master

- tests/wfpc2/test_wfpc2.py
This disables WFPC2 waiver file format tests until the truth files can be updated in regression tests. See https://github.com/spacetelescope/drizzlepac/issues/338
> Disable WFPC2 waiver tests

- CHANGELOG.rst
- drizzlepac/util.py
This should fix the issue described in https://github.com/spacetelescope/drizzlepac/pull/360#issuecomment-489739047. Specifically, it appears that `util.WithLogging` was designed for the original `astrodrizzle` and `tweakreg`' `run()` functions that do not return values. As designed, `util.WithLogging` cannot handle the case of functions returning values as used in https://github.com/spacetelescope/drizzlepac/pull/360/files#diff-7e71c64f2a6349beb1e22b3761bb8e81R192
This PR expands `util.WithLogging` to make the decorated function return the original function return value.
> Make WithLogging decorator handle functions that return values

- CHANGELOG.rst
- drizzlepac/util.py
This PR fixes a bug in `util.WithLogging` due to which the name of the log file reported by the decorator is incorrect when the log file name set by user does not have the `.log` extension.
This also fixes a bug introduced in #364 (`return` in `finally`) reported by @pllim .
> Fix incorrect log file name reported by WithLogging and return in finally

- drizzlepac/alignimages.py
- drizzlepac/hlautils/astroquery_utils.py
Testing under HSTDP 2019.3a uncovered problems with using astroquery in parallel.  These changes recognize that specific exception case and silently trap it while setting up to warn the user if it ever happens interactively. 
The testing of this change also uncovered a limitation in the interpretation of the ASN files; namely, it only looked for _flc.fits files as members.  However, for WFC3/IR data, associations will only ever have _flt.fits files as members, something the original code did not recognize.  This code looks to see what type of file is present if no suffix is specified in the ASN file itself, and set the suffix to be that value.
> handle astroquery import error and improve ASN interpretation

- drizzlepac/alignimages.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/runastrodriz.py
- setup.py
Some datasets result in the relative alignment between exposures being disrupted due to fits based on inaccurate source positions or other reasons.  These changes recognize when a fit has inconsistent RMS values for RA and DEC and flags that fit as invalid.  Other updates include:
- PEP8 updates for runastrodriz.
- Explicitly forcing 'clobber=False' in runastrodriz to avoid any potential for problems with astroquery
- updating the install requirements to include scikit-image to avoid numpy errors when running the alignment code with deblending turned on.
- Ignoring all sources in a segment if no identified source corresponds to the peak of the source.
These correct issues found during testing of HSTDP 2019.3a.
> Trap and avoid source identification problems

- drizzlepac/hlautils/astrometric_utils.py
This PR makes a few changes to allow the HLA astrometric code to work with `photutils 0.6` (latest stable release).  Once `drizzlepac` changes its minimal dependency to `photutils >= 0.7` some of this code can be removed.
> Allow HLA astrometric code to work with photutils 0.6

- drizzlepac/alignimages.py
This set of changes fixes a problem identified in the original code where the 'best fit' WCS is NOT being used to update the science data, where instead the last solution was being used.  This fix also removes the check for the ratio of the rms_RA and rms_DEC, since it is no longer needed with this fixing the underlying problem.  
The fix was to eliminate the use of 'best_meta' and replace it with a full copy of the 'best' imglist.
This needs to be included immediately in the pending, being tested, release.
> CRITICAL FIX for WCS update with best solution

- drizzlepac/hlautils/processing_utils.py
- drizzlepac/pars/acs_header_hla.rules
- drizzlepac/pars/wfc3_header_hla.rules
These new functions support the operation of updating the output product headers with values required for ingest into CAOM, along with any other defined values for the Hubble Advanced Pipeline products.
It specifically implements all the keyword definitions specified on the "New HLA Products" confluence page.  
It also includes the new default FITSBLENDER rules files for use with AstroDrizzle to generate the basic headers directly with as many CAOM-required keywords pre-defined as possible.
> Initial version of header update code

- drizzlepac/outputimage.py
This simple change insures that the WCSNAME header keyword gets populated based on the input WCSNAME values.  It also works in concert with [FITSBLENDER PR 25](https://github.com/spacetelescope/fitsblender/pull/25) to add WCSNAME to the HDRTAB extension of the drz products and has the WCSNAME keyword in the SCI header.
> Stop overwriting WCSNAME in drz products

- CHANGELOG.rst
- drizzlepac/tweakutils.py
Fixes a compatibility issue with Python 3 when using `drizzlepac.skytopix.rd2xy` with world coordinates in `hms` format. Reported in helpdesk.
> Make skytopix work in Python 3

- drizzlepac/alignimages.py
Any fit which is based on only 3 matched sources will always come out with an RMS very near zero, yet it may not be correct (due to cross-matching) or the most reliable compared to another fit with many times more matched sources and a still valid RMS.  So, this simple change will instead treat those solutions as completely invalid, until more refined logic can be determined to deal with the situations where another solution has a significant number of matches.
> Treat too few sources in match as invalid

- drizzlepac/alignimages.py
- drizzlepac/hlautils/processing_utils.py
- drizzlepac/pars/acs_header_hla.rules
- drizzlepac/pars/wfc3_header_hla.rules
- drizzlepac/updatehdr.py
Generating the sample datasets for pipeline testing revealed a number of problems with the headers and HDRTAB which prevented them from being ingested into the archive.  
(Most of?) These problems were addressed in this new version of `refine_product_headers`.
> Update headers to meet CAOM/Archive reqs

- drizzlepac/outputimage.py
- drizzlepac/updatehdr.py
The WCSTYPE keyword was added to the HDRTAB table in #390, however, additional changes needed to be made to get the keyword added to the DRZ/DRC product science headers.
> Include wsctype in drz product headers

- drizzlepac/hlautils/processing_utils.py
The value of HAPEXPNAME in the HDRTAB for the total product needs to point to the original files that were used to generate the total product; namely, the exposure level files. This comes as a request from CAOM to insure that the correct data gets presented to the archive users.
> Revise HAPEXPNAME for level 2 products

- drizzlepac/pars/acs_header_hla.rules
This change insures that all HAP products include the PA_V3 keyword in the header of the products.
> Add PA_V3 to ACS HAP rules to insure consistency for HAP products

- drizzlepac/hlautils/processing_utils.py
- drizzlepac/pars/acs_header_hla.rules
These changes move keywords around to insure they are always in the same extension regardless of instrument or detector.  This includes updating the rules to make sure a couple of keywords are kept in the product header that were originally missing (for ACS, that is).  
The HAPEXPNAME value was also updated to report the 'exposure name' instead of the full filename, upon request of the archive and CAOM.
> Move keywords in HAP products to be consistent

- CHANGELOG.rst
- drizzlepac/pixtopix.help
- drizzlepac/pixtopix.py
- drizzlepac/pixtosky.help
- drizzlepac/util.py
This PR fixes the behavior of `verbose` parameter to actually work as expected when `pixtopix` is not run as a script. In addition it also removes the `coords` parameter that has been deprecated for years. It is time to remove it.
> Enforce pixtopix verbose setting when not run as a script

- setup.py
This change automatically installs a command-line interface to 'runhlaprocessing.main()' in the same manner as done for 'runastrodriz'.  The interface is required for pipeline use.
> Adding cmd line interface to runhlaprocessing

- drizzlepac/runhlaprocessing.py
The code originally looked for all DRC files to update with the CAOM columns necessary for linking the products with the inputs.  This resulted in real problems under a couple of different processing scenarios: inputs were FLT files and generated DRZ not DRC files and (as noted pipeline use by Lisa S. during testing) there may be DRC files in the current directory which are not part of this visit. 
The changes here keep track of only those products generated during the processing of the input visit (or set of exposures) and only update those specific drizzle products.  This should make the code compatible with pipeline processing or any other processing where multiple datasets are located in the same current working directory regardless of the suffix used for the products (DRZ vs DRC).
> Update real product headers for CAOM compatibility

- tests/resources.py
With the introduction of `pytest 5.0.0`, use of `pytest.config` is no longer possible as it has been deprecated since `4.1`.
This PR changes to a different means of obtaining user-specified config values taken from either `setup.cfg` or `pytest.ini`. 
General approach taken from https://github.com/spacetelescope/jwst/pull/3200 where this has been demonstrated prior.
> Get user-defined pytest config values through non-deprecated means.

- drizzlepac/wcs_functions.py
Simple change to make this function used by single_visit HAP code to exactly replicate the CD matrix computed when AstroDrizzle is run.
> Update make_mosaic_wcs to produce a perfect CD matrix

- drizzlepac/hlautils/astroquery_utils.py
- drizzlepac/runastrodriz.py
- requirements-dev.txt
- setup.py
- tests/hla/test_pipeline.py
Pipeline testing under HSTDP 2019.3b uncovered problems with how singleton observations which are CTE-corrected are processed that resulted in FLC and FLT versions of the calibrated data having different WCSs.  
The base cause for this came down to how runastrodriz tried to include the FLC file for processing for singletons, then subsequently added another list that also included the FLC filename for additional processing.  Combined with STWCS v1.5.1, this resulted in the FLC file WCS getting reset by stwcs.updatewcs while the FLT image did not.  
The changes here will resolve this (long-standing hidden) problem with runastrodriz, while also adding a fast, simple regression test to insure it is fixed and that it stays fixed.
> Correct singleton CTE processing in runastrodriz

- drizzlepac/updatehdr.py
- tests/hla/test_apriori.py
Running 'tweakreg' or resetting WCSNAME by any other means to values other than those starting with 'OPUS' or 'IDC' caused 'tweakreg' and subsequent runs of 'astrodrizzle' to fail.  This was caught in our nightly regression tests https://plwishmaster.stsci.edu:8081/job/RT/job/drizzlepac/313/testReport/tests.acs.test_acs_tweak/TestAcsTweak/_3_6__test_tweak/
This failure showed up as: 
```
>      wcstype += base_terms[wcsname_list[0][:3]]
E       KeyError: 'TWE'
../../drizzlepac/updatehdr.py:539: KeyError
```
This problem has been resolved with this change to 'updatehdr'.
> Support user-defined WCSNAME values

- drizzlepac/updatehdr.py
Valid a posteriori WCSNAME values were being ignored when creating the WCSTYPE value when trying to account for user created WCSNAME values.  This logic has been revised to correctly allow valid a posteriori fits to be interpreted fully.
> Fix logic for interpreting wcsname

- JenkinsfileRT
- requirements-dev.txt
Update the build requirements to pull in latest version of astroquery from master since it is being actively developed partly to stay in step with astropy as a whole.  Also, this will remove mention of the conda-dev channel for the Jenkins builds, not that it was being used.
> Updating astroquery build reqs for testing

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/product.py
Added some code to hapsequencer.py to instantiate configuration objects into each product object defined by hlautils.poller_utils.interpret_obset_input(). These configuration objects contain all necessary pipeline parameter settings that will be used later on in the hapsequencer run.
> add config object instantiation

- .gitignore
Emacs generate temp file in the format of `*~`.
> Ignore Emacs temp file

- drizzlepac/wcs_functions.py
This fixes a rounding problem with determining the size of the output undistorted WCS for a given set of distorted WCSs.
> Fix rounding problem with creating meta_wcs

- MANIFEST.in
After `drizzlepac-2.2.6` the `pyproject.toml` stopped getting included by `sdist`. I suspect `setuptools` may be to blame for this, because we didn't change anything of note on our end.
> Fix pyproject.toml exclusion from sdist

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/product.py
These changes simply tie the generation of the alignment .reg and .cat files from single-visit processing to the 'debug' parameter, so that they are only generated if 'debug' mode is turned on.  As a result, they are not created during standard pipeline processing.
> Set reg and cat files as debug only

- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/runastrodriz.py
This attempts to correct the logic for handling singletons, especially special singletons like ACQ images, as reported during continued testing of 2019.5.  
The changes were tested against jc3c02b5q, iaaua1n4q, and  j9r384fmq to generate the same set of output files as the pipeline generated in previous builds.
> Singletons 2019 5

- drizzlepac/processInput.py
Simple fix to warn users about use of 'minmed' option in combine step of astrodrizzle when combining more than 5 images.
Tested against j9l902010 and jd5702030.
Addresses #473 .
> Add warning about minmed for N>5

- drizzlepac/runastrodriz.py
This revision addresses the pipeline processing problem where all inputs are 'bad' (EXPTIME==0, for example) and updatewcs does not get applied.  The change forces updatewcs to run (checkfiles=False) in order to apply solutions from astrometry database and reformat the WCS in the header to include the WCSNAME keyword for use in creating a more accurate headerlet for archiving.
Fix was tested on ibvz01010.
> Force updatewcs in cases where exptime==0 for all inputs

- drizzlepac/devutils/comparison_tools/compare_sourcelists.py
- drizzlepac/devutils/comparison_tools/starmatch_hist.py
- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/catalog_utils.py
- drizzlepac/hlautils/hla_flag_filter.py
- drizzlepac/hlautils/photometry_tools.py
- ABMAG calculation from flux now handled by dedicated subroutine photometry_tools.convert_flux_to_abmag().
- Both point and segment code can use photometry_tools.convert_flux_to_abmag() to compute ABMAG from flux.
- Corrected units for flux columns of point catalogs from "erg cm^-2 sec^-1 Hz^-1" to "electrons/second"
- updated drizzlepac/devutils/comparison_tools/compare_sourcelists.py so that it can work with the new catalog format.
> ABMAG calculation cleanup

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/hla_flag_filter.py
- hla_flag_filter.make_mask_file() renamed hla_flag_filter.make_mask_array()
- Modified said subroutine to return the mask array rather than write it to a file
- Updated hla_flag_filter to accept mask array data as input and pass it to hla_nexp_flags()
- Updated hla_nexp_flags code to use in-memory mask array rather than data from _msk.fits file
- Updated hapsequencer.run_sourcelist_flagging() to store the mask array generated by make_mask_array() as an filter_prod_obj attribute if it doesn't already exist so that it can be used for both point and segment hla_flag_filter() runs. This also solves the problem of the code crashing because the mask fits file was being deleted after the point catalog and was not available for the segment hla_flag_filter() run.
- Removed a few lines of code …
> Streamline refactoring of hla_flag_filter.hla_nexp_flags()

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/poller_utils.py
- drizzlepac/hlautils/processing_utils.py
A request was made a while ago to support simpler input formats than the poller files.  This PR attempts to provide support for either a list of dataset names (singleton or ASN filenames only) or a poller file.  
This implementation replaces a simple Table.read() call with a call to a new function which interprets the input as either a list (assuming it is a list of dataset filenames) or a poller file.  If a list if provided, it will use astroquery to make sure all requested files are in the local directory without clobbering any that may already be present, and build a poller file in memory.  This function then returns the poller_table with column names as an in-memory object.
> Initial attempt to update poller file input formats

- drizzlepac/hlautils/align_utils.py
- drizzlepac/updatehdr.py
This simple change takes advantage of the revised alignment code to report SVM as the type of alignment for single visit products (and input exposures), instead of IMG or REL.
> Simple change to report SVM in WCSNAME

- drizzlepac/align.py
- drizzlepac/alignimages.py
- drizzlepac/astrodrizzle.py
- drizzlepac/hapcatalog.py
- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/hlautils/analyze.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/hlautils/astroquery_utils.py
- drizzlepac/hlautils/ci_table.py
- drizzlepac/hlautils/hla_flag_filter.py
- drizzlepac/hlautils/poller_utils.py
- drizzlepac/hlautils/processing_utils.py
- drizzlepac/hlautils/product.py
- drizzlepac/hlautils/se_source_generation.py
- drizzlepac/hlautils/sourcelist_generation.py
- drizzlepac/hlautils/testutils.py
- drizzlepac/runsinglehap.py
- drizzlepac/updatehdr.py
- drizzlepac/util.py
These changes implement a single file as the full log of all processing that takes place for a single visit through `runsinglehap`.  This logging relies entirely on Python's basic logging functionality, with standardized, Python-recommended setup being performed by `stsci.tools.logutil`.
In addition, I addressed some syntax (PEP8) issues and removed some extraneous import statements as well.
> Revise logging

- drizzlepac/hlautils/cell_utils.py
The `np.searchsorted` function was not used correctly by `cell_utils` when determining the projection cell by ID.  This corrects that usage to allow the code to correctly define sky cells and projection cells from cell names.
> Fix problem with defining cells by ID

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/hla_flag_filter.py
- drizzlepac/hlautils/processing_utils.py
These changes redirect the log output from Python to the multiple total products trailer files that get generated for single-visit processing.  It also adds a few key timestamps to the logging as well.   A few flagging comments were also set to use log.debug, instead of log.info just to keep the logs more relevant for casual users.  A lot more comments in this processing can also be moved to log.debug as well, but those will be tackled in later PRs.  Currently, more information goes to each log file than absolutely necessary, but at least they are present for all total products and populated with mostly relevant messages.  
The changes were tested by running `runsinglehap ib4606.out`.
> Get log files written out correctly for multiple TDP

- drizzlepac/hapsequencer.py
Simple change to protect against trying to remove a non-existent log file if logging did not work as intended.
> Protect logname removal

- drizzlepac/runastrodriz.py
Include new logic in `runastrodriz` which looks for any exposure that was 'skipped' originally by 'updatewcs' and re-runs with 'checkfiles=False' to 'force' the update with the reference files and database.  This will insure that ALL input exposures are updated with WCSNAME to avoid problems when trying to write out the headerlet file, as reported during DMS testing for j9by01020.
> Expand logic to apply updatewcs if any exposures were originally skipped

- drizzlepac/align.py
- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/poller_utils.py
The Astropy code used to read in the poller file automatically converted everything to numpy numeric types when at all possible, causing the 'obset_id' column to be converted to non-0-starting integers (1 instead of 01).  This change adds the correct converter to interpret that column as a string and retain the original formatting.  
In addition, the reference catalogs from the alignment step are also (intended to be) removed.
> Add converter to correctly interpret obset_id poller column

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/catalog_utils.py
- drizzlepac/hlautils/ci_table.py
- drizzlepac/hlautils/hla_flag_filter.py
- drizzlepac/runsinglehap.py
See Issue #500.
The rename was done to decouple the variable 'debug' from the python logging level 'debug'. There was never any actual functional overloading--The variable 'debug' never changed logging behaviour, and vice-versa. The rename was done to simply minimize future potential confusion.
> Global rename of variable 'debug' to 'diagnostic_mode'

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/product.py
Change the place in code where the reference catalogs are cleaned up to avoid the following issue:
Not enough reference sources for absolute alignment...
INFO: EXCEPTION encountered in align_to_gaia for the FilteredProduct.
Traceback (most recent call last):
File "/internal/hladata/dev_repos/drizzlepac/drizzlepac/hlautils/product.py", line 224, in align_to_gaia
raise ValueError
ValueError
INFO: No correction to absolute astrometric frame applied.
WARNING: Step to align the images has failed. No alignment table has been generated.
INFO: 
Traceback (most recent call last):
File "/internal/hladata/dev_repos/drizzlepac/drizzlepac/hapsequencer.py", line 357, in run_hap_processing
for catalog_name in align_table.reference_catalogs:
AttributeError: 'NoneType' object has no attribute …
> Adjust where the reference catalogs are cleaned up

- drizzlepac/align.py
- drizzlepac/alignimages.py
- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/hlautils/astroquery_utils.py
- drizzlepac/hlautils/poller_utils.py
- drizzlepac/runsinglehap.py
This updates the format of the log messages generated by single-visit processing modules (as per #502 ).  
The changes were implemented for 'runsinglehap' and 'hapsequencer' in order to enable easier testing of the log format and datetime format changes.
> Format log messages to be DMS-compatible

- drizzlepac/hapsequencer.py
- drizzlepac/runsinglehap.py
- This PR allows the user to specify the logging level (CRITICAL/ERROR/ Etc...) as a command-line input to runsinglehap.py. (See issue #501)
The runsinglehap.perform() subroutine and the the main logging definition at the top of the code were modified to accommodate a user-specified log level.
- The hapsequencer.run_hap_processing()  subroutine and the the main logging definition at the top of the code were modified to accommodate a user-specified log level.
- Fellow Burgundy team members can now use log_level for their work towards issue #502.
> Add command-line input "log_level" to runsinglehap.py, hapsequencer.run_hap_processing

- drizzlepac/processInput.py
The drizzle processing code not only generates default output names determined from the ASN file, but it can also support user-provided output names.  Unfortunately, as a result, it was looking to see whether a valid output name was provided to determine how much work it needs to do to create it's own valid output name; in this case, valid meaning something that ends in _drz.fits.  The previous logic was only looking for 'drz' in the output name.  😉  These datasets have 'drz' in the middle of the rootname, so the logic in the code said it had a valid output name as input and did not make sure the filename ENDED in _drz.fits. 
This fix looks for the more specific '_drz' instead to build the final output name for the empty drz product.  It has been tested using jdrz2m010.
> Fix empty drz naming problem (HSTSDP-851)

- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/runastrodriz.py
A new algorithm has been added to detect differences between images; specifically, single drizzle images and the final drizzle product.  This algorithm works with differences larger (and apparently invisible) to the similarity index as well as the focus index which both identify more subtle (primarily sub-pixel) alignment issues.  The code uses this new algorithm to reject any alignment where the differences are greater than 10% between the single-drizzle product ('truth') and the combined drizzle product in the area of greatest overlap between the 2 products.  
The dataset `ib5w02030` includes observations with less than 10% overlap between pointings where the aposteriori fitting initially resulted in double-exposures in some of the overlap region.  This new algorithm identified that …
> Add overlap diff verification to detect double-images

- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
Changed "skystat" from "mode" to "median" in the "STEP 2: SKY SUBTRACTION" sections of the following astrodrizzle param files:
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodri …
> Modify existing WFC3/IR configuration files for SVM processing

- drizzlepac/hlautils/product.py
Although a previous PR really addresses the situation where there is no viable data to align, the `refname` variable has been further protected.
> Further protect variable refname in FilterProduct

- drizzlepac/pars/hap_pars/acs_sbc_index.json
Fixed a few typos in the ACS/SBC JSON index file for the astrodrizzle configuration filenames.  The files already exist, but the names in the index file were incorrect.
> Fixed filenames in ACS/SBC JSON index file

- drizzlepac/devutils/alignment_viewer.py
- drizzlepac/runastrodriz.py
This change works entirely within runastrodriz (pipeline processing) to insure that any exposure taken after 10/1/2017 will have '-GSC240' at the end of the apriori-corrected WCSNAME since it will not be getting that from the astrometry database.
> Added function to verify GAIA WCSNAMEs

- drizzlepac/runastrodriz.py
Zero exposure time images do not get updated with 'updatewcs' and therefore have not WCSNAME keywords (or other calibrated keyword).  This adds logic to allow the code to skip these datasets when processing through runastrodriz.
> Avoid zero exptime

- drizzlepac/devutils/comparison_tools/compare_sourcelists.py
- drizzlepac/devutils/comparison_tools/starmatch_hist.py
- drizzlepac/hapsequencer.py
See issue #542.
This script adds an additional step in hapsequencer which attempts to locate the equivalent HLA classic filter product image and sourcelist for each HAP filter drizzled product image/source list pair, and then if the HLA classic files are found,  executes drizzlepac/devutils/comparison_tools/compare_sourcelists.py.
Highlights:
- Added subroutine _run_sourcelist_comparision_ to hapsequencer.py. This subroutine takes care of locating the relevant HLA classic image/sourcelist and the actual execution of compare_sourcelists.py
- Brought logging in compare_sourcelists.py and starmatch_hist.py up to HAP standards
- Sanitized all mentions of absolute paths in log messages in compare_sourcelists.py and starmatch_hist.py
- The filenames of all .pdf plot files generated by …
> Add automated HLA classic sourcelist comparison

- drizzlepac/hlautils/cell_utils.py
In module cell_utils.py, the build method of the SkyFootprint class had been updated, and subsequently, broke the code which computes the mask used by the Segment Catalog to distinguish between illuminated and non-illuminated portions of the input image.  In the old version of the code, the variable `blank` was appended each time through the inner `for` loop.  As such, the variable `self.total_mask` just needed to be updated for each new file examined.  In the new implementation, the variable `blank` is essentially reset each time through the `for` loop, so the variable `self.total_mask` needs to be updated every pass of the inner `for` loop.  
This PR addresses Issue #546.
> Modified SkyFootprint build method 

- CHANGELOG.rst
- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/runastrodriz.py
The RMS_RA, RMS_DEC, and NMATCHES keywords were being added to the headerlets created during the a posteriori alignment step of runastrodriz.  However, those headerlets were not getting copied over from the aposteriori processing sub-directory for use as the final headerlet.  
These changes insure that the headerlets get copied as the working headerlets.  In addition, the aposteriori aligned FLC/FLT images get updated with the values of these keywords as well with these code changes.  Between the two sets of changes, all critical fit information finally makes it into the outputs generated and used by the pipeline.  
This addresses #554.
> Add rms to headers

- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/runastrodriz.py
Errors in the alignment can often cause the a posteriori alignment to exit before determining a fit; sometimes as the result of an Exception, sometimes as a result of the data (too few sources,...).  Processing in the pipeline, though, requires that all open files be closed before exiting the a posteriori alignment step.  This includes both logging files as well as any open input or output files.  
The changes here explicitly close all the input files anytime the alignment code returns before full completion (an oversight in the original implementation).  There are also changes to define default values upon returning early to avoid subsequent Exceptions as well due to lack of a "best fit".  
These changes were tested using the singleton `ibbq01n0q` as reported by DSB during their nightly …
> Close open files in align upon error

- drizzlepac/runastrodriz.py
Logic for determining what MDRIZTAB reference file row should be used to set the correct parameters for the processing did not guard against all inputs having EXPTIME=0 and therefore not processed.  This change simply catches that case and reverts to assigning the MDRIZTAB row as if all were good when all inputs have EXPTIME=0.  This will not affect the generation of the actual output product, but does allow the code to run to completion (useful for the pipeline).
> Catch case where all inputs have zero exptime

- drizzlepac/runastrodriz.py
This fixes a problem with the logic for determining the MDRIZTAB parameters to be used in pipeline processing when all inputs have EXPTIME=0 (and are rejected for processing).  The changes in this were separately delivered to HSTDP 2019.5.1 on branch 3.1.4x (#564), and this merges those changes into master.
> Fix logic for getting MDRIZTAB pars

- drizzlepac/hlautils/analyze.py
- drizzlepac/hlautils/product.py
The filenames of the input exposures need to be compatible with the rest of the SVM generated products to indicate what has been updated with the SVM alignment and to keep all the products together in the archive. 
This was done by copying the input FLT/FLC exposures to files with new filenames that follow the HAP naming convention. The new filenames then get used throughout the processing, most importantly when writing out the manifest file for archive ingest.  This implementation also has the distinct advantage of insuring that the original pipeline-processing input files are not modified (even inadvertantly) by the SVM processing.  
Addresses #539 .
> Update SVM processing to use HAP names for input exposures

- drizzlepac/hlautils/poller_utils.py
The poller_utils interface did not correctly handle a simple 1 column file with filenames as input to runsinglehap.  This corrects that problem so it does not throw an exception.  These changes change the interpretation to work with a single column input file as well as a Python list or a full poller file.  
It was successfully tested using data from visit 'ib6wd6'.
> Fix simple poller input

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/hlautils/cell_utils.py
- drizzlepac/hlautils/product.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
- drizzlepac/updatehdr.py
This implements the initial version of a single WCS fit for all exposures in a single visit for a single instrument (across all detectors used for the visit) as described in #521.  This does NOT implement the actual input exposure sorting described in #521 that will be expected by this PR.  
- User values and default values for tolerance for 'match_relative_fit' were lowered to 0.5.  This relies on the assumption that the errors in the proper motions for the GAIA sources are going to be within 20-25 mas depending on the time of the observation for enough sources to get a good alignment to GAIA. 
-  The fit uses the 'relative' fit method to align all exposures to each other THEN perform a single uniform fit to GAIA for the entire mosaic and relies on background and source determinations …
> Implement v1.0 of single fit for entire visit

- drizzlepac/hlautils/processing_utils.py
Removed the last character in the root filename (rootname=ipppssoot) before comparison to expname=*ipppssoo_.  The rootname could never be found in the expname which eventually caused the code to fail with an error.
> Removed last character in the root filename to fix a bug

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/catalog_utils.py
- drizzlepac/hlautils/product.py
Fixed bug  so only the drizzle FITS files have their headers modified as the output product list now also includes the headerlet and FLT/FLC FITS files.  Changed variable name: total_list to total_obj_list.  Corrected name of column in Segment catalog from MagAp to MagAP.
> Fixed bug in generating the manifest list

- drizzlepac/hlautils/catalog_utils.py
- drizzlepac/hlautils/product.py
The boolean mask which is used to identify sources in the usable illuminated image region for the segmentation catalog has been improved.  When in diagnostic mode, a segmentation and possibly a deblended segmentation image will be created for debug purposes, the obsolete parameter, preserve, is set to False in the Product classes so no OrIg_files subdirectory will be created.
> Improved the boolean mask creation for use with segmentation catalog

- drizzlepac/hlautils/catalog_utils.py
The regions file should only be generated at this point in the code if the program is being run in diagnostic mode, AND it is the total object product being processed.  The check for the existence of self.segm_img should not have been removed.
> Fix bug introduced in commit fc98ce6 for diagnostic mode only.

- drizzlepac/hlautils/align_utils.py
Simple change to update HDRNAME in output drizzle products so that it remains consistent with WCSNAME after performing the a posteriori alignment.
> Keep HDRNAME consistent with WCSNAME

- doc/source/index.rst
- doc/source/pixreplace.rst
- drizzlepac/__init__.py
- drizzlepac/hlautils/align_utils.py
This simple change explicitly updates the aligned FLT/FLC files with the HDRNAME associated with the new WCS solution (based on WCSNAME).  This change will insure that the HDRNAME and WCSNAME keywords in the FLT/FLC files stay in sync, something which was not happening during HSTDP 2019.5.1. regression testing. 
In addition, the docs were updated to document the 'pixreplace' task which has been a part of the drizzlepac package since 2015.  Only the docs were updated, and no code was changed for this task.
> Add hdrname to hdulist

- drizzlepac/hlautils/poller_utils.py
This modification checks that the input poller manifest file is not of length zero (empty file).
> Check the input file to make sure it does not have zero size.

- drizzlepac/hlautils/analyze.py
- drizzlepac/hlautils/poller_utils.py
SBC filter names are currently malformed (e.g., "F140LP;N/A;F140LP" in the SVM poller manifests.  The third token delimited by ";" should not be present. Also, the "N/A" needs
to be replaced with "none" as the slash cannot be part of the output filename.  The code has been modified to handle this situation.
> Modified the handling of the filter values to accommodate SBC names

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/catalog_utils.py
- drizzlepac/hlautils/poller_utils.py
- drizzlepac/hlautils/product.py
Modified the segmented catalog to address bugs, make improvements, and to align better with the way the Point catalog is produced.
- Use option "columns" on to_table() method so only desired values are computed.
- Need to provide both the segmented image, as well as the total detection catalog to
the filter product object.
- Change some methods to modify the passed table parameter object as if "passed by
reference" rather than return a new table.
- Use list indices for addressing column "good" or "bad" rows.
- Put X-/Y-centroids and RA/Dec coordinates, as captured from the total detection
table, for corresponding segments in the filter catalog which could not be measured.
- Create columns of the output filter table and fill values with nans.  For any
measurments that cannot be made, a nan …
> Segmented Catalog Updates

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/catalog_utils.py
Modified hapsequencer (create_catalog_products) when one or both algorithms (point and segment) do not find any sources in a total detection product.  If neither algorithm finds sources, escape the for loop and do not create any catalogs.  However, if only one of the algorithms does not find any sources, the other algorithm must be allowed to continue on to the associated filter catalogs.  Also, if multiple detectors are represented in the visit, the logic needs to start fresh for both algorithms.  Finally, since a specific algorithm can be requested via input parameter, this must also be accommodated in the logic.
> Modify SVM code to handle "no sources found" gracefully

- CHANGELOG.rst
- drizzlepac/hlautils/analyze.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/imgclasses.py
- drizzlepac/runastrodriz.py
These commits fix numerous bugs reported as a result of initial reprocessing after installing HSTDP 2019.5.1 (quick-fix).   Multiple bugs will be addressed starting with:
- **jcwr03030** : Processing encountered recursion error (exceeded maximum limit) caused by FWHM being measured for 'sharpest' focus object in field that was too close to the edge of a chip.  
- **j8uw01020** : One (of the 2) exposures in the association had NGOODPIX=0, yet it was still being passed to AstroDrizzle() as if it was valid, causing the wrong parameters to be set for processing and resulting in 'too many pixels rejected' error. 
The datasets listed with each error not only the datasets reported in reprocessing as having errors, but were also used to demonstrate the original problem for debugging and used to …
> Fix HSTDP 2019.5.1 bugs

- CHANGELOG.rst
- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
- setup.py
This includes the minimum set of code changes needed to use the new 'tweakwcs' (v0.6.0, when released).  See [tweakwcs PR 105](https://github.com/spacetelescope/tweakwcs/pull/105) for details on what changed in the API.  See [tweakwcs PR 106](https://github.com/spacetelescope/tweakwcs/pull/106) on details of bug fix for HST alignment problems.
> Minimum changes in pipeline code needed to use new tweakwcs

- drizzlepac/hlautils/hla_flag_filter.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_quality_control_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_quality_control_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_quality_control_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_quality_control_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_quality_control_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_quality_control_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_quality_control_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_quality_control_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_quality_control_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_quality_control_all.json
**Summary**
Up to this point, there was no way hla_flag_filter.py to use user-specified ci limits from the parameter files. The values for ci_lower_limit and ci_upper_limit were determined by the  ci_table.get_ci_from_file() subroutine even though ci limits are explicitly set in the quality_control_all.json parameter files. The 
This PR addresses that issue by simply adding a new parameter the quality_control_all.files called "lookup_ci_limits_from_table", and wrapping the call to ci_table.get_ci_from_file() in some logic. Now, if lookup_ci_limits_from_table is set to "true", ci_table.get_ci_from_file() is executed. However, if lookup_ci_limits_from_table is set to "false", ci_table.get_ci_from_file() is not executed, and the existing values for ci_lower_limit and ci_upper_limit from the …
> Make hla_flag_filter.py concentration index limits user-definable

- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
This simply insures that the correct values are being pulled from the fit_info structure after being revised in tweakwcs v0.6.0.  Duplicate functions were also removed from align.py as well to prevent any further confusion.
> Remove duplicate function; refer to correct fit_info values

- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/runastrodriz.py
This set of changes addresses the following issues:
- computation of similarity between images had a bug in computing final binned size for images
- criteria for overlap diff needed to be revised to not be so strict (based on testing of icw402010)
- logic for determining pass/fail of verification of overlap diff and similarity needed to be corrected and massively simplified in the process
- apriori alignment failure now resets the PRIMARY WCS to the pipeline-default IDC_* solution as originally designed, instead of defaulting to 'best' astrometry database solution which may have been corrupted.
> Correct overly complex verification logic

- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/runastrodriz.py
This adds a '.write()' method to the AlignmentTable class which dumps the 'selected_fit' list out to a pickle file for further analysis by the end-user/pipeline.  In addition, 'runastrodriz' and 'align.perform_align' were updated to call this when 'debug=True'.  
This pickle file supplements the GAIA catalog written out as 'ref_cat.ecsv' and 'refcatalog.cat' used for the alignment to provide a more complete view into what went into the fit which was deemed 'best' during pipeline processing.
> Write out alignment's selected fit in debug mode

- drizzlepac/hlautils/astrometric_utils.py
The logic which checks to see whether images are blank when computing the overlap differences could have been skewed by crowded fields or large extended sources.  Therefore, an additional condition based was implemented to insure the logic does not get fooled by (too many) crowded field/extended source images.
> Insure blank images are actually blank

- azure-templates.yml
- drizzlepac/hlautils/align_utils.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/runastrodriz.py
This revision moves the code that performs CR flagging so that it is done anytime the verification of the alignment fails, as opposed to only doing it if apriori alignment failed to verify.  In addition, the parameters for computing sources in the overlap region was refined to return segmentation maps for the sources which are broader than before, allowing the overlap computation to be a little less sensitive to noise.  Also, an astropy deprecation warning was also resolved.  
This change was tested on these datasets: jcdm42010, idn117010, icw402010, j90o47zjq, ibsl31030, ib6w61050, and idhq04010.
> Apply CR flagging every time WCS fails verification

- JenkinsfileRT
This was overlooked in https://github.com/spacetelescope/drizzlepac/pull/613
> Remove codecov --token flag; rely upon env var instead.

- drizzlepac/hlautils/astrometric_utils.py
The original similarity check has now been merged into the overlap difference computation to guard against bad-pixels skewing the overlap difference computation.  This should restore the original successes we had based solely on the similarity while also taking advantage of the overlap difference checking.  
The dataset jbet3r010 was used to verify that it worked as expected, since the overlap difference got dramatically skewed while the similarity index reflected what a user would see interactively.
> Merge old similarity with overlap diff

- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/hlautils/astroquery_utils.py
- drizzlepac/runastrodriz.py
It turned out that background subtraction was not being done consistently for each of the iterations of the drizzling during standard pipeline processing.  This led to images which are mostly blank to fail similarity comparison due to differing background levels resulting in many datasets not getting updated WCS solutions when they were appropriate.  
In addition, datasets which can not be aligned in the pipeline with an aposteriori solution (such as prism or grism datasets), were not being handled correctly and an unnecessary exception was being thrown.  This also prevented the apriori solution from being applied in some cases where it should have been.
These changes address both of these issues and were tested on ALL 209 datasets that only had pipeline default solutions (or NONE) from …
> Insure background subtraction is consistently applied

- drizzlepac/devutils/alignment_viewer.py
The 'alignment_viewer' had problems with some datasets when used on 1000 random datasets processed interactively, and these changes insure that all datasets can generate a comparison page.  
In addition, several new fields were added to the summary JSON file that gets generated along side the PDF report.
> Fix bugs in alignment_viewer

- drizzlepac/hlautils/align_utils.py
- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/hlautils/quality_analysis.py
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/runastrodriz.py
This addresses problems seen in extended testing of 1000 datasets where an Exception gets thrown when 1 image in a set did not have a successful relative fit while the others did.  This showed up as the Exception:
`
KeyError: "fitmask"
`
In addition, problems with blank images not generating a source catalog was causing 'amutils.build_wcscat' to throw the following Exception:
`  
File "/home/mburger/anaconda3/envs/2019.5.clone/lib/python3.6/site-packages/drizzlepac/hlautils/astrometric_utils.py", line 559, in extract_point_sources
if high_sn is not None and len(srcs) > high_sn:
TypeError: object of type 'NoneType' has no len()
`
Both of these issues were corrected in this PR based on testing of ibc305yvq, iaac240d0, ibg414010, and ibh707010.
> Fix fitmask exceptions for blank images 

- drizzlepac/hlautils/astrometric_utils.py
- drizzlepac/runastrodriz.py
For datasets with no detectable point-sources, the quality analysis code ended up getting only 4 empty columns returned by the source finding code 'tweakutils.ndfind'.  This resulted in the following Exception being thrown as detected through testing:
`
File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/hlautils/astrometric_utils.py", line 561, in extract_point_sources
nbright=nbright)
ValueError: not enough values to unpack (expected 7, got 4)
`
This simple fix insures that the returned values always have the same number of values to unpack (7).  This fix was verified using ibh705w8q (original error case) and iaac240d0 (case with detected sources).
> Insure src catalog always has same number of columns

- drizzlepac/hlautils/catalog_utils.py
Fixed a bug which only happened in diagnostic mode.  After source segments are detected, a deblending process is invoked.  In diagnostic mode the inadvertent use of a non-existent variable caused an exception.  While this bug was not fatal, it could significantly reduce the number of detected sources in the image.
> Segmentation catalog bug in diagnostic mode

- drizzlepac/hlautils/quality_analysis.py
- drizzlepac/runastrodriz.py
The QA test for standard pipeline processing originally passed in the alignment dictionary generated during processing.  However, in cases where all astrometry updates get turned off, this dict is uninitialized.  Furthermore, it turned out the QA test did not use that input in the first place (planned for, but not used).  
This set of changes addresses both situations as documented in JIRA ticket [HLA-317](https://jira.stsci.edu/browse/HLA-317).
> Reset initialization for pipeline QA test

- drizzlepac/hlautils/align_utils.py
- drizzlepac/hlautils/product.py
- drizzlepac/hlautils/quality_analysis.py
Not all datasets have enough (good quality) sources to perform a full 'general' fit, which is the default for tweakwcs.  These changes expose control over the 'fitgeom' parameter in `tweakwcs.align_wcs()` to enable the code to set the value instead of relying solely on the default value.  Additional PRs/tickets will be needed to describe work to define the value of 'fitgeom' for each instrument if that turns out to be necessary.
The SVM processing was updated to set the value of 'fitgeom' to 'rscale' for all SVM processing under the assumption that higher order fitting done in standard pipeline processing has accounted for any skew in the observations being combined in SVM processing.   
This addresses [JIRA Ticket HLA-316](https://jira.stsci.edu/browse/HLA-316).
> Enable control over fitgeom in alignment

- drizzlepac/hlautils/astrometric_utils.py
The 'within_footprint' function in astrometric_utils needed to be updated to take into account the changes in the astropy.wcs API.  
In the process, the API was changed to return (a more useful) mask indicating which sources were actually found to be within the footprint.
> Rework within_footprint to work

- drizzlepac/hlautils/align_utils.py
An oversight in redefining the terms reported in debug mode within AlignmentTable caused the code to throw an Exception when log_level = DEBUG. This change corrects that mistake by reporting a value that actually gets computed.
Essentially cherry-picking PR #652 for the release branch.
> Fix debug problem in AlignmentTable for 3.1.8x

- drizzlepac/hlautils/align_utils.py
An oversight in redefining the terms reported in debug mode within AlignmentTable caused the code to throw an Exception when log_level = DEBUG.  This change corrects that mistake by reporting a value that actually gets computed.
> Correct debug statement in AlignmentTable

- drizzlepac/hlautils/align_utils.py
Some datasets trigger an Exception when trying to close an already closed fits.HDUList object for the input image.  The change here adds logic to look for this case and handle it correctly.  
This error case was identified when processing jc4b03010, which this change resolved.
> Address error case in AlignmentTable

- drizzlepac/align.py
- drizzlepac/hlautils/align_utils.py
- drizzlepac/runastrodriz.py
HSTDP 2020.2 testing encountered exceptions being generated, and worked around, when pipeline processing j9l929010 and 9 other datasets.  It turns out that these datasets still have incomplete IDC_* solutions in the astrometry database, and trying to restore one of them as the active PRIMARY WCS caused subsequent processing to throw an Exception (missing wcs.idcscale).  
These changes address this issue as well as tries to make the names for the new aposteriori headerlets consistent with what is stored in the database.
> Resolve HSTDP2020.2 WCS exceptions

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/catalog_utils.py
Changes based on what was learned in #643 for the alignment steps were now applied as appropriate to the catalog generation processing as run in single-visit processing.  These appear to improve the memory use (cutting it by 1/3 or more in processing iboa31) without affecting the final results.
> Improve catalog memory

- drizzlepac/hapcatalog.py
- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/cell_utils.py
- drizzlepac/make_cfgobj_files.py
- drizzlepac/run_config_utils.py
This simple update replaces the expected list of headerlet filenames that currently gets added to the manifest file with the list of actually generated headerlet filenames.   Initial testing indicates it does not interfere with generating the manifest file when all expected headerlets are written out (verified using iboa31).
> Initial fix for manifest file

- drizzlepac/imgclasses.py
- drizzlepac/processInput.py
- drizzlepac/resetbits.py
- drizzlepac/sky.py
The function 'interpret_dq_bits' originally developed as part of 'stsci.tools.bitmask' has been integrated (as-is?) into astropy.  These changes simply replace the imports to point to the astropy version now instead of stsci.tools.  
The astropy function has the exact same API for both inputs and output values while also retaining (word-for-word) the same docstring description making this a pure drop-in replacement for the stsci.tools version the code had been using.
> Update imports of interpret_big_flags to use astropy instead

- drizzlepac/hapsequencer.py
- drizzlepac/hlautils/svm_quality_analysis.py
- Fixed use of variable before its initialization.
- Removed call to report_wcs from hapsequencer.py as the routine is called within svm_quality_analysis.py.
- Found bug in reporting all of the alternate WCS solutions in a single exposure,
as well as the Delta (Primary-Alternate) solution.
- Also found the statistics for all exposures in a particular total drizzled
product were not reported due to non-unique labels for parts of the JSON
hierarchy.
> Updates to SVM Quality Test "report wcs".

- CHANGELOG.rst
- drizzlepac/findobj.py
Source finding in very large images fails due to convolution image containing `NaN`s. This is due to a bug in `scipy.signal.convolve2d` - see https://github.com/scipy/scipy/issues/10761 
Both `scipy.signal.fftconvolve` and `scipy.ndimage.convolve` work correctly.
This PR replaces the call to `scipy.signal.convolve2d` with `scipy.ndimage.convolve`.
> Fix a crash when finding sources in very large images

- drizzlepac/hlautils/align_utils.py
- drizzlepac/hlautils/poller_utils.py
- drizzlepac/runastrodriz.py
The astrometry pipeline processing in svm0.2.6 was found to have bugs which prevented it from successfully completing.  Specifically, the selection of the correct apriori WCS from the astrometry database did not reset for each file, so it tried to update the second (and subsequent files) with a headerlet that had the name defined in the first image.  In addition, the sorting implemented in poller_utils was updated to document how the sorting needs to take into account saturation in the images, something that will need to be implemented in a later revision. 
This fix resolves that problem and allows the data to process correctly.
> Fix critical bugs in svm026

- drizzlepac/haputils/align_utils.py
This insures that all places where the default value for the fitting mode is defined as 'rscale' and not 'general'.  The standard pipeline processing relies almost exclusively on these default values insuring that (as requested by INS and the HSTMO) there can be no chance that pipeline processing will use 'general' fitting mode for aligning data either in a relative sense (exposure to exposure) or in an absolute sense (to GAIA).
> Insure rscale as primary/default fit mode for all alignment

- azure-pipelines.yml
The Windows builds are not properly supported yet.  Therefore, they should be commented out and re-instated once we start supporting that platform again.
> Comment out Windows builds for now

- drizzlepac/align.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
- drizzlepac/runastrodriz.py
Yet another way in which we can insure that only 'fitgeom=rscale' gets used.
> Update all alignment parameter files to force use of rscale only

- tests/hap/test_pipeline.py
Remove code that overrides the definition of the TEST_BIGDATA environment variable to try to get all regression tests to run to completion each night.
> Remove override of TEST_BIGDATA definition

- drizzlepac/haputils/product.py
Pipeline processing of HAP products requires the use of the HAPLEVEL keyword in order for the system to categorize all the products correctly and successfully archive the results.  This small fix adds this keyword to the HAP input files.
> Add HAPLEVEL to ExposureProduct file headers

- drizzlepac/haputils/svm_quality_analysis.py
- Fixed report_wcs() to generate its JSON output in a more efficient manner in terms of space saving.  This comes at the cost of more JSON files being produced - one per exposure in a visit. However, this makes the WCS data in the final Pandas dataframe more accessible.
- Made the output JSON file name conform to the naming convention
adopted for the SVM products.
> Updated report_wcs() in svm_quality_analysis.py

- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/quality_analysis.py
This simple change resolves the problem in `quality_analysis` when it tries to report the name of the module and did not have that information defined yet as `__taskname__`. 
Additional information on the number of matches used in the relative fit now also gets reported to aid in debugging and quality analysis of each dataset as it gets processed.
> Add taskname to quality_analysis

- drizzlepac/haputils/diagnostic_json_harvester.py
The current version of the JSON harvester will only search for JSON files in the currently specified directory.  This works perfectly well when all the data is in a single directory, perhaps as will be the case for pipeline processing.  Unfortunately, testing on large numbers of datasets, each in their own directory, makes this code impossible to collate all the JSON files since it would need to be called separately for each dataset/directory.  
This small revision simply adds logic to look in the underlying directories for the desired JSON files.  The result is that a single call pointing to the parent directory for all the datasets directories can now find all the desired JSON files in one step resulting in a collated Pandas DataFrame file with all the results.
> Expand search for JSON files in harvester

- drizzlepac/haputils/align_utils.py
Fitting performed by alignment code was intended to use the parameters stored in the config parameter files for the package.  This set of updates finishes the implementation of using those values with 'tweakwcs'.  
This addresses Jira ticket HLA-380 and closes #701  when merged.
> Use min obj as define in default parameter config files

- CHANGELOG.rst
- drizzlepac/outputimage.py
Recent changes to `stwcs`, see, e.g, https://github.com/spacetelescope/stwcs/pull/141 introduced warnings in drizzlepac, in particular during the `blot` step. These warnings are similar to:
```
-Generating simple FITS output: j8c107d5q_sci1_blt.fits
WARNING: wcs_from_key: Could not read WCS with key A [stwcs.wcsutil.altwcs]
WARNING:               Skipping in-memory file '[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x134ec9650>][0]' [stwcs.wcsutil.altwcs]
WARNING: wcs_from_key: Could not read WCS with key B [stwcs.wcsutil.altwcs]
WARNING:               Skipping in-memory file '[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x134ec9650>][0]' [stwcs.wcsutil.altwcs]
```
As a result, alternate WCSes in blotted are not removed.
I tracked these warnings to the following two factors:
1. …
> Add CPDIS and DP to the list of distortion keywords

- doc/source/astrometry.rst
- doc/source/hla.rst
- doc/source/index.rst
- doc/source/runastrodriz.rst
The documentation in this package needs to be updated to more fully explain the expanded astrometry processing now implemented for pipeline calibration of HST imaging data.  Updates to the documentation are intended to provide end-users with a better understanding of the logic and algorithms used to do what is possible to get their HST data aligned to GAIA as well as possible while retaining the relative alignment between all their exposures.
> Update docs to describe astrometry processing more fully

- doc/source/runastrodriz.rst
Simple update to reword some very clumsy descriptions in the runastrodriz readthedocs documentation.
> Fix clumsy text in runastrodriz docs

- drizzlepac/ablot.py
- drizzlepac/adrizzle.py
The undocumented TEAL interface for just the 'adrizzle' and 'ablot' stand-alone tasks did not enforce integer values for the user-defined custom output WCS generation.  These small changes simply insure that user-provided sizes are always cast as integers before being used to define the custom output WCS. 
This problem came to light as the result of a user help question.
> Update adrizzle teal interface

- CHANGELOG.rst
- drizzlepac/buildwcs.py
- drizzlepac/imgclasses.py
- drizzlepac/outputimage.py
- drizzlepac/tweakback.py
- drizzlepac/tweakreg.help
- drizzlepac/tweakreg.py
- drizzlepac/updatehdr.py
- drizzlepac/util.py
This PR greatly simplifies the logic for archiving primary WCS. Now, if `'reusename'=True` then primary WCS is archived if provided `'wcsname'`is different from the `'WCSNAME'` of the primary WCS in image headers.
If primary WCS' name is the same (case-insensitive) as the name provided by `'wcsname'` parameter and `'reusename'=True`, then primary WCS will be updated by `tweakreg` in-place without archiving primary WCS. If `'reusename'=False` then an exception will be raised.
This PR reduces the number of duplicate alternate WCS created by `tweakreg` and it also solves the issue of non-unique WCS names in image headers: the algorithm is designed not to create WCSes with the same name.
Fixes #697 
This PR **requires functionality from** https://github.com/spacetelescope/stwcs/pull/149 and …
> Simplify logic for archiving WCS in tweakreg

- drizzlepac/haputils/align_utils.py
Added logic to avoid trying to delete the HDRNAME keyword when it was not present.  This affected the processing of some associations (like j9l929010).
> Catch when HDRNAME is missing

- drizzlepac/devutils/comparison_tools/starmatch_hist.py
- drizzlepac/haputils/hla_flag_filter.py
- drizzlepac/haputils/svm_quality_analysis.py
**Linked issues/tickets**
- Git issue #702 
- JIRA ticket [HLA-381](https://jira.stsci.edu/browse/HLA-381)
**High-level summary**
-Added new test to svm_quality_analysis.py that quantifies the quality of alignment of filter products in multi-filter datasets. 
- This is accomplished for a given multi-filter dataset by:
1. independently identifying point sources in each filter product
2. convert X and Y coords of all identified sources to the common reference frame of the image that yielded the most sources.
3. Cross-match using the catalog with the most sources as the reference for all crossmatches
4. Compare the X, Y positions of the cross-matched sources in the various catalogs vs. the reference catalog and compute statistics on the differences.
5. For each interfilter comparison, write …
> Generate cross-filter point-source comparisons

- drizzlepac/haputils/diagnostic_json_harvester.py
diagnostic_json_harvester.py: added logic to make_dataframe_line() to ONLY harvest values the following header keywords into a dataframe line:
- APERTURE
- CHINJECT
- DATE-OBS
- DEC_TARG
- EXPTIME
- FGSLOCK
- GYROMODE
- MTFLAG
- OBSKEY
- OBSTYPE
- RA_TARG
- SCAN_TYP
- SUBARRAY
- TIME-OBS
> Filter out various header keywords from json file harvesting

- drizzlepac/runmultihap.py
This simply adds a draft, skeleton MVM sequencer to the package to use as the basis for developing the final pipeline implementation of the MVM processing code.
> Add skeleton MVM sequencer for testing

- drizzlepac/haputils/graph_utils.py
- Removed deprecated code as we do not allow the user to set any figure
tools explicitly.
- Added comments for clarity.
> Remove deprecated code

- drizzlepac/align.py
- drizzlepac/haputils/pipeline_graphics.py
- drizzlepac/haputils/quality_analysis.py
- drizzlepac/haputils/testutils.py
- drizzlepac/outputimage.py
- drizzlepac/runastrodriz.py
The comparison of the dataset's point-sources to the absolute astrometry reference sources from the GAIA catalogs can provide another measure of the quality of the pipeline processing.  These changes add those residuals to the set of Q&A JSON files that can be generated for pipeline processed datasets.   The comparison implemented here relies on the cross-matching of the point sources actually used for the pipeline alignment with the GAIA reference sources. 
This work addresses [Jira ticket HLA-369](https://jira.stsci.edu/browse/HLA-369).
> Add generation of absolute astrometry residuals to pipeline Q&A tests

- drizzlepac/haputils/diagnostic_json_harvester.py
- drizzlepac/haputils/pandas_utils.py
- drizzlepac/haputils/svm_quality_graphics.py
The new API was used to generate the point-to-segment-catalog cross-match comparison histograms.  
This set of changes also includes an update to the JSON harvester code to support user-provided search patterns.  Using only the SVM search pattern allows the harvester to work on the full set of SVM JSON files to successfully create a single master file. 
Finally, the `get_pandas_data` function has been replaced by an updated function with the same name in 'pandas_utils' in an effort to minimize the number of copies of at least this one utility function. 
This supports [Jira Ticket HLA-394](https://jira.stsci.edu/browse/HLA-394).
> Update SVM point-to-segment catalog xmatch comparison plots

- drizzlepac/align.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/runastrodriz.py
Data with some extreme fields-of-view or extreme problems exposed failures in some of the error handling with the alignment code.  These problems were seen in datasets ibm503tnq, idn110010, and idw101090.  The problems which were corrected were:
- failure to recognize when no sources were found while running 'build_auto_kernel'
- an empty entry is now always provided for all input files when configuring the fit in AlignmentTable
- the extracted PSF to be measured by 'find_fwhm' is checked to have a minimum size to allow 'find_fwhm' to not throw an Exception
- failure to find an aposteriori solution in runastrodriz gets caught with a check for None before trying to interpret the returned results
In addition, logging configuration for AlignmentTable was passed in and used to expand the log …
> Fix problems identified in Build 2020.4 testing 

- drizzlepac/haputils/quality_analysis.py
These small changes insure that should a singleton be processed, the attempt to generate relative astrometry residuals does not prevent the GAIA residuals generation to fail.
> Fix logic for singleton QA Gaia Plotting

- drizzlepac/haputils/quality_analysis.py
This fixes problems with the selected fit not using all the matched sources due to sigma clipping which caused a mis-match between the GAIA source list and the input source list.  This problem was found during astrometry testing with dataset jd8f16010.
> Fix QA indexing problem

- drizzlepac/align.py
- drizzlepac/runastrodriz.py
Some datasets do not get drizzled while other datasets do not result in successful aposteriori solutions, and both were causing runastrodriz to throw an Exception during processing.  The code has been updated with:
- update to align to return the full alignment table upon errors (this was already happening for most error cases, but somehow this slipped through).
- update logic to only run QA test results when DRIZCORR was turned on to avoid trying to generate test results for data with no valid measurable sources.  
These address the error cases encountered in astrometry testing on 2020-07-24.
> Fix runastrodriz errors

- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/svm_quality_analysis.py
This set of changes resolves a couple of bugs identified during SVM testing; namely,
- only remove columns from astrometric catalog if specified columns are found in the table to start with
- only apply mask for 'pmra' column if 'pmra' column exists
These errors almost entirely affect use of EPOCH when obtaining the GAIA catalog from the web-service.
> Fix SVM GAIA catalog bugs

- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/quality_analysis.py
- drizzlepac/haputils/svm_quality_analysis.py
These changes address issues identified during DSB regression testing when using the QA code with the astrometry/pipeline processing.  This change only tries to generate QA results (JSON files) for input exposures that actually had identifiable sources useful for alignment, since the code now relies on the pipeline processing results for the inputs data for the QA results.
> Only try to generate QA JSONs for data with sources

- drizzlepac/haputils/pipeline_graphics.py
Interpretation of the JSON files can sometimes involve reading in data for images where there were no matching or cross-matched sources.  In those cases, the pipeline graphics code should simply skip over those exposures data to avoid throwing an Exception, which is what gets done in these changes to the plotting logic.
> Update pipeline graphics to only plot valid data

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
- Ensure the phot_mode variable is reset to its input setting for every total product
being processed.  The phot_mode can be modified during processing if one of the
source detection algorithms does not find any sources.
- Bubble up the stack the "no sources detected" warning for the segmentation algorithm
and return to the invoking algorithm.
> Fix logic for SVM with multiple detectors and possiblity of detection of no sources

- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/catalog_utils.py
SVM testing on 2020-08-13 revealed problems with dealing with blank images during alignment as noted in [Jira Ticket HLA-404](https://jira.stsci.edu/browse/HLA-404).  These changes address the issues identified with  single visit dataset 'ib2t06' by recognizing blank images before trying to interpret segmentation of the image in 'astrometric_utils' and 'catalog_utils'.  
This will close #767 when merged.
> Handle empty images in alignment

- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
The weight array gets used in this set of changes to modify how the point source catalog gets computed.  It uses it to define which regions have nearly the same S/N (WHT) within a factor of 1.5.  The relative weight across the WHT array (relative to the max WHT value) gets computed and used to scale each region before computing the RMS.  This accounts for the lower S/N in lower WHT regions that causes background noise fluctuations to be scaled up in DRZ products.  This allows the algorithm to account for regions where fewer inputs contribute to the final output image.  
**This needs to be discussed and reviewed thoroughly before being merged.**  Initial results processing IBWB01 indicate that it significantly improves the actual detection rate by minimizing the number of faint, scaled …
> Use WHT array to refine point catalog

- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/processing_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/runmultihap.py
This change adds the HAPLEVEL keyword value as an attribute of the HAPProduct class.  A new method, find_member, was also added to the Filter, Exposure, and SkyCell product classes as well to support use from within the 'refine_product_headers' function.  These changes allow 'refine_product_headers' to add the correct value of the HAPLEVEL keyword to each of the drizzle products which gets created.  
In addition, the 'runmultihap' interface was fixed to actually call the 'hapmultisequencer' module for correctly processing MVM data.  
This will close #786.
> Add HAPLEVEL as attribute to HAPProduct class

- CHANGELOG.rst
- drizzlepac/updatehdr.py
Fixes a crash in `TweakReg` when `updatehdr` was set to `False` because the code would attempt to archive the Primary WCS of a read-only file.
Fixes #800
> Fix crash in tweakreg when updatehdr is false

- drizzlepac/haputils/catalog_utils.py
Fixed typo which caused documentation of flag values in catalog headers to be displayed improperly (e.g., not displaying some values).  Added documentation for flag 128.
> Fixed display of flag values in catalog headers

- CHANGELOG.rst
- doc/source/runastrodriz.rst
- drizzlepac/adrizzle.py
- drizzlepac/astrodrizzle.help
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/runastrodriz.py
These fairly simple, and blunt, changes address problems that prevented `runastrodriz` from successfully executing to completion under Windows (the OS).  The changes are:
* insure that `num_cores` parameter value as set by the user gets passed to `astrodrizzle` when generating the a posteriori drizzle products 
* added `try...except` block around the deletion of the astrodrizzle log file in `run_driz`
* A note was added to the `runastrodriz` sphinx docs to suggest that users set `num_cores` to 1 when running under Windows due to problems with threaded logging (or, in fact, lack of any working logging when using multiprocessing as we have it implemented now in `astrodrizzle`). 
In addition, a few (PEP8) Flake8 syntax errors were also corrected.
> Update runastrodriz to work under Windows

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Simply update to the default value for the `nsigma` parameter in the catalog generation step from 5.0 to 7.5.
> Updated NSIGMA for source identification to 7.5

- drizzlepac/adrizzle.py
This changes how the code recognizes when it is being run under Windows or not to use a more consistent Python function that works the same across all OSs.
> Change how OS is recognized

- drizzlepac/haputils/catalog_utils.py
- See JIRA ticket [HLA-411](https://jira.stsci.edu/browse/HLA-411)
**High-level summary**
- The 2-d source detection threshold array used for identification of sources for the segment catalog is now weighted by the relative fractional input image contribution (i. e. \<number of input images\>/\<max number of input images\> for any given pixel). This minimizes  background fluctuations in regions of the drizzle-combined image where there is low S/N due to there being relatively few contributing input images.
- This PR applies the functionality of  PR #785 to segment catalog source identification.
**Changelog**
- catalog_utils.py:
- Moved creation of weight masks from HAPPointCatalog.identify_sources() (as local variable) to HAPCatalogBase.\_\_init\_\_() (as object attribute)
- Segment …
> Utilize the weight image in the catalog creation algorithms

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
If the background subtracted science minus Background2D image is found to have too many negative values, an alternative method of determining the background is employed.  The sigma-clipped-stats() method in Astropy is used to determine the mean, median, and std for an input science image.  The median is then used to generate a two-dimensional image with the single value of median.  The std is used to generate a corresponding two-dimensional rms image. This was done to mitigate the "zones of avoidance" - regions where the segmentation algorithm could not find any sources.  
The catalog configuration files were updated to contain additional configuration values used to determine when the alternative algorithm should be used, and how the sigma-clipped background is determined.
> Implement an alternative way to compute the background in support of Segmentation

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Reverts spacetelescope/drizzlepac#806.
Continued testing indicates this change to the NSIGMA parameter may be too aggressive in addressing over-population of the catalogs.
> Revert "Updated NSIGMA for source identification to 7.5"

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Re-organize and streamline the various background computation algorithms to provide a general resource for all source detection algorithms.  Move the majority of the existing code into the compute_background method of CatalogImage class, and clean up the residue in the HAP[Point | Segment]Catalog classes.  Updated the parameters files as necessary and appropriate.
> Re-organize/streamline background computation algorithms

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Changed or added where "del" is used in the compute_background image method for cleanup.  One of the del commands caused a bug when used in the mode of "simple_bkg=True".  Deleted some redundant code.
> Fix a bug introduced when cleaning up two-dimensional images

- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/graph_utils.py
- drizzlepac/haputils/poller_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/haputils/quality_analysis.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n6.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_any_n6.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_blue_n2.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_blue_n6.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n6.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n2.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n4.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n6.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n2.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n4.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n6.json
This PR implements the following changes to the SVM processing code:
- apply single-image cosmic-ray(CR) rejection by updating DQ arrays for sole exposure that defines a given FilterProduct 
- The algorithm is the same one used for alignment
- update single-image CR rejection algorithm to also identify most CR streaks (not delta CRs)
- update default parameters for astrodrizzle to NOT reset CR bits for single exposures or for the total detection image
- improve the memory use for the SkyFootprint algorithm
- fix a few more Flake8 syntax warnings/errors 
These changes were demonstrated to improve the total detection image, and the single image filter products using the data from the visit 'ib6w62'.
This will close #795 .
> Get single-image CR algorithm working

- drizzlepac/haputils/product.py
- drizzlepac/haputils/svm_quality_analysis.py
Some datasets end up causing 'tweakwcs' to throw an Exception when attempting to perform a fit to GAIA after doing a relative fit amongst the input images.  This update adds logic to trap that Exception from `tweakwcs.align__wcs`, resets the AlignmentTable instance by calling the `configure_fit` method, then tries another fit using the `default` to the reference catalog.  
This is still not guaranteed to work for all datasets, but for visit `ibjc44`, it results in a successful fit finally being applied.
In addition, a very minor fix was also included to update the GAIA catalog DS9 `.reg` file generated in debug mode by making the column header row a comment.
> Try another fit to GAIA if necessary

- drizzlepac/haputils/catalog_utils.py
Ensure the photometry routine has a value of 1.0 for the ACS/SBC gain to avoid values being set to nan and causing
all of the sources to be trimmed from the output catalogs.
> Set the gain to a value of 1.0 when processing ACS/SBC data

- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
These changes enable more control over how the code determines the FWHM and kernel from the PSFs actually found in the image being processed.  This includes:
- adds 'good_fwhm' range to the catalog generation config files as a controllable parameter
- increases the number of attempts to find a valid PSF by a factor of 10 
This was implemented to address problems with WFC3/IR data returning measured FWHM based on nearly saturated sources which apparently have a skewed PSF with a FWHM much greater than the actual PSF found for high S/N but non-saturated sources.   
This was tested using data from `icnw34` to return a FWHM closer to 1.1 instead of 3.45.
> Refine auto kernel

- drizzlepac/haputils/catalog_utils.py
Added the computation for the minimum allowable threshold based upon the readnoise, gain, number of images, and total exposure time.  This minimum only applies for the sigma_clipped_stats algorithm where a comparison is done between the rms computed by the sigma_clipped_stats and the minimum allowable threshold. Clean up with respect to images written in diagnostic mode.  Fixed a bug where a residual computation of the threshold had not been deleted.
> Add computation for the minimum allowable threshold 

- drizzlepac/hapsequencer.py
Insure that for the N=1 exposure times are defined for ALL detectors, even though it is not computed for IR or SBC data.
> Insure default value for n1 exptime

- drizzlepac/haputils/catalog_utils.py
A number of statements to write out intermediate products (for debugging and testing) needed to be removed.  In addition, logic needed to be added to accommodate the case when there are no sources after trimming to join with the total detection table.  
These changes fully address the errors encountered during testing on 2020-10-21 that exhibited the following Traceback messages:
`ib1f0b/HAP_ib1f0b.out-    sources.write(self.image.imgname.replace(drc, 'raw_sources.ecsv'), overwrite=True, format='ascii.ecsv')`
`ib1f0b/HAP_ib1f0b.out-AttributeError: 'NoneType' object has no attribute 'write'`
`j8ca07/HAP_j8ca07.out-    raise OSError(f"File {self.name!r} already exists.")`
`j8ca07/HAP_j8ca07.out-OSError: File 'hst_9029_07_acs_hrc_total_j8ca07_region1.fits' already exists.` …
> Removed debug code from catalog_utils

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
The input (hst* FLT/FLC) files were having the SCI array corrupted by the computation of saturation masks around sources in the image during image alignment for single image filter product inputs that had their cosmic-rays identified.  These changes prevent the corruption of the SCI arrays by insuring that the masking of saturated sources only occurs on copies of the inputs.
In addition, the docstring for the `_get_envvar_switch()` from hapsequencer was updated and the sigma_clipped_stats median was limited to 0 in source finding for image alignment.
> Fix saturation mask application to input files

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/quality_analysis.py
Changes were needed to correctly interpret the weight region masks (only median non-zero pixels) and to correctly treat any NaNs in the total image when creating the exclusion masks. 
These changes allow the point-catalog to detect sources again, as confirmed by testing with the data from visit `ibe809`.
> Fix problem defining masks for use in point catalog generation

- drizzlepac/haputils/catalog_utils.py
Erode the footprint_mask to avoid detection of sources along any boundary where the boundary is approximately 10 pixels deep.
> Erode the footprint mask to ensure false sources are not detected along any boundary

- drizzlepac/haputils/analyze.py
The error message generated by 'haputils.analyze' when no exposures meet the criteria for processing causes the pipeline to think there was a problem needing reprocessing.  This message has simply been reset to a warning instead so that the trailer file still records what processing was not done and why without causing problems for pipeline processing.
> Change analyze error to warning

- doc/source/catalog_generation.rst
- doc/source/runsinglehap.rst
- drizzlepac/haputils/photometry_tools.py
- drizzlepac/haputils/processing_utils.py
An initial draft of text describing the basic algorithm implemented to determine whether to reject the catalogs based on contributions from cosmic-rays.  This description includes the description of the single-image cosmic-ray rejection algorithm that is applied to the single image filter product exposures to partially mitigate the effects of cosmic-ray contamination in the total detection image.  
In addition, the API documentation for the runsinglehap interface was updated to include pointers to the current set of classes and functions in the primary SVM modules.  
Finally, a few small Flake8 (PEP8) corrections were included for some of the code being documented in the runsinglehap API docs.
> Initial draft of catalog rejection description

- drizzlepac/haputils/processing_utils.py
The value of the IPPPSSOO keyword in the header of the SVM exposure drizzle product now gets defined to remain as the original 'ipppssoot' value from the calibrated input (*flc.fits/*flt.fits file) exposure.  
This is a required change to insure that these products can be correctly managed by the archive.  This change was successfully tested using the SVM dataset `ib2t06`.
> Insure IPPPSSOO keyword has correct value

- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/poller_utils.py
The "pipeline" MVM poller file specifies the skycell for each entry in the file.  In actuality, every entry has the same skycell id in the file.  The poller utility supports input not only from a poller file, but also a list of filenames where the skycell ids are computed.  The output table from the poller utility when MVM and input comes from a poller file, needs to be trimmed to contain only the specified sky cells.
> MVM: output from poller utility should only contain specified sky cells when input from a "pipeline" poller file

- drizzlepac/haputils/processing_utils.py
- drizzlepac/haputils/product.py
A number of keywords need to be updated/added to the HAP input files when they are created as copies of the original calibrated pipeline (FLT/FLC) files.  These changes include:
- updating 'FILENAME' with the new HAP filename to replace the original 'ipppssoot'-based filename
- adding the 'IPPPSSOO' keyword to the primary header 
- updating the 'HAPEXPNAME' column in the HAP DRZ product HDRTAB table with the basename, not full filename.
These changes address the issues identified in try to define the correct release date for the HAP products.
> Populate HAP keywords in copied HAP input files

- drizzlepac/haputils/poller_utils.py
Replaced cell_utils.get_sky_cells call which does time-consuming and
memory-consuming discovery with more rudimentary functions given that for
poller file input the output sky cell is already defined.
> WIP: Too many resources are used even when and MVM poller file is used as input

- drizzlepac/haputils/catalog_utils.py
The hard-coded values for the FWHM search range in the build_kernel method of the CatalogImage class have been removed, and the values which are read from the detector-specific configuration files are used instead.  These values, as well as the default FWHM value used when no good candidate PSFs are found in the input image, are reported as log.info just before the call to build_auto_kernel.
> Remove hard-coded values for the "good" FWHM search range 

- drizzlepac/haputils/product.py
This simple change makes the MVM manifest name more generic, removing the layer label, so that one manifest file will be more appropriately named for the entire input MVM poller file.  
This will partially address [HLA-455](https://jira.stsci.edu/browse/HLA-455).
> Revise MVM manifest name to be more generic

- CHANGELOG.rst
- drizzlepac/acsData.py
- drizzlepac/imageObject.py
- drizzlepac/nicmosData.py
- drizzlepac/processInput.py
- drizzlepac/stisData.py
- drizzlepac/wfc3Data.py
- drizzlepac/wfpc2Data.py
These changes implement a new naming convention for the common static mask file that gets used by `astrodrizzle.AstroDrizzle()`.  The new name is based on the original input provided to astrodrizzle, and if it is ASN file, the filename defined in the ASN file as the 'output' product.  This results in a dataset unique name for the static mask based on the original input file which will not be confused with the static mask for any other dataset being processed in the same directory.
> Rename static mask

- drizzlepac/hapmultisequencer.py
The manifest file also needed to include the renamed input FLT files since they contain updated WCS headers.  This change follows what was done for the SVM processing to add these filenames to the MVM manifest file.
> Add renamed input files to MVM manifest file

- drizzlepac/imageObject.py
Renaming the static mask file needed to be done in a more generic manner, not specifically tailored to pipeline IPPPSSOOT filenames.  This small change insures that the whole specified output filename gets used instead of just the first portion.
> Create more specific static mask name

- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/poller_utils.py
- drizzlepac/haputils/product.py
This change to the SkyCell API removes the overloaded set of input parameters in favor of using a decorator classmethod.
> Revise SkyCell API

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
The "big island" message which can be generated for the output catalog documentation section only applies for the segmentation algorithm.  The "if" statements were re-arranged.
Modified the join of specified filter columns to be added to the total catalog.  It is now a "left"
join (versus "inner") which means, in this case, the in-memory "total table" is always populated at this stage in the code.  If this table is empty, the algorithm has exited previously.   This change triggered unexpected behavior when generating the total Point catalog in that the RA and Dec columns were not necessarily totally populated as they were previously constructed from the filter in-memory tables.  Modified construction of Point total catalog with respect to the RA and Dec columns to ensure these columns are …
> Fixed two bugs during SVM testing: attribute not part of a class and error in joining tables

- drizzlepac/devutils/alignment_viewer.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
These changes revise the computation of the background and how it gets used for determining the sources in the segment catalog.  The changes include:
- using the -1 * RMS of the background as the negative threshold
- removing the 'negative_threshold' parameter from the config files
- updated computation of sigma-clipped background to be less influenced by bright sources 
- revising the Background2D parameters for the WFC3/IR format (smaller box size)
- reduced the source box size for the segment catalog sources for all detectors to pick up smaller/fainter sources
- eliminate background subtraction prior to calling photutils segmentation code (avoids applying the background twice)
These changes were tested using dataset 'ia0m04' (hst_11099_04, WFC3/IR).  Original HAP segment catalog had …
> Fix segment background determination and use

- drizzlepac/haputils/analyze.py
This change will check to see whether the DRIZCORR header keyword has been set to "OMIT" or "SKIPPED" and reject SVM processing for those images.  This will avoid problems with incomplete or problematic IDCTAB use with the images which would cause an Exception to the thrown.
> Add DRIZCORR as rejection criteria

- CHANGELOG.rst
- drizzlepac/tweakback.py
From the work on helpdesk issue INC0164467 it became clear that tweakback is ignoring updated WCS's name provided by `wcsname` parameter. This PR fixes this CRITICAL (IMO) bug.
In most situations _this will go unnoticed_ but in some situations, for example when drizzled image contains remnants of the OPUS WCS as described in https://github.com/spacetelescope/drizzlepac/issues/863 this will cause a crash. This (going unnoticed) makes fixing that issue even more important. CC: @stsci-hack @nden
> Fix a bug in tweakback due to which updated WCS's name is ignored

- JenkinsfileRT
- azure-templates.yml
- setup.py
The next release of astropy will not support Python 3.6. This PR changes the min Python version to
` >= 3.7`. 
Changing the version will help also with running the regression tests with dev dependencies.
Is there a reason not to update?
This is in support of AL-453.
> update version of python to >=3.7

- JenkinsfileRT
- drizzlepac/updatehdr.py
- tests/hap/test_align.py
This PR allows the tests in `test_align.py` to run so comparison with `truth` results can be done.
With this the Jenkins tests are now running and failing with trivial differences. The truth files need to be updated.
> fix align test, update Jenkins job title

- drizzlepac/haputils/processing_utils.py
This makes the logic consistent for all HAP Drizzle products when updating the HDRTAB extension so that the HAPEXPNAME column contains the product_basename, not full filename, as the value. 
These changes were tested by processing visit 'hst_11603_06' (ib2t06).  
This addresses HLA-483 and the related issue #925 .
> Fix HAPEXPNAME in HDRTAB for EXP HAP Products

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
The detect, deblend,  and kernel (Gaussian vs RickerWavelet) switching steps were re-organized to make better sense.  This relieves a majority of the issues (as well as any updates done by other folks with regard to the background determination) which caused deblending to take so long.
> Address problem of the deblend step taking too long

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/analyze.py
- drizzlepac/haputils/poller_utils.py
- drizzlepac/haputils/product.py
Accommodate processing Grism/Prism images in the form of the SVM hst*[flt/flc].fits) at least to the stage where the Grism/Prism SVM image and the direct SVM images have a common active WCS.
> Set a common active WCS for direct as well as corresponding Grism/Prism images

- tests/hap/test_align.py
- tests/hap/test_apriori.py
Two Pytests were modified by adding XFAIL to allow a a release candidate to build.  This change is meant to be a fix to the 3.2x branch and tagged as 3.2.1.
> Added xfail to two tests to force a release candidate build.  

- drizzlepac/hapsequencer.py
Fix to ensure the literal 'None' and the name of the 'metawcs all ref catalog' strings are not in the manifest.  In addition the
'metawcs fall ref catalog' file should be deleted from disk.  The disk clean up may have already happened, but this is to ensure it is done and is encapsulated in a try/except.
> Clean up manifest file and disk as necessary

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/poller_utils.py
Keep track of the WCS solutions which are defined in FITS keywords, not headerlets, in a dictionary to associate the solutions property with its image.  Since a Grism/Prism image my be acquired with another filter (ACS only) yielding a "filter" name in the processing code as g800l_f814w, for example, make sure to check the entire filter string for 'g' or 'pr' for Grism/Prism images.
> Store FITS keyword WCS solutions as a dictionary for use in multiple routines

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/poller_utils.py
If a visit only contains Grism or Prism data and no direct images, for example, there is no reason to process the visit.  When Grism/Prism and direct exposures are present, it is desired for all of the images in the visit from the same detector to have the same WCS.
> Handle situation of no viable Total Data Products in the visit

- CHANGELOG.rst
- drizzlepac/outputimage.py
These changes insure that all simple FITS files written out by astrodrizzle no longer have the `EXTNAME` and `EXTVER` keywords in the simple FITS drizzle product headers.  Instead, the `FILETYPE` keyword has been added to document the type of data in the file (SCI, WHT, CTX).  
This avoids the problems reported in #590 .  
In addition, 
- all Flake8 errors in the 'outputimage.py' module have been resolved.
- leftover WCS distortion keywords are finally cleaned up properly
Fixes https://github.com/spacetelescope/drizzlepac/issues/862, #590
> Fix EXTNAME/EXTVER in simple FITS files

- drizzlepac/haputils/catalog_utils.py
Surrounded the creation of some output files used for diagnosticpurposes only with "if self.diagnostic_mode" so they do not get created during standard processing.
> Ensure diagnostic files do not get created during standard processing

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/processing_utils.py
A new function has been added to `hapsequencer` to insure that all SCI extensions of all science images have valid, non-empty HDRNAME keyword values.  Invalid values can cause problems with using the headerlet functions in STWCS.  
A couple of small Flake8 fixes were also added.
> Insure HDRNAME is always valid

- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/deconvolve_utils.py
The use of the FWHM determination by the library PSF use for point-catalog generation now includes proper catches for invalid values returned by photutils.  In addition, other error cases where the code did not correctly catch empty lists for point-catalogs based on the library PSF were also addressed by the changes in the PR.  
The additional check for CR map used during alignment also needed to be added for cases where no updates are returned when alignment sources are identified.  Should be tested against dataset j8dnd5.
These changes were tested against datasets ib1319, ibbso1, ia1s70 and jcol11.
> Add more error cases for FWHM use

- drizzlepac/haputils/deconvolve_utils.py
Testing uncovered bugs in the point-catalog generation code related to limiting the size of the PSF measured for FWHM, and these changes correct those problems.
> Fix bugs in point-catalog generation

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/processing_utils.py
When the update to the drizzle products for CAOM compatibility fails, the FITS headers of the files may not be modified to contain all the proper information in the proper header for successful processing.  In particular the PHOT keywords for the WFC3/IR are found in the Primary and must be copied to the SCI extensions which is where these keywords are found for all of the other instruments.  
Added a stopgap routine which will search the Primary header, as well as one other specified header (extname, extver) to search for a floating-point keyword.  This is only a stopgap as generic template should be created to handle multiple datatypes.
> Ensure the PHOT keywords can be found in the SVM product header

- drizzlepac/hapsequencer.py
Computation of the CR threshold used to decide whether the catalogs are valid based on expected numbers of cosmic-rays turned out to have been provided the incorrect exposure time of N=1 exposures.  These changes correct the logic for computing the correct exposure time to be used in the threshold.
> Correct computation of CR threshold factor

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
If "diagnostic mode" is True, all diagnostic files (particularly the *.reg)
are written regardless of the setting of "reject_catalogs.  If
"reject_catalogs" is True, the output catalog files (*.ecsv) are not
written.
> Fixed the logic with regard to "reject_catalogs" and "diagnostic mode".

- drizzlepac/haputils/svm_quality_analysis.py
The dataset `ibtq25` results in some products not being generated during processing, and the SVM QA checks did not recognize the missing products when they tried to run.  These changes add logic to guard against missing inputs for the comparisons, and was tested on `ibtq25`.
> Fix svm qa logic

- drizzlepac/haputils/svm_quality_analysis.py
- setup.py
Ensure a column is reset to its original name ("RA") from the temporary name ("#RA") needed for use with ds9 (only when SVM_QUALITY_TESTING is set and logging is "debug" mode).
> Reset a column to its original name "RA" from the temporary name of "#RA"

- drizzlepac/haputils/cell_utils.py
- setup.py
These changes update how corners are detected for the footprints of datasets when defining the S_REGION keyword value.  It turned out that for some datasets where only 1 image contributed to the footprint, that the corners could not be identified by the 'corner_harris' algorithm due to (basically) too low S/N.  This simple change insures that the maximum S/N is roughly 100.  This was tested on datasets `ibeveo` to show that it correctly identified all the corners for all the products, despite the some of the IR footprints only having 1 exposure. 
Addresses HLA-514.
> Make corner detection more robust

- drizzlepac/devutils/sourcelist_generation.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/deconvolve_utils.py
- drizzlepac/haputils/photometry_tools.py
- drizzlepac/haputils/se_source_generation.py
- drizzlepac/haputils/svm_quality_analysis.py
I expanded this PR beyond fixing only the `NoDetectionsWarning` import to all `photutils` imports and references in docstrings.  These changes work for all drizzlepac-supported versions (>=0.7) of `photutils`.  I will put in a separate PR of updates specifically for `photutils 1.1.0` enhancements.
I noticed that several private functions from the `photutils.detection` subpackage are being imported here. The private functions are not intended to be used outside of `photutils` and of course are subject to change (e.g., API changes) or removed completely due to refactoring.  I don't plan to change those functions in the near-term, but I do want to refactor `photutils.detection` at some point.  If API stability is critical, then you may want to package those current functions with …
> Fix all photutils imports

- CHANGELOG.rst
- drizzlepac/sky.py
Some datasets triggered Exceptions during sky subtraction when using the 'match' option due to exactly overlapping input images and problems with the spherical geometry package.  This simple update adds a check for problems with the sky computation and if an AssertionError is raised (as happens when the spherical geometry error is triggered), it will simply try again with a simpler SkyMatch option that does not rely on spherical geometry to work.  
A verifiable test case still needs to be identified for testing of this change before it can be merged.
> Iterate over SkyMatch options

- drizzlepac/haputils/svm_quality_analysis.py
This PR replaces all instances of the deprecated function 'stwcs.altwcs.archiveWCS' with the new version 'stwcs.altwcs.archive_wcs'.  The change corrects a problem with WCSNAMEs being set to blank when running 'svm_quality_analysis.report_wcs' leading to direct images in Grism/Prism datasets to having no WCSNAME.  
The original problem was reproduced using dataset 'ib3a03', which was then used to verify that this change corrected the problem.
> Replaced deprecated STWCS calls

- drizzlepac/runastrodriz.py
Some headerlets from the astrometry database are not entirely complete, lacking at least the IDCSCALE keyword.  These changes look for that keyword when applying an `a priori` WCS solution from the database, and when it is missing, it gets added to the SCI header.  
Association j900a5010 headerlet with hdrname = 'j900a5agq_flt_IDC_0461802ej' does not contain the 'IDCSCALE' keyword and triggered an Exception during standard processing.  This PR resolves the problems and allows this dataset, jdgq05020, and others like it to process successfully.
> Insure IDCSCALE always exists

- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/product.py
Astrometric catalog names will no longer be treated as case-sensitive with these changes.  This makes it more robust when users specify what they think is the catalog name (GAIAedr3, for example) when the the list of "SUPPORTED_CATALOGS" for translation may have it differently (GAIAeDR3, for example) causing the translation to fail and the rest of the code to throw an Exception and not align to that catalog even though it is the right catalog.  
In addition, logging is cleaned up a bit with logging levels explicitly set when calling some user-callable functions from 'haputils/astrometric_utils'.  This should only result in a little more information being included in the log file, primarily when run in 'debug' mode. Additional changes can be done in separate PRs to insure that those log …
> Fix support of astrometric catalog names

- drizzlepac/align.py
- drizzlepac/haputils/product.py
These changes connect the varying limits for the fit based on the 'fitgeom' used for the fit to the code used in 'determine_fit_quality' for the 'min_xmatches' check.  This allows both the pipeline processing and SVM/MVM processing to use their own limits defined in the JSON config files.  
The limit for the max_fit_limit is also pulled from the config files in these changes as well.  
This allows dataset 'ic0s17' to end up with a 'shift' fit to GAIAeDR3 with 2 matches rather than ending up with a fit based on GSC242.
> Apply limits on cross-matches to fit quality

- drizzlepac/haputils/catalog_utils.py
The background used for point-source detection based on PSFs has been revised to use the full detection threshold (bkg + nsigma*rms) instead of just the background by itself.  This will resolve the most egregious cases where peaks in the background get picked up as 'real' sources as noted by INS for 'id7h42' and 'ica9t3'.
> Adjust threshold for point-catalog generation

- drizzlepac/haputils/align_utils.py
Applying a headerlet from an extension will cause these keywords to be overwritten with the values from the headerlet, which will most likely not be the current versions in use.  These simple changes insure that all a posteriori WCS headerlets created during pipeline processing, along with the FLT/FLC image primary header, get updated with the version of STWCS and Astropy actually used to create the new WCS.  Since this change affects code used by both pipeline processing and SVM/MVM processing, we are insuring all future processing will report the correct versions used to create the WCS in use.
> Insure correct versions get reported for WCS

- drizzlepac/haputils/product.py
Clarified message issued when a downgrade in the fit geometry is done.  The message was fixed to ensure the correct fit geometry name is issued.
> Clarified message issued when a downgrade in the fit geometry is done.

- drizzlepac/haputils/product.py
This restores the logic to avoid trying to perform a relative fit when there is only 1 exposure to align, as some visits only contain a single exposure (ibe809 and idcm13 for example).
> Add logic to avoid relative fit with singletons

- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
These adjustments to the parameters used for alignment allow data which was previously unable to be aligned or aligned correctly to actually get aligned to GAIA.  These changes were demonstrated to work for 'ibe809' which ended up having an offset of (236, -347) pixels or 16.6 arcseconds.  In addition, the 2dhist fitting option was restored for mosaic_fitting use since it relies on a very different algorithm from the default fitting for cross-matching and determination of the offset providing complimentary techniques for trying to align single exposures to GAIA.  In fact, the 2dhist option was the only way to align 'ibe809'.
> Update default fit pars

- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
After updating the SVM processing with a new set of catalogs, this updates the options for alignment in standard pipeline processing of ASNs and singletons to be consistent.
> Update defaults for pipeline catalog use

- drizzlepac/align.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/product.py
These changes identify and flag as 'FAILED' any relative alignment solution (performed using `align_utils\match_relative_fit`) where any member exhibits a wildly different rotation.  This typically results from a nearly singular solution with very few (2 or 3) matches or from incorrect cross-matching. 
By setting the `meta["fit_info"]["status"}` to 'FAILED' for all members in the fit, that fit solution will be thrown out and the rest of the code will try the next possible solution.  This logic has only been added to the relative fit solution, since there is an expectation that any corrections will be relatively small in rotation at least.  
These changes were tested using 'ibvg03' under Windows which only uses float64 as long, instead of float128 used under Linux, resulting in a near …
> Skip inconsistent fits during relative alignment

- drizzlepac/astrodrizzle.help
Currently example of `astrodrizzle` call shows WCSNAME used for `wcskey`. This PR corrects the example.
> Correct astrodrizzle example use of the wcskey

- drizzlepac/runastrodriz.py
The IDCTAB in the FLT/FLC files have reverted to older IDCTABs in the archive.  This implements support for a new environment variable, **PIPELINE_RESET_IDCTAB**, to enable this new function, `reset_idctab_kw`,  to sync the IDCTABs (and corresponding PRIMARY WCS) in the FLT/FLC files with the newest IDCTAB specified in the RAW file header.
> Insure IDCTAB is current in FLT files

- CHANGELOG.rst
- src/cdrizzleblot.c
A port of a fix for a bug originally discovered in the `drizzle` - see https://github.com/spacetelescope/drizzle/pull/66
> Fix memory corruption in the linear blot algorithm

- drizzlepac/haputils/cell_utils.py
This PR adds a new attribute to the SkyFootprint class, bounded_wcs, which represents the WCS of just the section of the SkyCell where the footprint has HST data.  This attribute gets automatically computed upon completion of the '.build()' method, although the method could be called again separately if needed. 
In addition, during testing, it was discovered that the similarity computations have been broken for a few months.  This PR includes a fix for this long-standing bug as well so that that similarity check now gets performed as designed.
> Define bounded WCS for SkyCell footprint

- drizzlepac/haputils/cell_utils.py
One of the primary limitations for processing MVM datasets has been the memory requirements for the SkyFootprint class.  These changes reduce the memory use for that class to a single np.int16 array for the total_mask and, when requested, a single np.float32 array for the exposure time scaled total_mask.  These arrays are the size of the final output frame, which for MVM processing is the full size of a SkyCell or 21418 x 21418 pixels.  This memory usage does not go up noticeably with the number of input exposures, unlike the original implementation.  
One of the major benefits of this PR is that the **runtime was also dramatically sped up** now taking only about 1second per input image, **about 10X faster**, give or take.
The **'get_sky_cells' function was also fixed** to work correctly …
> Minimize memory usage of SkyFootprint

- drizzlepac/haputils/cell_utils.py
The expnames are now correctly parsed from a file as input to 'get_sky_cells' with these changes.
> Fix list input parsing for get_sky_cells

- drizzlepac/outputimage.py
Corrected the problem of "long string" values being abbreviated in the FITS header.  These strings were abbreviated in old drizzlepac source code and not by the FITS writer.  Note: Now that the full string can be written according to the standard, the associated comment can be abbreviated.
> Fixed abbreviated "long string" values in the FITS header

- drizzlepac/haputils/cell_utils.py
The SkyFootprint class attribute, self.footprint_member, needed to be initialized in the constructor in order to avoid errors being raised elsewhere in the code when checking for its value.  This bug was noticed during testing, and also seen when generating the fix which became PR#1057.    This PR was generated in order to avoid code smuggling.
This fix is short, sweet, and oh so petite.
> Initialize the SkyFootprint attribute, self.footprint_member

- drizzlepac/hapmultisequencer.py
Changed the way the skycell filenames are collected in order to generate the Rules file list.  Modified the code from using glob to collecting the filenames from the exposure object attribute as is done for SVM processing.
> Fixed the clean up of the Rules files

- src/arrdrizmodule.c
Building a whl for drizzlepac produces the following warning:
> src/arrdrizmodule.c:790:10: warning: unused variable 'val' [-Wunused-variable]
double val;
^
1 warning generated.
This PR removes the spurious variable and quiets the warning.
> Remove unused variable `var`

- drizzlepac/haputils/cell_utils.py
These changes insure that the indices used for the SkyCell ID are always between 1 and 21 (or whatever sc_nxy was defined to be in the pars/allsky_cells.fits table).  The logic prevents negative skycell indices from being tried or used as well.  
The data from `idix03` which overlapped skycells p1894 and p1974 was used to confirm that the negative Y index was corrected.
> Fix indexing of SkyCell IDs

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Restructured code to allow for modest recomputation with regard to identifying
segments with the custom/Gaussian or RickerWavelet kernel.  If the segmentation
image is found to have big islands or a large source fraction after both
kernels have been tried, the algorithm allows for a recomputation of the background
image (sigma-clipped to Background2D) or raising the threshold for detection if the
Background2D is already in use.  Pending: last ditch thresholds on big islands and/or
source fraction which allow segmentation processing to continue as the deblending
should statistically not take days and days (based upon test results).  I still
need to analyze the stats to determine these thresholds.
Reset some configuration variables, keep track of the background determination
type …
> WIP: Address unreasonable deblending times for segments 

- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/product.py
Fixed the construction of the manifest filename for MVM processing.  The manifest name is now of the form hst_skycell-p<PPPP>x<XX>y<YY>_manifest.txt.   The name is solely dependent upon the skycell name which should make it predictable for the operations software.
> Fix the construction of the manifest filename for MVM processing

- drizzlepac/haputils/astroquery_utils.py
Clarify documentation for 'haputils/astroquery_utils/retrieve_observation' to make it more obvious how to use the function to retrieve all data associated with a visit.
> Update docs for aqutils

- drizzlepac/haputils/cell_utils.py
Fixed the code in cell_utils.py which was generating a FutureWarning of "Using a non-tuple sequence for multidimensional indexing is deprecated. Use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.".  Fixing this issue eliminates unnecessary clutter in the output trailer files.
> Fix the code in cell_utils.py which is generating a FutureWarning

- drizzlepac/haputils/poller_utils.py
- drizzlepac/haputils/product.py
The interpretation of the MVM poller file would not work when exposures from multiple instruments were included.  The poller file now correctly associates the right instrument with each exposure when reading the MVM poller file.  In addition, the information from the poller files have been interpreted to generate the latest convention for the MVM exposure files, by eliminating extra 'all' terms and the 'fine' pscale term from the layer string.
These changes were tested using the 24 exposures that overlap hst_skycell_p1637x16y01.
> Fix MVM poller

- drizzlepac/align.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
These changes allow some single source images to be aligned to GAIA, if the single source cross-matches with GAIA.   The primary revisions are:
- reset minimum number of cross-matches for 'shift' alignment, and ONLY 'shift' alignment, to 1 from 2
- turn off clipping in 'tweakwcs' for 'shift' mode since we are already working with so few sources
These changes allowed the images taken for 'jdzn04' of a photometric calibration source to be aligned to GAIA with 1 cross-match.  This will still not help images where the sources are completely saturated.
> Reset parameters for shift alignment

- tests/acs/test_acs_kernels.py
- tests/acs/test_acs_narrowband.py
- tests/acs/test_acs_tweak.py
- tests/acs/test_asn_regress.py
- tests/acs/test_unit.py
- tests/hap/test_align.py
- tests/hap/test_alignpipe_randomlist.py
- tests/hap/test_apriori.py
- tests/hap/test_pipeline.py
- tests/hap/test_randomlist.py
- tests/stis/test_stis.py
- tests/wfc3/test_vary_perf.py
- tests/wfc3/test_wfc3.py
- tests/wfpc2/test_wfpc2.py
Pytest skip drizzlepac tests due to mismatch between code version and artifactory truth files.
> Skip drizzlepac PyTests for HSTDP-2021.3.3. Build

- drizzlepac/hapsequencer.py
Fix to handle a dataset where no images are viable for processing so
no total objects are created.  As a result, the manifest name cannot
be generated in the standard way and upon exit, the process ends on
an error. Addressed the situation so the process ends in a tidy manner.
> Fix to handle an undefined manifest filename

- drizzlepac/runastrodriz.py
This corrects the problem with trying to update the DRIZPARS keyword in an empty DRZ file or one for which AstroDrizzle did not create a DRZ product at all.  
The problem was identified with dataset 'ib8c5k'.
> Only apply DRIZPARS when returned by tweakwcs

- drizzlepac/haputils/align_utils.py
This fixes the problem where a log message was trying to be written out using a field that 'tweakwcs' did not create for an image (reference image?).  
Found using dataset 'ibcd61'.
> Fix fitgeom use in log msg

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/analyze.py
Fixed the bug to access the dataset filenames properly if all Grism/Prism
datasets need to be deleted from the processing.  Also, fixed an unreported
algorithmic bug causing the ibbr01 to not produce output.  Two of the
Grism/Prism data files actually had an exposure time of zero.  The
Grism/Prism data is minimally processed in order to have the same
WCS as the corresponding direct images. STWCS found the images had
zero exposure time, so the images had only an OPUS WCS. This
caused the processing to fail as there was no preferred 'a priori'
WCS available for all the images to use.
> Fixed bug to access the dataset filenames properly AND remove zero exposure images from processing

- drizzlepac/hapmultisequencer.py
These changes should result in drizzled versions of the MVM input FLC files to be produced as output products of MVM processing.
> Create Drizzled MVM FLC files

- drizzlepac/haputils/cell_utils.py
Modification to skip any image/chip in the MVM visit list which does not really overlap with the skycell footprint so the data is not included in the processing and cause a failure.
> MVM: Skip any image/chip in the MVM visit list with no skycell overlap

- drizzlepac/haputils/make_poller_files.py
This additional logic allows the creation of MVM poller files when the input files are already in the current working directory without having to specify an external environment variable. 
This change is NOT critical to any pipeline functionality, but rather allows poller files to be generated for local use; primarily, for testing.
> Allow local files in poller files

- drizzlepac/haputils/product.py
Simple change to update the value of the HAPLEVEL keyword for MVM products (not exposure level MVM products) to a value of 4, from 3.
> Update HAPLEVEL for MVM products

- drizzlepac/haputils/product.py
As requested by INS, this turns off the creation of CTX extensions for MVM products.
> Turn off CTX creation for MVM products

- drizzlepac/buildmask.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/imgclasses.py
- drizzlepac/processInput.py
- drizzlepac/resetbits.py
- drizzlepac/sky.py
- setup.py
This PR effectively undoes https://github.com/spacetelescope/drizzlepac/pull/1098 in light of https://github.com/spacetelescope/stsci.tools/pull/135#issuecomment-896792533: `numpy 1.21` compatibility can be improved in `stsci.tools.bitmask` before next `astropy` release.
> Keep using stsci.tools.bitmask for compatibility with numpy 1.21

- drizzlepac/adrizzle.py
- drizzlepac/catalogs.py
- drizzlepac/devutils/alignment_viewer.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/hla_flag_filter.py
- drizzlepac/haputils/hla_flag_filter_HLAClassic.py
- drizzlepac/imgclasses.py
- drizzlepac/minmed.py
- drizzlepac/stisData.py
- drizzlepac/tweakreg.py
- drizzlepac/tweakutils.py
This replaces the deprecated `numpy` global types
```python
np.float
np.bool
np.int
```
with the Python types
```python
float
bool
int
```
to avoid (reduce) deprecation warnings.
> Use intrinsic int, bool, and float types instead of numpy

- drizzlepac/haputils/testutils.py
Fix how the compare_wcs function works so that the hap/test_apriori tests will run correctly.
> Fix hap apriori pytest

- CHANGELOG.rst
- drizzlepac/adrizzle.py
- drizzlepac/drizCR.py
- drizzlepac/processInput.py
- drizzlepac/util.py
This PR fixes compatibility issues in `Python >= 3.8` when running `astrodrizzle` in parallel mode.
From [Python 3.8 Documentation](https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods):
> Changed in version 3.8: On macOS, the spawn start method is now the default. The fork start method should be considered unsafe as it can lead to crashes of the subprocess. See bpo-33725.
In order to pass open `HDULists` (or other complicated objects) to subprocesses, we have to continue using `'fork'` for now.
In the future, it may be worth exploring switching to `'spawn'` or `'forkserver'` which may improve security and possibly add support for multiprocessing when running on Windows.
Fixes #1068
> Fix multiprocessing incompatibility with Python >= 3.8

- drizzlepac/hapmultisequencer.py
- drizzlepac/hapsequencer.py
- drizzlepac/haputils/processing_utils.py
Update SVM and MVM processing code to support input filenames with any extension, as opposed to throwing an Exception if the filename did not end in '.out'.
> Support general input poller file name

- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/processing_utils.py
- drizzlepac/haputils/product.py
The S_REGION keyword computation has been simplified and generalized to not only work for pipeline and SVM products, but also for MVM products.  
The simplification comes from correctly implementing use of the Harris corner detection algorithm (from skimage) to detect the corners in the mask of SCI array while removing the computation based on each input to the output product.  This allows the code to work on images where chips extend beyond the bounds of the output image, as is the case with MVM products.  
The output value of the S_REGION keyword also now separates each region with it's own POLYGON ICRS tag, leading to multiple POLYGON sets of coordinates in the keyword value.  
In addition, a new method was added to the SkyFootprint class to enable creation of a footprint mask directly …
> Compute mvm sregion

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
Ensure the segmentation image is not None upon return from detect_and_eval_segments()and handle the situation appropriately though additional logic.  Added informational log messages regarding lack of sources found and catalog status. Protect against divide by zero when computing the ratio of "Gaussian big islands" vs "RW big islands".
> SVM: Handle multiple total data products (TDP) when first TDP processed has no sources

- drizzlepac/haputils/astrometric_utils.py
Replace reference to 'source_properties' with name used on import; namely, SourceCatalog.  This will avoid throwing an Exception when using photutils < 1.1.0 while keeping the 1.1.0 syntax backwards-compatible.
> Remove reference to source_properties

- pyproject.toml
The build is currently failing because `setup.py` imports `numpy`, meaning that `numpy` must be installed and available before setuptools is run. `pyproject.toml`, and [PEP517](https://www.python.org/dev/peps/pep-0517/)/[PEP518](https://www.python.org/dev/peps/pep-0518/) more generally, is intended to allow users to specify build requirements such as these, when they're necessary to run `setup.py`. However, at the moment we are not using the PEP517 build process, due to [logic in the spacetelescope/action-publish_to_pypi](https://github.com/spacetelescope/action-publish_to_pypi/blob/master/entrypoint.sh#L67-L78) GitHub Action we're using. The end result is that the build dependencies specified in the `requires` key of the `pyproject.toml` are not installed automatically, including …
> Add build-backend to pyproject.toml, to force PEP517 build

- pyproject.toml
Co-authored-by: Zane.Geiger <zgeiger@stsci.edu>
> Add build-backend to pyproject.toml, to force PEP517 build (#1121)

- pyproject.toml
Reverts requirement in pyproject.toml to use current numpy.
> Revert to using current numpy only for build

- drizzlepac/devutils/search_skyframes.py
- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/make_poller_files.py
- drizzlepac/haputils/poller_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/haputils/which_skycell.py
- drizzlepac/make_custom_mosaic.py
**Related JIRA Ticket**
- [HLA-598](https://jira.stsci.edu/browse/HLA-598)
**High-level Summary**
- Modified MVM pipeline code so that it can process both non-pipeline-processed flc/flt fits files (as it did previously) and SVM pipeline-processed flc/flt fits files as well. This gives the MVM pipeline the ability to utilize the WCS solutions that were previously derived by the SVM pipeline.   The vast majority of the changes were to account for the differences in the filename formatting between the SVM pipeline-processed  and the non-SVM pipeline-processed input flc/flt fits files. 
**Additional Code Additions**
- Added new script which_skycell.py. This script is basically just a command-line interface for cell_utils.get_sky_cells() and as the name of the script suggests, allows users to …
> MVM: Insure SVM-derived WCS gets used as input to MVM processing

- drizzlepac/haputils/which_skycell.py
This is just a simple one-line bugfix. which_skycell.py had an incorrectly set argument that I didn't catch before merging PR #1125.
> which_skycell.py simple bugfix

- drizzlepac/haputils/_detection_utils.py
- drizzlepac/haputils/deconvolve_utils.py
This PR will remove once and for all the current dependence on `photutils` private functions.  I'm planning to refactor some of these private functions in `photutils` to allow the addition of new features (prompted by https://github.com/astropy/photutils/pull/1231).  Moving the current versions of the private functions here will prevent `drizzlepac` from breaking after these private functions are changed in `photutils`.  I don't want to break `drizzlepac`.
This would need to go in the 3.3.0 release, otherwise I'm stuck in `photutils` without breaking `drizzlepac`.
> Remove dependence on photutils private functions

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/product.py
These changes insure that empty catalog files get written to disk when no sources are identified in either/both of the segment or point-source catalogs.  The changes also includes updates to the logic for rejecting both the point and source catalogs based on the HLA's algorithm implemented here in the 'verify_crthresh()' function so that if the catalogs are rejected, it simply deletes all the rows when writing them out.  This insures that catalogs ALWAYS get generated, even if empty. 
It was tested on data from 'ib2t06' and 'id7r03' (a case where sources were found).
> Generate empty source catalogs

- drizzlepac/haputils/analyze.py
Added a new function, mvm_analyze_wrapper, which uses the functionality in the underlying
analyze_data routine to examine FITS keywords and determine the viability of the data to
be used in the MVM processing.  The mvm_analyze_wrapper works on a single image at a time.
Added an optional parameter to analyze_data so the routine can determine when MVM processing
is wanted as MVM processing does not allow anything to be done for GRISM/PRISM images.
Updated doc strings.
> Function mvm_analyze_wrapper determines the viability of an image for MVM processing

- drizzlepac/hapmultisequencer.py
- drizzlepac/make_custom_mosaic.py
- drizzlepac/runmultihap.py
**Relevant Ticket:**
- [HLA-617](https://jira.stsci.edu/browse/HLA-617)
**Summary of Changes:**
- hapmultisequencer.py: 
- added logic to run_mvm_processing() to optionally skip execution of run_align_to_gaia().
- Added new optional subroutine input 'skip_gaia_alignment' in run_mvm_processing() to control the new feature.
- runmultihap.py: added new optional command-line switch to allow users to skip gaia alignment of input images
- make_custom_mosaic.py: updated code to support new "skip_gaia_alignment" functionality in hapmultisequencer.
> MVM: Make alignment to GAIA optional

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/astroquery_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
These changes update the logic used for fitting to an astrometric catalog to limit when minobj < 4 to only those cases where only 4 or less sources are identified in the input images to start with.  This eliminates cases when too many sources in the input image are identified and a fit to 'shift' only (nmatches=1) results in mis-identified cross-matched sources leading to errors being introduced in the relative alignment of the images.  The goal of this PR is to only allow "fitting to GAIA" when the chance of confusion and mistakes in cross-identification are minimized in order to preserve relative alignment.
> Minimize use of fitting for shift only

- drizzlepac/haputils/catalog_utils.py
Added the FWHM measurement to the output Segmentation filter catalog. The FWHM measurement
only exists in versions of Photutils > 1.1.0.  The code accommodates older versions of
Photutils by including the FWHM column in the output Segmentation catalog, but the entire
column is zero-filled.
> Add FWHM measurement to the output Segmentation filter catalogs

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Added the Kron radius as an output measurement for the catalog.  This change required providing
"kron_params" to the SourceCatalog instantiation.  The "kron_params" are a list of two values that
are used to determine how the Kron radius and flux are calculated.  The two values, kron_scaling_radius
and kron_minimum_radius, are stored as two new configuration values in the catalog configuration file
associated with each of the detectors.
> Add the Kron radius as an output measurement for the catalog

- setup.py
Simple change to insure that v1.2.0 of photutils does not get used with this version of Drizzlepac at this point.
> Insure only photutils 1.1.0 gets used

- drizzlepac/haputils/catalog_utils.py
The MSkyAp2 and StdevAp2 are based on an estimate of the background in an annulus beyond Aperture 2 (the outer aperture).  Bck looks like it is per unit area.  The descriptions units were updated for these values in any catalog where they are present.
> Fix the units of a few variables in the output Point and Segmentation catalogs

- drizzlepac/hapmultisequencer.py
Use the correct version of the function `_get_envvar_switch()` in `hapmultisequencer.py`; specifically, the version from `hapsequencer.py` that supports use of a default value.
> Use correct version of get_envvar function

- drizzlepac/haputils/hapcut_utils.py
For mvm_id_filenames, make the output MAST query results file have a
consistent naming convention with the remaining hapcut utilities.
For make_the_cut, loop over the files for which cutouts have been requested.
In this way if one of the files causes an exception for any reason (e.g.,
the file does not contain the cutout region), an error is issued, but
the remaining files continue to process. For make_the_cut and mvm_combine,
added the instrument designation to the output files for completeness (though
now the filenames are even longer).  For mvm_combine, added the FILENAME
keyword to the PHDU of the output combined file.  Also, improved the EXTNAMEs
of all the EHDUs to reflect the data they contain.  Added or improved clarity
of comments.
> Improvements/updates made to MVM utilities while documenting the code

- tests/hap/test_svm_wfc3ir.py
- tests/hap/wfc3_ir_ib6807_input.out
This adds some pytests for the SVM processing of WFC3/IR data based on data from visit ib6807 and using the template for the tests developed under #1185 .
> Add pytest for WFC3/IR SVM processing

- tests/hap/test_acs_hrc_sbc_input.out
- tests/hap/test_svm_hrcsbc.py
This adds a new pytest derived from the template implemented under #1185 to validate SVM processing of ACS/HRC and ACS/SBC data.  The test only checks a couple of simple things, such as WCSNAME with FIT_SVM_GAIA and that the total catalogs exist with a rough (rtol=0.1) number of sources.
> Add new pytest for SVM HRC and SBC processing

- CHANGELOG.rst
- drizzlepac/imageObject.py
- drizzlepac/wfpc2Data.py
This PR addresses an issue with WFPC flat filed files having extension name `FLT` instead of the expected (by the code) extension `SCI`. When trying to drizzle WFPC2 image with IVM weighting, this unexpected extension type would result in a crash.
> Fix an issue with WFPC2 flat field file extension name

- drizzlepac/hapsequencer.py
Reworked to ensure *all* the alternate WCS solutions, except for OPUS, are
stored as headerlets.  As the alternate WCS solutions may not have an HDRNAME,
a HDRNAME is generated on-the-fly by using the filename, stripping off the
".fits" suffix, and adding the WCSNAME and "-hlet.fits". For example, a HDRNAME
might be hst_9029_01_acs_wfc_f775w_j8ca01at_flc_IDC_0461802ej-FIT_SVM_GAIAeDR3-hlet.fits.
This change ensures the list of headerlets contains all of the solutions, except
perhaps for the OPUS solution.
> SVM: Ensure list of headerlets contains all the WCS solutions available

- drizzlepac/haputils/processing_utils.py
These changes revise the logic used to update the HDRTAB extension table with the HAPEXPNAME column to avoid creating empty rows in the HDRTAB.  Previously, a new column including the new HAPEXPNAME values was created by searching for the input exposures in ALL the total products resulting in a column that was the sum of all the total drizzle products input exposures in length.  This logic was revised to only update the HDRTAB table for the inputs associated with  the total product image being updated.
> Avoid empty HDRTAB rows

- drizzlepac/hapsequencer.py
Simple fix for the logging initialization for SVM processing.  
These changes were used to successfully process data from visit **j94sk1**.
> Fix logging setup for SVM processing

- JenkinsfileRT
- azure-templates.yml
These changes are the changes needed to add Python 3.10 testing to the nightly Jenkins regression tests, while also documenting how to add Python 3.10 to the Azure tests as well.
> Add Python 3.10 to Azure test matrix

- JenkinsfileRT
Python 3.10 configurations added in #1208 now need to be turned on in Jenkins with these changes.
> Turn on Python 3.10 Jenkins testing

- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/analyze.py
- drizzlepac/haputils/poller_utils.py
Reworked the analyze_wrapper function to accept two new parameters, an indicator for SVM or MVM processing and an indicator as to whether or
not SBC/HRC data should be used for MVM processing.
The MVM indicator has two uses: (1) Marks Grism/Prism data as "do not
process" in the filtered table associated with the poller file, and
(2) acts as a gate for further checking of the filtered table data when
SBC/HRC data should not be used for processing.
Clarified messages which are generated for the log for the cases with
associated return codes:
No viable images in single/multi-visit table - no processing done.
Return code = 65
Only non-viable or SBC/HRC images in the multi-visit table - no processing done.
Return code = 55
> Special handling of SBC/HRC MVM data, clarify messsages, return codes

- drizzlepac/align.py
This change stops relying on the tweakwcs fit information for the 'nmatches' value altogether, since it has proven to be inconsistent with what actually gets used for the final fit due to outlier rejection used within tweakwcs.
> Compute own NMATCHES value for fit validation

- drizzlepac/haputils/align_utils.py
- drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
This codifies the limits on minimum number of cross-matches that are acceptable for each type of fit (e.g., rscale, rshift,...) that gets performed during alignment as requested by INS.
> Set NMATCH limits for fitgeoms to INS requested values

- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/product.py
These changes fix problems with memory use during processing with hapmultisequencer.  Specifically, footprint masks are properly defined one per layer, not one per exposure, and they are deleted as soon as they are no longer needed by the processing.  This reduces the memory usage during this stage of processing to a maximum of about 2Gb based on the memory used by an array of a single full skycell layer.
> Reduce memory use in hapmultisequencer

- setup.py
- tests/hap/test_pipeline.py
- tests/hap/test_svm_hrcsbc.py
- tests/hap/test_svm_ibqk07.py
- tests/hap/test_svm_ibyt50.py
- tests/hap/test_svm_j97e06.py
- tests/hap/test_svm_wfc3ir.py
The issues are reference files are no longer in the appropriate locale, or
the expected WCS is not derived.  Interestingly, the tests run successfully
locally.
I will note the majority of the HAP tests may still fail **_as an ensemble_** due to the way the logging has been implemented in the HAP routines combined with the fact the PyTests are run in a single Python session.
> Temporarily "skip" the HAP PyTests which fail in their assertions.

- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/product.py
- drizzlepac/runmultihap.py
This prefix was inadvertently re-introduced when handling the special cases
of no data being available for processing or some other error when reading
the poller file so the total data product attributes were never set.  Hence,
no default manifest filename was defined.
> Remove the prefix "hst_" from the manifest filename for MVM products.

- doc/.rtd-environment.yml
- setup.py
This PR explicitly adds `spherical_geometry` to the list of dependencies in the `setup.py` because it is used by HAP code and I also set the minimum  version requirement for the `spherical_geometry` to `1.2.22` as previous versions may cause memory corruption.
> Add explicit dependency on spherical-geometry and set min version

- drizzlepac/haputils/testutils.py
- tests/hap/test_apriori.py
These changes make the 'test_apriori' tests less stringent while also reporting a lot more information on failures or Exceptions.  The less stringent limits for this test do not impact the validity of the test since they are looking for situations where the fitting ended up acting singular (wildly wrong, yet successful).  Small variations in the results can come from differences in the proper motions used in the catalog source positions as well as implemented (expected) changes to the sigma-clipping in the fitting itself amongst other valid reasons.
> Update apriori test to be more explicit with errors

- drizzlepac/haputils/align_utils.py
- drizzlepac/runastrodriz.py
These changes copy the header keywords from the FLC file header that report the quality of the a posteriori WCS fit into the header of the FLT file.  This insures both headers have the same information so that the DRZ and DRC files will also be identical/consistent.  The set of keywords updated includes: PYWCSVER, UPWCSVER, HDRNAME, NMATCHES, FITGEOM, RMS_RA, RMS_DEC, CRDER1, and CRDER2.
> Insure both FLT and FLC headers have same a posteriori fit keywords

- drizzlepac/haputils/diagnostic_utils.py
- drizzlepac/haputils/make_poller_files.py
**RELATED ISSUES AND TICKETS**
- #1216 
- [HLA-680](https://jira.stsci.edu/browse/HLA-680)
**BACKGROUND**
- For a small number of edge case images (those with header values "PRIMESI" != "INSTRUME"), the first two characters of header value "LINENUM" do not match the values in the 5th and 6th places of the filename or header value "ROOTNAME".
- make_poller_files.py was populating the "visit number" column of .out files with the incorrect value because it was using the first two characters of header value "LINENUM" for these edge case images.
**SUMMARY OF CHANGES**
- Added logic to check for the edge case and if detected, use the 5th and 6th characters of "ROOTNAME" header value rather than "LINENUM" to produce "visit number" values. 
- For all other non-edge case images, "visit number" …
> update how make_poller_files.py generates visit numbers to account an edge case

- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/analyze.py
- drizzlepac/haputils/product.py
These changes correctly(?) utilize the logic in analyze_data to skip alignment of grism/prism data during standard pipeline processing while allowing the (partial) processing of grism/prism data for SVM processing as needed to sync WCSs with the direct images.  
The data from visit 'ibtt98' with grism ASNs 'ibtt98010' and 'ibtt98020' were used to verify the correct behavior of this logic for both standard pipeline processing and SVM processing.
> Fix logic to not align grism data in standard pipeline

- drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
RickerWavelet Kernel for SBC needs to have dimensions which are odd.
Changed to 23 from 24.  Tested with j8ep07.
> RickerWavelet Kernel for SBC needs to have dimensions which are odd

- drizzlepac/align.py
This simple change addresses the bug reported in HLA-689 that related to checking for alignment results in align.py when it was apparently not necessary.   Removing this logic should allow more data to successfully align to GAIA.
> Remove logic from align

- drizzlepac/nicmosData.py
- drizzlepac/wfc3Data.py
- setup.cfg
- setup.py
`nictools` does not appear to be maintained, removing it makes drizzlepac's build system just a bit more robust.
Copied the code fro nictools to drizzlepac/nicmosData.py.
Should be merged after #1244.
> Remove nictools as a dependency

- CHANGELOG.rst
- src/cdrizzlebox.c
- tests/drizzle/test_drizzle.py
This PR fixes a bug in the C code of the core drizzle algorithm due to which flux from the input image could be dropped onto the output (resampled) image even though those input pixels have zero weights.
This is a port of the bug fix from https://github.com/spacetelescope/drizzle/pull/79
> Fix incorrect drizzling of 0-weight input pixels

- drizzlepac/haputils/align_utils.py
This simple change corrects the use of 'rstrip' in the generation of the HDRNAME keyword so that it comes out as expected.  
Using '.rstrip(".fits")' on a full filename results in chopping the last character of the filename before the ".fits" (don't ask me why!).  However, using '.rstrip("fits")' leaves the '.' from the full filename at the end of the string.  This simply uses that behavior to correctly strip the '.fits' from a full filename and not chop the 'flt' or 'flc' to be 'fl'.
> Generate correct HDRNAME (finally?)

- drizzlepac/devutils/comparison_tools/compare_sourcelists.py
- drizzlepac/hapsequencer.py
- drizzlepac/haputils/comparison_utils.py
- drizzlepac/haputils/config_utils.py
- drizzlepac/haputils/get_git_rev_info.py
- drizzlepac/haputils/product.py
**Relevant Issues and Tickets**
- [HLA-677](https://jira.stsci.edu/browse/HLA-677)
- Issue #1212
- [HLA-712](https://jira.stsci.edu/browse/HLA-712)
- Issue #1260 
**Summary of Changes**
- The main goal here was to standardize execution of the sys.exit() command by any and all code ultimately run by either the SVM or MVM pipeline.
- At the site of any sys.exit() command in  any code that is ultimately run by either the SVM or MVM pipeline I...
- ensured that there was a descriptive message in a log.error() statement
- ensured that the sys.exit() command returned an integer value, which was typically 1, but could also be 0, 55 or 65 in specific cases.
- A small section of code was copied from hapmultisequencer.py to  hapsequencer.py to handle BaseExceptions raised when a sys.exit() command …
> SVM/MVM: Update/fix HAP code "exit" statement handling

- drizzlepac/hapmultisequencer.py
- drizzlepac/hapsequencer.py
Logic for deleting all the rules files generated during SVM and MVM processing gets updated with these changes to include the rules files created for the filter and total products as well.  Previously, these rules files were not included in the list of rules files which get deleted during processing resulting in these intermediate files being left behind after successful processing and causing confusion for subsequent processing.
> Add product rules files for deletion

- drizzlepac/align.py
Update to handle the situation where the one chip has sources, but the other chip has no sources, and the data is stored in a dictionary. The "table" is actually a dictionary so the len function on len(table[chipnum]) where table[chipnum] is NoneType caused an exception.
> Protect actions being performed on a potentially NoneType object

- pyproject.toml
- setup.cfg
This simply updates the dependency requirements for the package to allow use of the latest version of astropy; namely, astropy 5.0.  The addition of the 'typing_extensions' dependency is needed since astropy 5.0.1 does not include this itself, as it was only added to astropy installation with [Astropy PR #12812](https://github.com/astropy/astropy/pull/12812) after 5.0.1 was released.  
The results of using astropy 5.0.1 are identical to using astropy 4.3.post1 based on comparisons of data from visit 'iacs01' along with running the 'hap' pytests.
> Update requirements to allow astropy 5.0 use

- drizzlepac/haputils/diagnostic_utils.py
- drizzlepac/haputils/get_git_rev_info.py
- drizzlepac/haputils/svm_quality_analysis.py
The JSON files now can be generated for SVM processing with **'SVM_QUALITY_TESTING'** turned on as a result of these changes.  Updating _photutils_ to v1.2.0 resulted in the table of point sources to be returned as a **QTable** instead of a simpler **Table** object, and the **QTable** object can not (at this time anyway) be serialized as a **JSON** object.  Casting the output from _photutils_ to a simpler **Table** object fixes this problem with no consequences.  This allows the SVM testing using the _'svm_quality_analysis'_ module to succeed regardless of the version of _photutils_.  
In addition, a couple of changes were implemented to allow this code to be more platform independent; specifically, the git information can now be reported successfully even when run on Windows.  
These …
> Generate SVM QA JSONs again

- CHANGELOG.rst
The CHANGELOG file which serves as the release notes for the Drizzlepac package is being updated here to document the changes for v3.3.1 (which due to an oversight) never got properly documented as well as the new release v3.4.0 in support of the MVM processing code.
> Update Release Notes for v3.4.0 release

- setup.cfg
This simple change insures that the version of the markupsafe package used by astropy will allow astropy to still work, as markupsafe v2.1.0 removed functionality which astropy used up through 5.0.1.  This will allow the publish to PyPI scripts to work for drizzlepac as well.
> Limit markupsafe version for astropy use

- setup.cfg
Update release branch to allow publishing to PyPI to work.
> Limit markupsafe version for astropy use (#1286)

- drizzlepac/ablot.py
- drizzlepac/adrizzle.py
- drizzlepac/astrodrizzle.py
- drizzlepac/buildmask.py
- drizzlepac/buildwcs.py
- drizzlepac/createMedian.py
- drizzlepac/drizCR.py
- drizzlepac/imagefindpars.py
- drizzlepac/mapreg.py
- drizzlepac/photeq.py
- drizzlepac/pixreplace.py
- drizzlepac/pixtopix.py
- drizzlepac/pixtosky.py
- drizzlepac/refimagefindpars.py
- drizzlepac/resetbits.py
- drizzlepac/skytopix.py
- drizzlepac/staticMask.py
- drizzlepac/tweakback.py
- drizzlepac/tweakreg.py
- drizzlepac/updatenpol.py
- drizzlepac/util.py
These changes reset the values of the `__taskname__` variable for each task/module in drizzlepac so that code which calls teal to get the default parameters using these tasknames will actually work again.  This will enable many of the pytest tests to also run successfully again as well.
> Reset tasknames to work with TEAL

- setup.cfg
Restrict the markupsafe dependency even further.
> Lower markupsafe dependency again

- pyproject.toml
Update release branch with pyproject update for markupsafe version use.
> Update pyproject file for public release (#1293)

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/constants.py
- drizzlepac/haputils/photometry_tools.py
When photflam == 0.0, the magnitude, magnitude error, and CI are set to -9999.0.  Reworked the computation of CI for both Point and Segment catalogs.  Also, ensure "ci_data" and "ci_mask" are created even if an exception is thrown.
> Protect computations when photflam is equal to 0.0

- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/product.py
This corrects an oversight in the drizzling of MVM products, where the rules file intended for generating the MVM products was not being explicitly passed to AstroDrizzle.  The changes here now insures that the correct rules file gets used so that the IPPPSSOO keyword no longer appears in ANY MVM product header.
> Remove IPPPSSOO keyword from MVM product headers (again)

- drizzlepac/processInput.py
These changes implement the code necessary for correctly interpreting binary tables with astropy regardless of the astropy version.  Astropy versions < 5.0 returned binary table data as byte arrays, while versions > 5 did not.  This code interprets that table data correctly in either case.  This now allows `astrodrizzle.AstroDrizzle()` to be run directly from python scripts (or command line) when astropy >=5.0 is installed as tested using data from ASN `ibvz01020`.
> Fix problem with astropy 5.0 table interpretation

- drizzlepac/haputils/product.py
This ticket addresses a majority of HLA-338 HLA-687.  
Also, fixed a bug which manifested itself by inserting incorrect statistics into each SkyCell layer.  The statistics for the last layer processed were used for all layers.  The problem was a shallow copy of the default dictionary was used to initialize the object attribute when a deepcopy was needed.  The stats are in SCI header only.
WHT statistics.
> Statistics for SVM and MVM 

- drizzlepac/processInput.py
These changes force boolean columns of ASN tables to be explicitly copied over with the exact values as the input ASN table when creating copies for pipeline processing in `runastrodriz`.  This corrects the problem with using `stsci.tools.asnutil.readAsnTable(asnfile, prodonly=True)` and not getting any table data as seen in testing.
> Explicitly update boolean column in ASN tables

- tests/hap/test_svm_ibqk07.py
- tests/hap/test_svm_ibyt50.py
- tests/hap/test_svm_j97e06.py
This just cleans up a couple of HAP pytests; 
- fixed variable being referenced with the variable that actually exists in test_svm_ibqk07
- refined the success criteria for a test dataset with only 1 strong source to use atol instead of rtol, since 1 is 0.5 of 2 using rtol limits.
> Refine HAP Pytests success criteria

- drizzlepac/haputils/product.py
- drizzlepac/wcs_functions.py
The specification of the output WCS used in determining the backgrounds during catalog generation, and all throughout SVM processing, are now synchronized between what AstroDrizzle computes and what the SVM determines for the meta_wcs.  Hard-coded values and interpreted WCS objects were removed in favor of exact user and/or config-file specified output WCS values which eliminates a source of rounding error when trying to use the AstroDrizzle products with the SVM computations.  
These changes address the problems seen when processing some ACS/HRC datasets where an IndexError like:
```
File "/ifs/pipeline/dms/rhel7/pkgs/miniconda3/envs/caldp_mvmbeta/lib/python3.8/site-packages/drizzlepac/haputils/catalog_utils.py", line 275, in compute_background
num_of_zeros = …
```
> Synchronize output WCS specifications for SVM processing

- drizzlepac/haputils/comparison_utils.py
- drizzlepac/haputils/get_git_rev_info.py
- drizzlepac/haputils/svm_quality_analysis.py
These changes add logic to guard against trying to cross-match empty catalogs in svm_quality_analysis which would otherwise cause an Exception reporting an "Unrecognized format.  Exiting...".  
In addition, these changes look to see whether or not the package has been installed outside the source tree, like it would be when installed under a conda envs site-packages directory.  If no git information is present, it instead reports the commit id as 'master' as a default rather than raising an Exception.  
Finally, some changes were also included to clean up the git hash returned under Windows so that is is valid.
> Ignore git information for installations in conda envs

- drizzlepac/haputils/catalog_utils.py
Modify the units of the catalog variables to put them into a format recognized by astropy.units.  The reason for this is when a table is read (Table.read), it is prohibitively slow when astropy cannot figure out the units.
We (Rick and Steve for MAST) are reading all the ecsv files and inserting them into database tables, and about 25% of the time was being spent reading these headers!  The problem is that astropy is trying to figure out what the unit is.
Tested with dataset ic5s09 (hst_13089_09_wfc3_uvis_total_ic5s09_point-cat.ecsv).  Verified all output catalogs, filters and total, contain the updated units.
> Ensure units of catalog variables comply with Astropy

- drizzlepac/runastrodriz.py
New logic was added to the updating of header keywords to report on the quality of the alignment fit to report default values for zero-exptime exposures that are members of an ASN where the other members are valid (exptime > 0).
> Apply default alignment fit parameters for zero exptime exposures

- drizzlepac/haputils/catalog_utils.py
Since the introduction of proper astropy units (Git PR#1316), some variables were interpreted to be QTable instead of Table. This caused errors not seen previously. Simply casting the variable back to a Table at the point where the error was raised fixed the problem.
> Fix bug caused by Astropy Tables being interpreted as QTables

- drizzlepac/hapmultisequencer.py
- drizzlepac/hapsequencer.py
- drizzlepac/haputils/product.py
These changes insure that when the mask keywords such as MEANEXPT are expected to be written to the output product headers, that they have already been computed.  This insures that all SVM filter and total products and all MVM (filter) products get updated as expected with this set of keywords.  These keywords are not added to the SVM exposure time products since it makes no sense to do so.  
This was tested using data from visit 'ib6807' and from skycell p1889x07y19.
> Revise logic for when mask keywords are computed

- drizzlepac/haputils/product.py
Add MEANWHT and MEDWHT keywords to drizzle products.  These keyword computations are currently working
and tested for SVM Total and Filter drizzle products where they are resident in the WHT extension.
> Add MEANWHT and MEDWHT keywords to drizzle products

- drizzlepac/pars/acs_mvm_header_hap.rules
Simple fix to correct a typo in the ACS MVM header rules file that was partially responsible for corrupting the output MVM products.  
This fix works in concert with the [fitsblender PR #33](https://github.com/spacetelescope/fitsblender/pull/33).
> Fix typo in ACS MVM header rules file

- drizzlepac/haputils/product.py
Small change to the comment portion of the FITS cards for MEANWHT and MEDWHT to clarify the meaning of the keyword.
> Clarify comment portion of FITS card for MEANWHT and MEDWHT.

- pyproject.toml
As [noted](https://github.com/spacetelescope/drizzlepac/pull/1335#issuecomment-1099237782) by @nden in PR #1335, the astropy version in `pyproject.toml` needs to be updated. This PR does that too.
> Update pyproject.toml astropy min version

- drizzlepac/haputils/catalog_utils.py
Improved the algorithm used to filter the array of big segments which
will be deblended.  Added safety catches, more comments, and clean-up to
the logic.  The clean-up clarifies the distinction between the code
used to identify "big islands" or a large "source fraction" which are
only used to set a flag to indicate another kernel or background
computation could yield improved results.  This is distinct from
an array of identified large segments which are filtered only to
contain segments of reasonable size to be deblended.  Deblending
enormous segments can be prohibitive in time.
This PR address the issue reported in JIRA HLA-757
> Improve algorithm for identifying and filtering large segments

- drizzlepac/hapsequencer.py
These simple changes insure that the IDCSCALE keyword does not get deleted when the WCS gets updated to an a priori WCS to match the Grism exposures WCS.  The keyword gets deleted by STWCS when restoring the WCS from the headerlet.  The code now just records the original value and restores it at the same time it restores the NMATCHES keyword.  
This change was tested against data from **icwz06** which was originally used to demonstrate the problem.
> Carry over IDCSCALE keyword when updating WCS to match Grism WCS

- drizzlepac/hapmultisequencer.py
- drizzlepac/haputils/analyze.py
- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/product.py
This implements several changes (fixes?) to how exposures are associated with SkyCells and how the processing will respond when an unexpectedly non-overlapping exposure is specified for a given SkyCell.  The specific changes include:
- adding an attribute to the SkyCellProduct class to indicate whether or not there are overlapping exposures for that product
- adding logic to check whether or not any exposure overlaps a SkyCellProduct footprint
- checking whether or not this attribute is True when running `hapmultisequencer.run_mvm_processing`
- treating all edge pixels and corner pixels as lists of numpy arrays (addresses #1358 and #1359)
- checking each exposure separately to see what SkyCell(s) it overlaps when running `cell_utils.get_sky_cells`
These changes were all tested against …
> Ignore layers with no overlapping exposures

- drizzlepac/haputils/align_utils.py
Simple changes to correctly describe the CRDER and RMS_RA keywords in headers aligned to GAIA.   This also scales the CRDER keyword values to be in units of deg (as expected by FITS and described in the comment)  instead of mas for the values from the WCS fit.
> Update crder units

- drizzlepac/haputils/catalog_utils.py
(1) During construction of the attribute, it is necessary to check the array is not empty.  If it is, set the attribute
to None.  (2) Only perform the deblending step if the attribute in not None.
> This change addresses bugs associated with the big_segments attribute of the segmentation image

- drizzlepac/haputils/analyze.py
- drizzlepac/runastrodriz.py
Added protection around the function call, verify_guiding, from the analyze_wrapper routine.  The function will only be called if the processing type is "MVM".  Also added a new parameter, do_verify_guiding, to the process function in runastrodriz.py.  This new parameter will allow a user to turn on verify_guiding for pipeline processing.  Organized the order of the parameter switches for the process function.  Added explanatory comments in the code for these changes.
> Only allow "verify_guiding" check for MVM processing

- drizzlepac/haputils/processing_utils.py
Ensure the HAPEXPNAME column is the size of the largest input name currently being processed OR at least 51 characters.
> Fix the size of the HAPEXPNAME column in the HDRTAB of the MVM output DRZ/DRZ file

- drizzlepac/outputimage.py
This simple change makes sure that the WCSNAME and WCSTYPE keywords do not get populated by blank strings if the output WCS used for drizzling did not have a `wcs.name` attribute to use in creating the WCSNAME keyword value.  This situation can happen if an output WCS gets defined and passed in to AstroDrizzle for the final drizzle step, leading to the blank string overwriting the default value  from the input images during MVM processing.
> Pass along default WCSNAME

- CHANGELOG.rst
- drizzlepac/tweakback.py
Due to somewhat recent changes in the `stwcs` package and `altwcs` module specifically, `tweakback` function stopped working with default parameters. It has become clear that it is impossible to fix `tweakback` (or its documentation) in a consistent way given changes in the `stwcs`.
This PR proposes a new version of the `tweakback` function called here `apply_tweak` with a slightly different API consistent with `stwcs` changes that preserves main functionality of the `tweakback`. This is basically a replacement for `tweakback` which is deprecated in this PR.
> Re-design tweakback

- drizzlepac/haputils/analyze.py
Ensure Ramp filter data is not used for MVM processing.  Marked this data as "do not process" during the early analyze step.  Messages are generated for the output trailer file for documentation purposes.
This fixes JIRA HLA-777.
> Ensure Ramp filter data is not used for MVM processing

- drizzlepac/haputils/product.py
The changes are that Level 3 is unused and Level 4 indicates the multi-visit mosaics.  The full documentation is now:
1 : calibrated (FLT/FLC) input images and exposure level drizzle products with improved astrometry
2 : filter and total products combined using the improved astrometry, consistent pixel scale, and oriented to North
3 : unused
4 : multi-visit mosaics aligned to a common tangent plane
> Modified the docstring which defines the HAPLEVEL and its associated meaning

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/product.py
Alignment of SVM products often requires multiple attempts based on multiple astrometric catalogs.  These changes keep track of what reference catalogs get written out for use in alignment, then removes all of them if not in diagnostic_mode during SVM processing.  
This prevents these ref_cat files from remaining on disk during pipeline processing and resolves [HLA-775](https://jira.stsci.edu/browse/HLA-775).
> Delete all reference catalogs during SVM processing

- drizzlepac/haputils/mvm_quality_analysis.py
- Ticket [HLA-802](https://jira.stsci.edu/browse/HLA-802)
- As originally written, mvm_quality_analysis.py would only work with input images that were named with the "pipeline" filename format (ipppssoot_fl[tc].fits), and would crash if presented with input images that were named with the "hap" filename format (hst_<propid>_<visit>_<instr>_<det>_<filter>_<ipppssoo>_fl[tc].fits). This PR fixes the hap filename format incompatibility so that mvm_quality_analysis.py can process input _fl[ct].fits images whose filenames use either format.
- removed unused overlap_dict element 'svm_img_'
> MVM: Update cross-match routine to read pipeline poller file

- drizzlepac/haputils/poller_utils.py
This simple change converts an Exception to an immediate system exit so that the calling code can better understand the reason for quitting processing at this point.  Specifically, if there are no new MVM inputs to process, it should simply quit with a pre-defined exit code of 65.
> Exit immediately if no new MVM inputs

- drizzlepac/sky.py
Super simple update to the sky matching code in AstroDrizzle to always revert to a less complex sky matching algorithm if the full matching algorithm fails.
> Revert sky matching upon any error

- drizzlepac/haputils/mvm_quality_analysis.py
Added try/except blocks for a KeyError, generated for a dictionary, and an IndexError, generated for a 2D mask, where information may be missing as the regions do not overlap or do not overlap enough to have the data to populate the data structures.  Since this information is for quality analysis of the alignment, we want the evaluation to continue and skip over "inappropriate" regions. Tested with skycell-p1637x16y01 which has 24 input SVM images over three visits, four filters, and two detectors.
> Added try/except blocks for exceptions generated with regions do not have cross matches

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/hla_flag_filter.py
- drizzlepac/runastrodriz.py
- drizzlepac/wfpc2Data.py
These updates revise the SVM processing code to support not only full 4-chip readout mode WFPC2 exposures, but also 'subarray' readout exposures where only some of the detectors are read out.  This adds a new 'detector' mode for WFPC2 data, 'wf', to compliment the default 'pc' which gets defined for 4-chip exposures.  
These changes were tested using data from "visit" **u2310k** which actually has a mix of readout modes for the exposures in the visit.
> Update SVM to support WFPC2 subarray exposures

- CHANGELOG.rst
- drizzlepac/haputils/catalog_utils.py
Some input data includes names of the coordinate system for the WCS from the REFFRAME keyword that are not supported by the FITS WCSLIB transformations.  These changes watch for any incompatible REFFRAME/RADESYS values and replaces it blindly with a value of 'ICRS' for the purposes of generating the sky coordinates of the segmentation catalog sources only.  Log messages are then generated to warn the user that such a change to the computation of the sky coordinates was made and that the output sky coordinates may not be entirely accurate.
> Support additional RADESYS options for input files

- setup.cfg
Essentially remove restriction on PhotUtils package version, except to avoid old versions where there were many changes (avoid <= 1.2.0).
> Essentially remove restriction on PhotUtils package version

- drizzlepac/outputimage.py
- drizzlepac/runastrodriz.py
Some _a posteriori_ headerlet solutions retrieved from the astrometry database do not have the full distortion model solution attached as they should have which results in the omission of the distortion model when drizzling the affected exposure(s).  These changes look at all the headerlet solutions provided by the astrometry database to verify that those with WCSNAME containing '-FIT' also have a full distortion model and the corresponding CTYPE values.  This check gets performed before those solutions are used for alignment, so if any are found with problems, they are simply deleted from the input exposure so that the alignment can proceed from scratch.  
This allows the resulting image to be aligned correctly while also generating a properly distortion-corrected drizzled image and was …
> Verify astrometry headerlets and remove bad ones

- CHANGELOG.rst
- azure-templates.yml
- drizzlepac/haputils/poller_utils.py
New logic has been implemented to determine the output product type (DRZ vs DRC) based on evaluating the filenames of all inputs.  If any FLC files are present for the filter product, any FLT images in the same filter product input list will be ignored and the product will be given the DRC product type (filename suffix).  A single exposure product will be created for any ignored product as a record that those exposures were taken, but they will not be included when creating any filter product, total product or even skycell layer.
This change serves as the interpretation of decisions made by the instrument teams on how to treat any mix of CTE and non-CTE corrected exposures when creating SVM and MVM products.  The changes were tested using the data from visit ``ibig07``, where the F814W …
> Insure correct filetype gets defined for filter and total products

- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/cell_utils.py
These changes fix the last remaining instance where numpy v1.23 support was overlooked earlier when resolving numpy deprecation warnings.  This affected the use of the cell_utils module only.  In addition, a typo was also cleaned up in a function within the align_utils module which would have affected what exposures could be aligned to an astrometric catalog. 
These changes were tested against data from visits 'j8ph01' and 'ie3501' with standard pipeline processing of an ASN with ``runastrodriz``, single-visit mosaic processing, and also sky cell determination for an exposure (where the numpy problem was originally identified).
> Update to fully support numpy v1.23

- CHANGELOG.rst
- azure-templates.yml
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/cell_utils.py
- drizzlepac/haputils/poller_utils.py
This pulls in changes from master to define the next release candidate: v3.5.0rc1
Changes include:
- Update logic for defining output product filenames with correct DRZ or DRC suffix (#1433 )
- Fix lingering problem with numpy v.1.23 support (#1434 )
> Update release candidate to define v3.5.0rc1

- JenkinsfileRT
This simple change removes any Python 3.7 builds from the Jenkins builds used for testing our package.
> Remove Python 3.7 tests from Jenkins builds

- .readthedocs.yaml
- .readthedocs.yml
- doc/source/conf.py
change `.readthedocs.yml` -> `.readthedocs.yaml`, enable `nitpicky` mode to validate intra-doc links
> use canonical filename of RTD configuration and enable `nitpicky`

- drizzlepac/haputils/astroquery_utils.py
Some requests for SVM data using `astroquery_utils.retrieve_observation` will result in an Exception being thrown due to an attempt to try to move a file which has already been moved.  This simple change avoids that problem and allows the request to succeed normally.
> Prevent astroquery code from throwing an Exception for SVM requests

- drizzlepac/runastrodriz.py
This simple change fixes the command line interface to `runastrodriz` in order to once again interpret the `-n` parameter input correctly.
> Fix command line interface for runastrodriz

- CHANGELOG.rst
- drizzlepac/haputils/analyze.py
- drizzlepac/runastrodriz.py
These changes turn on the use of the `verify_guiding()` function from `haputils/analyze.py` in order to not try to align any exposure which appears (according to the algorithm) to have lost lock resulting in trailed stars.  The function was also upgraded to check the `QUALITY` keyword and ignore any exposure which has been marked with either 'GSFAIL' or 'TDF-DOWN'.  In addition, the logic for using this function was updated considerably in `runastrodriz` so that alignment is turned off when any exposure has been flagged as `BAD` by this function, and to not create any drizzle products if all exposures are found to be 'BAD'.  The logic, though, still allows the user to override these behaviors with the use of the `force` and `force_alignment` parameters. 
These changes were tested using …
> Use verify_guiding correctly for pipeline and SVM processing

- drizzlepac/runastrodriz.py
Update 3.5.0rc1 to include fix for runastrodriz command-line interface (#1444).
> Fix command line interface for runastrodriz (#1444)

- drizzlepac/runastrodriz.py
- drizzlepac/wfpc2Data.py
These changes include:
- a new function `wfpc2Data.apply_bestrefs()`
- update to `runastrodriz.process()` to always call `wfpc2Data.apply_bestrefs()` for all WFPC2 input files
- only FLT files will be updated by `runastrodriz.process()` 
- only the distortion reference files will be updated by `runastrodriz.process()`
The new function uses CRDS to update the headers with the best reference files currently available for processing according to CRDS.  If a local CRDS cache is already defined, it will use that, otherwise it will create one in the current working directory then delete it when finished.
The code was tested using data from visit **u2lx05**.
> Implement update of WFPC2 header for best references in runastrodriz

- drizzlepac/haputils/catalog_utils.py
The datasets quoted in this ticket which indicate they are good for testing a fix no longer even execute the apparent troublesome portion of the code.  The entirety of the drizzlepac code has changed a great deal in two years.  Since this has not been noted to have been an issue and no longer fails for the datasets suggested, I will make a modest change in the code which covers the case of zero sources. Note that zero sources should not be able to reach this portion of the code any longer.
> SVM: Fix logic for catalogs and cosmic ray checking

- setup.py
I can reproduce the error in #1453 by running `pip install ".[test]"` and `pytest` on the `main` branch in a new environment; however, when applying the change in this PR the build works correctly and properly assigns the C extension when running `pytest` in a new environment. I'm not entirely sure why.
> small change to test PEP517 build of C extension

- CHANGELOG.rst
- drizzlepac/haputils/astrometric_utils.py
Added informational text in the form of a log WARNING when the catalog service fails (e.g., service cannot be reached or the request was somehow malformed) in an effort to make the default response more useful.  The request specification is also sent to the log, so the user can see what was actually requested.
The routine that is making the function call may decide this issue is or is not a problem.
> Add error handling/improved messages to CatalogSearch functions

- CHANGELOG.rst
Added the missing CHANGELOG comment for the update in PR#1450 as it addresses a bug.  The fix ensures if no sources are found and the threshold is zero, the code properly evaluates to indicating the catalog failed the CR threshold criterion.
> Add the missing CHANGELOG comment for PR#1450

- CHANGELOG.rst
- drizzlepac/haputils/analyze.py
Protect against there being no sources left to measure after cleaning cosmic rays from the input image in ``verify_guiding()``.  If there are no sources left, this is akin to the check in the code where the number of sources < 2.  The value of False is being returned in both cases indicating the guiding is good.  This fix avoids the _ValueError: segment_img must have at least one non-zero label._
> Protect against there being no sources left to measure

- CHANGELOG.rst
- drizzlepac/hapsequencer.py
Check the SCI extension(s) of the output FLT/FLC and DRZ/DRC files.  If the active
WCS solution is 'a priori', there should not be any valid values for NMATCHES, RMS_RA/RMS_DEC, FITGEOM, and CRDER1/CRDER2 as these keywords are associated with 'a posteriori' solutions.  Ensure the WCSTYPE is based upon the active WCSNAME. Clarify some comments.
> Cleanup SCI header (FLT/C, DRZ/C) keywords remaining from an 'a aposteriori' active WCS solution

- CHANGELOG.rst
- drizzlepac/haputils/astrometric_utils.py
Excapsulate the code which creates an IterativelySubtractedPSFPhotometry object and then tries to fit a FWHM with the settings in a try/except.  Added a log message indicating inability to find a FWHM due to a fitting problem as the original Exception message could be misleading.
> Protect against inability to find a FWHM due to a fitting problem

- drizzlepac/buildmask.py
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/deconvolve_utils.py
- drizzlepac/wfpc2Data.py
The 'shadow mask' refers to the mask used to ignore those pixels from each chip which falls under the shadow of the WFPC2 pyramid.  This mask gets used when drizzling the data and can either be made from the DQ array or from a calibrated function that describes that shadowed region.  The changes in this code allow the code to properly work with the new ACS-style FLT format for the WFPC2 data as generated when updating the reference files early in astrodrizzle processing.  This allows the current logic to work correctly based on the DQ array as opposed to using the default functional form when the code was originally looking for the DQ array in the c0m file which was not provided as input to astrodrizzle.  
The logic was also updated to used the shadow mask defined by the calibrated …
> Update wfpc2 shadow mask

- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wf/wfpc2_wf_alignment_all.json
These changes simply turn on the CR identification step within the alignment processing to ignore CRs when aligning WFPC2 data.   This corrects the problems with aligning WFPC2 data seen in testing, as confirmed by successfully aligning data from these visits:
- u2m301
- u27817
- u2lx05
- u55i03
> Turn on CR classify in align for WFPC2

- CHANGELOG.rst
- drizzlepac/runastrodriz.py
This simple change applies photometric equalization using `drizzlepac.photeq` to all WFPC2 exposures during standard pipeline processing with `runastrodriz`.
> Implement photometric equalization for WFPC2 pipeline

- pyproject.toml
This PR updates the `stregion` version from `1.1.6` to `1.1.7`, to include the fix for building in CPython 3.11
> update `stregion` to include Python 3.11 build patch

- drizzlepac/runastrodriz.py
This very simple fix allows the code to not try to delete invalid alternate WCS solutions if they are also the primary WCS.  Some headerlets from the astrometry database apparently do not have all the distortion keywords saved in them, and if they end up being used as the PRIMARY WCS, they should not get deleted since those keywords were already added by updatewcs during processing.  
This fixes the problem found with reprocessing data from idb645030, idh119010, idl330030, idxxa3030.
> Ignore headerlets for primary WCS solutions

- drizzlepac/haputils/diagnostic_utils.py
- drizzlepac/haputils/graph_utils.py
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_total.json
- drizzlepac/wfpc2Data.py
Modified diagnostic_utils.py module to accommodate WFPC2, in particular for its filter keywords which are FILTNAM[1|2] vs FILTER[ |1|2] for ACS and WFC3, respectively.  Addeded keyword PRIMESI to the PHDU for WFPC2 data, and fixed a typo in a configuration JSON file. Finally, made graph_utils.py a bit more flexible as the interface now accommodates a "view" request.
> Updates to the SVM quality analysis to accommodate WFPC2

- drizzlepac/haputils/poller_utils.py
- drizzlepac/haputils/processing_utils.py
These simple changes (as suggested by Numpy 1.20 Release Notes) should fix the problems with the pytests now that Numpy 1.24 has been released since Numpy 1.24 completely removed the deprecated use of 'np.str' in favor of 'np.str_'.
> Fix Numpy 1.24 str deprecation

- drizzlepac/wfpc2Data.py
This changes the code to use any user-specified CRDS_SERVER_URL from os.environ when applying bestrefs to WFPC2 data.  This will support use of test CRDS servers rather than always forcing the use of the public server.   In addition, the logic has been revised to also trigger a sync of the reference files to the local cache (or not) based on the 'CRDS_READONLY_CACHE' environment variable in order to support pipeline use of that variable. 
This code allows the CRDS code to crash with a status=-1 completely crashing out of any Python environment it was running in if the CRDS reference file cache or uref is not configured correctly BY THE USER if sync is turned off.
> Enable user specified CRDS URL for WFPC2 processing

- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n6.json
These are simple changes to fix the syntax of a couple of WFPC2 config files based on errors reported during WFPC2 SVM testing.
> Fix WFPC2 config file typos

- drizzlepac/wfpc2Data.py
This change avoids treating the environment variable `CRDS_READONLY_CACHE` as a writable variable, since the code only needs to read it once.  Removing this from the list of variables read keeps this variable out of the list of variables that need to be restored to the original state so the code does not try to delete the non-existent variable.
> Avoid trying to delete non-existent readonly cache flag from environment

- drizzlepac/haputils/astrometric_utils.py
- pyproject.toml
- tests/hap/test_pipeline.py
Modified compute_2d_background to accommodate API changes in PhotUtils while keeping this source code backwards compatible.  Modified the imports used in conjunction with OLD_PHOTUTILS.
Tested the "old" and "new" versions of compute_2d_background() by calling the function explicitly within a small test harness using hst_12572_52_wfc3_ir_total_ibug52_drz.fits as the input image.  The output images and float statistics were compared.  Note the specific portion of the code modified is invoked when the bkg = None and the resultant background and background_rms images are images of a single value.  The comparison between the "old" and "new" datasets is considered fine.
NEW
bkg_median: 0.5143258571624756   bkg_rms_median: 0.2762162387371063
OLD
bkg_median: 0.521289587020874   bkg_rms_median: …
> Update required to compute_2d_background() in astrometric_utils.py 

- drizzlepac/align.py
- drizzlepac/haputils/align_utils.py
These changes report the correct units for the CRDER* keywords now, using the astropy units already defined for them instead of trying to convert them manually.  Comments were also added to the keyword cards to specify the units of the term.  The units used for this keyword are now fully correct and consistent with the FITS Paper 1 standard and with the CUNIT* header keyword value.
> Reset crder units

- tests/wfpc2/test_wfpc2.py
The WFPC2 nightly regression test needed to be updated to stay consistent with the change in WFPC2 drizzle product name when it changed from _drz.fits to _drw.fits.
> Update WFPC2 RT to work with new DRZ name

- drizzlepac/runastrodriz.py
Only observations with the DRIZCORR header keyword value set to PERFORM should have 'updatewcs.updatewcs()' run on them, as the calibration files do not provide support for calibration or engineering modes.  This change fixes the problems caused by #1443 by moving that update and subsequent analysis of guiding inside the if statement for DRIZCORR.   
These changes were confirmed using data from visit 'u23v02'.
> Avoid running runastrodriz on calibration data

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/runastrodriz.py
- drizzlepac/util.py
Photutils renamed the '_wcs' attribute for SourceCatalogs to simply 'wcs' as of photutils==1.6.0.  These changes not only look for that and use the correct attribute under 1.6.0, but also uses the old attribute name generated by 1.5.0 as well when creating the source catalogs for SVM products. 
In addition, the version of photutils being used for processing now gets reported along with the versions of numpy, stwcs and astropy since photutils is a major dependency for this package. 
These changes were tested using data from visit 'j8ep06' under photutils=1.5.0 and photutils=1.6.0.
> Update to use photutils catalog wcs correctly

- drizzlepac/runastrodriz.py
Some WFPC2 exposures do not have their photometry properly calibrated causing the `photeq.photeq()` function to fail due to `PHOTFLAM` having a reported value of 0.0.  An example of such an exposure would be `u2l90105t` which uses an unusual polarizer filter, whereas other exposures in the visit using other filters process successfully.  These changes simply  trap the Exception from `photeq`, report the error in the log, then proceeds to process the image.   This should only affect the photometry of exposures taken with unsupported modes and will not affect the alignment or subsequent HAP processing of the data.
> Let photeq fail without crashing pipeline

- drizzlepac/runastrodriz.py
The logic for identifying headerlet WCSs which are invalid did not account for the headerlet WCS from the database not being added as an alternate WCS.  In this case, an invalid WCS is a WCS that does not contain all the SIP keywords even though they are supposed to be a SIP WCS.  This simple change does not change the original logic except to handle a value of None correctly when identifying what alternate WCS the invalid WCS had been written out to, with a value of None meaning it wasn't.  
The data from ASN 'id8064020' has at least 1 invalid WCS and was used to confirm the problem and that this change fixed it.
> Handle headerlet WCSNAME check correctly

- drizzlepac/haputils/catalog_utils.py
Source position columns in the source catalogs come back as MaskedColumns, yet the masking can actually cause problems in some cases when the '_mask' attribute goes missing during processing.  Since we never use the mask attributes for any of our processing, we can avoid these problems by simply insuring that the source catalog never contains a MaskedColumn.  These changes convert all point source catalog columns to simple unmasked columns.  
The data from visit `idw101` originally had problems since some of the images were empty causing those catalogs to be MaskedColumns unnecessarily.  These changes were tested against that data to confirm that this allows that data to complete SVM processing.
> Insure source columns are not masked

- drizzlepac/runastrodriz.py
Some headerlet files get written out by STWCS when they represent WCS solutions which are not present in the astrometry database, yet the filenames for those headerlets do not get passed along to the standard pipeline processing code `runastrodriz` to be included in the manifest file.  These changes look for those files and adds them to the manifest file along with the name of the headerlet file that was written out to represent the final WCS applied to the FLT/FLC file.  
These changes were tested against exposures from visit `u2l901` and resulted in 3 headerlet files being added to the manifest file that were not there before.
> Revise what HLET files get added to manifest file

- drizzlepac/haputils/catalog_utils.py
- drizzlepac/runastrodriz.py
Updates to the release branch 3.5.1x which currently has RC0 and RC1. These fixes constitute RC2 and include tickets/hashes in reverse time order (older tickets first as this is how the tickets MUST BE APPLIED to the release branch):
#1496 57b0d7f
#1497 ebfe042
#1498 242abde
> Create new release candidate 351rc2

- drizzlepac/runastrodriz.py
The filename used to write out the HLET file for the WCS solution used for the final runastrodriz product had been adding the WCSNAME to the filename without using the hash-tag when it should simply have been named using '_flt_hlet.fits'.  This corrects that mistake so that the simpler name gets used consistent with what gets written out to the manifest file.  
This change was tested using data from visit `u2311s`.
> Fix default HLET filename

- drizzlepac/haputils/analyze.py
- drizzlepac/runastrodriz.py
The logic used for checking whether WFPC2 observations should be processed took place after already starting to perform DRIZCORR processing.  This removed exposures from the list of inputs leaving no exposures to process, yet the next step was to get the exposures times which failed.  These changes update the logic for checking what exposures to process to not only fully reuse code from `haputils.analyze`, but also includes the check for GSFAIL as well, all before DRIZCORR processing starts.  
In addition, the message in `haputils.analyze.verify_guiding()` reporting on GSFAIL has been clarified so that the fact that the QUALITY keywords triggered the image to be flagged as 'BAD' gets properly reported in the output processing log (trailer file). 
The problem was originally identified in …
> Skip processing GSFAIL WFPC2 exposures

- pyproject.toml
Fix test/x-rst ==> text/x-rst.
> Fix another typo in pyproject.toml

- JenkinsfileRT
This change turns off generation of the XML output from pytest to see whether the regression tests will complete successfully.
> Turn off Pytest XML output

- drizzlepac/runastrodriz.py
The use of 'verify_guiding()' for WFPC2 images incorrectly recognizes diffraction spikes from saturated stars as evidence of loss of lock and flags those exposures as 'bad'.  This simple change turns off use of this function for WFPC2 data only, since loss of lock during an exposure was rarely an issue (if ever) and any such problems were reported in the QUALITY keywords which get checked as well.  
This was tested using data from visit `uba301`.
> Turn off verify for WFPC2

- drizzlepac/haputils/analyze.py
- drizzlepac/runastrodriz.py
Some user-specified target names include terms like 'DARK', such as the targets for visit `u47m08` defined as "'NGC1976-DARK-STIS-EDGE".  Unfortunately, the original logic in `haputils.analyze.analyze_data()` registered any exposure with 'DARK' as any part of the TARGNAME keyword value as a calibration exposure that should be ignored and not processed.
The logic was updated to use the IMAGETYP keyword in conjunction with the TARGNAME for WFPC2 observations only to recognize such cases as true external science exposures that can be processed.  It was only implemented for WFPC2 since this problem has never been identified for any ACS or WFC3 exposures that we know of so far in order to minimize the risk for processing the ACS and WFC3 data.  
These changes were tested using data from visit …
> Process all EXT WFPC2 targets

- drizzlepac/adrizzle.py
- drizzlepac/findobj.py
- drizzlepac/haputils/cell_utils.py
- pyproject.toml
The logic for identifying what ProjectionCells (pcells) overlap a set of input exposures ended up only identifying the pcell that had the exposures closest to the center in the X direction (along the ring, or declination band of pcells).  These changes revise that logic to look in the central pcell as well as the ones on either side (-1 and +1).  This logic of looking on either side gets applied to finding the pcell in each overlapping declination band, looking in a total of 6 (or 9?) pcells for any overlap with the input exposures.  Doing so allows SkyCells near the edges of the pcells (with X=1,2, 20 or 21) to be identified as output products as well.
These changes were tested to identify overlap with missing X=2 SkyCells for data from visits `idlx09`, `j8fncm`, and `jd5h17`.
> Find neighbor pcells

- drizzlepac/haputils/analyze.py
- drizzlepac/runastrodriz.py
These changes look for and remove any WFPC2 calibration exposures that can not be aligned or processed during standard pipeline alignment and drizzling.  This required updating the list of recognized calibration target names for WFPC2 and using that to identify those exposures to be skipped and deleted after converting the D0M images into FLT images.
The data from WFPC2 visit 'u2311s' include KSPOT and DARK exposures as well as 2 SCI exposures, and was used to confirm that these changes work as expected.
> Delete WFPC2 CAL FLT files

- drizzlepac/haputils/testutils.py
- drizzlepac/runastrodriz.py
- tests/resources.py
Finally removed the use of the ASTROMETRY_STEP_CONTROL environment variable which had
been deprecated for some years as it had been replaced with ASTROMETRY_APPLY_APRIORI.  Only modest changes were necessary to clean up the deprecated variable.
> Removed the use of the ASTROMETRY_STEP_CONTROL environment variable

- drizzlepac/haputils/astrometric_utils.py
These are simple changes to the docstring for `astrometric_utils.extract_sources` along with an implementation for a default value for the `kernel` parameter.  Previously, `kernel` was actually a required parameter, yet it was specified with a default value of None implying it was optional.  Unfortunately, if `kernel` actually stayed as None, the code would throw an Exception.  So, some logic was added to compute a default kernel based on the `fwhm` parameter using code already called from other functions if `kernel` was None.
> Update docstring for extract_sources and add default kernel

- pyproject.toml
This change simply adds the 'tomli' package as a dependency that needs to be installed when building the docs, since it is called by 'conf.py' when building the RTD pages.
> Add doc build dependency for install

- .readthedocs.yaml
Need a PR just to try to debug the RTD build with this one trying to force it to use an editable install so that the C extension gets installed for use by the RTD build process.
> Try to set readthedocs to use an editable pip install

- .readthedocs.yaml
This backs out the incorrect update to the RTD build configuration.
> Backout incorrect update to RTD build config

- doc/source/conf.py
Another attempt to modify the RTD configuration to once again work.  This time by not adding the repo directory to the sys.path, since pip install will only install to the site-packages dir now.
> Adjust RTD build paths

- pyproject.toml
This adds the `numpydoc` package as a dependency to the installation for use with building the sphinx (RTD) documentation.
> Add numpydoc as RTD build dependency

- pyproject.toml
This adds more missing packages to the RTD configuration so the docs can be built.
> Add more RTD packages for installation

- doc/source/catalog_generation.rst
- doc/source/conf.py
- doc/source/multivisit_api.rst
- doc/source/nicmosobjects.rst
- doc/source/runastrodriz.rst
- doc/source/runmultihap.rst
- doc/source/runsinglehap.rst
- doc/source/singlevisit.rst
- doc/source/tweakback.rst
- drizzlepac/mapreg.help
- drizzlepac/pixtopix.help
- drizzlepac/sky.help
The last(?) of the warnings/errors for the RTD build for version 3.5.1 should have been fixed with these changes.  The changes involved removing duplicate references in the automodule and autofunction listings, as well as cleaning up some last cross-references problems and fixing the name of the `generate_custom_svm_mvm_param_file` as used in the docs.  Some additional entries needed to be made to `conf.rst` for the intersphinx configuration to tell Sphinx where to look for references to modules, functions and classes from external packages like stsci.skypac.
> Remove the last RTD warnings for v3.5.1

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
This PR abstracts CI workflows to the OpenAstronomy workflows; this should reduce maintenance for updating and maintaining actions. Additionally, these changes move the majority of MacOS jobs to the weekly scheduled workflow. This should alleviate the issue where the limited MacOS runners for the organization are not available for CI jobs.
> use OpenAstronomy workflows and move MacOS jobs to a schedule

- drizzlepac/haputils/processing_utils.py
- drizzlepac/haputils/product.py
Implemented an update to ensure the SVM FLT/FLC files all contain the S_REGION keyword AND it has valid values (i.e., closed polygons). Removed a print statement (cruft) in the compute_region() function.
> Ensure the SVM FLT/FLC files all contain a valid S_REGION

- JenkinsfileRT
This simply adds a Python 3.11 environment to the suite of Jenkins tests for nightly builds.
> Add Python 3.11 to Jenkins tests

- CHANGELOG.rst
- drizzlepac/processInput.py
A user reported in help desk ticket INC0189304 that running `AstroDrizzle` with `updatewcs=True` on WFPC2 `*_c0m.fits` data crashes with an error:
```
File "python3.11/site-packages/stsci/tools/check_files.py", line 18, in checkFiles 
if isinstance(filelist[0], str): 
~~~~~~~~^^^ 
IndexError: list index out of range 
```
This PR fixes this error.
> Fix a bug in buildFileListOrig causing crash when updatewcs=True

- drizzlepac/runastrodriz.py
An exception error now reports the name of the file being processed (e.g., ERROR: Cannot run astrodrizzle on runastrodriz -m -i u482c701r_d0m.fits).
> runastrodriz: Report the name of the file being process on exception

- CHANGELOG.rst
- drizzlepac/processInput.py
- drizzlepac/runastrodriz.py
Ensure runastrodriz.py does not execute compute_sregion() if no valid images are found for processing and AstroDrizzle is exiting.  In the case of associations, a drizzled image file is created (e.g., ibvz01010_drz.fits), but the file only contains header information and no actual data component.
> Protect against using compute_sregion for no valid images

- CHANGELOG.rst
- drizzlepac/runastrodriz.py
If analysis of a WFPC2 exposure determines the data cannot be processed for some reason, the converted WFPC2 FLT file is currently deleted.  The process will now exit with the return code of NO_VIABLE_DATA (65), and an empty manifest file will be created. Also, fixed the option string, added a little documentation, and added a BaseException to handle the sys.exit().
> WFPC2: Issue a specific error code and create an empty manifest file for bad data

- tests/acs/test_asn_regress.py
- tests/stis/test_stis.py
- tests/wfc3/test_wfc3.py
- tests/wfpc2/test_wfpc2.py
Five PyTests have had their rtol/atol settings loosened as the Linux and MacOS truth files no longer are in agreement with the previous settings.  While the disagreement is not understood at this time, the tests needed to be modified so that work can continue.  A ticket will be written to keep track of these settings and to try to determine the underlying issue.  The tolerances were modified within the test method to limit the scope of the change.
1. acs/test_asn_regress.py: test_hrc_asn 
2. stis/test_stis.py: test_stis_ccd 
3. wfc3/test_wfc3.py: test_binned_single 
4. wfc3/test_wfc3.py: test_uvis_single 
5. wfpc2/test_wfpc2.py: test_mef_asn
> Five PyTests have had their rtol/atol settings loosened

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
The algorithm which rejects catalogs based upon the check for cosmic
ray contamination (CR) has been modified. An empty catalog (n_sources = 0) should not get rejected by the CR contamination test (since it is empty, it clearly is not contaminated by cosmic rays). Also, if a catalog is empty because it is rejected for some other reason, it should never trigger the rejection of the other type of catalog.
The idea here is not to throw away viable catalog data.
> Modified the criteria for catalog rejection based upon expected CR contamination

- pyproject.toml
A change in the bounding polygon computation in tweakwcs v0.8.2,imalign.align_wcs(), has improved the runtime processing of some SVM datasets from literally days to tens of minutes.  The algorithm formerly used an "exact" method as the default, but now
an approximate method of computing of the bounding polygon is used by default.
Example dataset: acs_8y2_02
> Ensure tweakwcs >= 0.8.2 is in use 

- .github/workflows/publish-to-pypi.yml
update the runners used in the PyPI publish workflow
> use latest versions of linux and macos runners

- CHANGELOG.rst
- pyproject.toml
The matplotlib version 3.7.x caused a problem for the spec-plots preview code as discovered by B. Hayden in the latest build (Drizzlepac 3.6.0 and HSTDP-2023.1.0 ==> not installed in OPS yet).  He found the code seems to work for matplotlib 3.6.3, but not 3.7.1. While the group that handles the preview code has been contacted, it seems I should force a requirement on the matplotlib version temporarily.  The matplotlib version 3.6.3 has been a part of the packaging of Drizzlepac in previous releases so no issues with Drizzlepac are anticipated.
> Ensure version of Matplotlib <= 3.6.3 for now

- drizzlepac/haputils/cell_utils.py
I've added a +1 to the upper range so that the code appropriately indexes skycells. Previously a range(20:21) was being used to loop through cell 21, but this range yielded just [20] so skycells with y=21 were not being looped through. 
The code now identifies program iczge2* as being in skycell-p2111x08y04 and skycell-p2111x09y04, and now, skycell-p2036x01y21 and skycell-p2037x17y21 as well.
> HLA-1029: Fix projection cell identification in overlapping regions

- drizzlepac/haputils/config_utils.py
- drizzlepac/haputils/product.py
This PR corrects the weighting of the reference catalogs; the code now uses 1/sigma**2. The important lines of code are 283 and 284. I also added line 281 to avoid a possible divide by zero error. The remaining changes are the result of code formatting (black).
> HlA-1059: Reference catalog weights corrected

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
The detection_cat parameter of SourceCatalog (Photoutils) is now set to the source catalog object computed for the total detection image. This ensures the source centroid and morphological properties computed based upon the total detection image are used to perform the aperture photometry in the filter images.  Removed check for old versions (<1.1.0) of Photoutils as the pyproject.toml enforces the use of newer versions. Updated the call to the SourceCatalog constructor to remove the deprecated kernel parameter.
This PR addresses Jira HLA-1044.
> Fixed bug in calculation of the measurements for each detected source

- drizzlepac/pars/hap_pars/svm_parameters/wfpc2_wfpc2_index.json
An unwanted trailing comma in the WFPC2 json index file is the likely culprit for a failure of the WFPC2 HAP processing. This fix was confirmed by doing the WFPC2 processing locally (make_wfpc2.py) on the data from visit "ua0t02".
> WFPC2 json file error due to trailing comma

- tests/hap/test_svm_hrcsbc.py
Updated PyTest test_svm_hrcsbc.py after testing on Linux, MacOS, and examining archive files.  After this work was done, it was justified to change the number of sources found in the SBC image(s).
> Drizzlepac: Updated PyTest test_svm_hrcsbc.py from causing failure on PR

- JenkinsfileRT
Changes as suggested by Nadia and Joe to improve the JenkinsfileRT - more output information and address issues for Python 3.10 and 3.11.
These updates were formerly in a different branch with other fixes/changes by Michele.
> Updates to JenkinsfileRT as suggested by Nadia and Joe.

- tests/acs/test_acs_tweak.py
- tests/acs/test_unit.py
Tests marked as **xfail** are actually passing (**xpass**), so removed the **xfail** marker.
> Removed XFAIL marker as tests are xpassing

- requirements-dev.txt
This matches the corresponding solution in `romancal`'s `requirements-dev.txt`
> replace astropy VCS checkout with link to wheel URL

- pyproject.toml
The appropriate fixes have been made in the downstream systems so the plotting now works with more current versions of Matplotlib.
> Removed version restriction on Matplotlib

- CHANGELOG.rst
The master branch of Drizzlepac did not have the most recent CHANGELOG.rst file from the last release of Drizzlepac (3.6.1).  This PR updates the CHANGELOG.rst.
> Get the CHANGELOG.rst from the last release (3.6.1)

- CHANGELOG.rst
- drizzlepac/imageObject.py
- drizzlepac/processInput.py
- drizzlepac/util.py
This PR fixes a bug reported in INC0189304 that, contrary to the documentation, setting `group` argument would result in a crash. In addition, now it is allowed to set `group` to a Python list of integers (_extension numbers_) and list of tuples of _extension name_ and _extension version_ (`(extname, extver)`).
> Allow group specifications as integers or tuples

- CHANGELOG.rst
Literally updated the CHANGELOG.rst to bring it up-to-date with the latest changes destined for Drizzlepac 3.6.2.
> Updated CHANGELOG

- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n1.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n2.json
Resolves [HLA-1093](https://jira.stsci.edu/browse/HLA-1093)
The PR updates the WFPC2 SVM parameters, in particular, the final_bits variable.
> HLA-1093: Updated WFPC2 params for SVM any_n1.json and any_n2.json

- JenkinsfileRT
- requirements-dev.txt
Resolves [HLA-1084](https://jira.stsci.edu/browse/HLA-1084)
Closes #
This PR addresses failures in drizzlpac regression tests and reports on Jenkins.
Changes include
- remove the limit on `ci_watson` and use the latest release
- run tests with dev versions of dependencies in one job only (no reason to run it with all Python versions)
- run code coverage on one job only (no reason to run it in all jobs)
- add the location of numpy nightly wheels
- remove astroquery from the dev dependencies (my understanding is it's used only in testing) 
- fixed the RTD build. RTD deprecated `use-system-packages` in configuration files
Regression …
> HLA-1084:Fix regression tests

- drizzlepac/haputils/cell_utils.py
All np.float_'s are changed to np.float64 as the former is being deprecated in Numpy2.0
> SCSB-93: Changes to fix errors expected from Numpy 2.0

- drizzlepac/haputils/astrometric_utils.py
Resolves [HLA-1122](https://jira.stsci.edu/browse/HLA-1122)
Closes #1668 
This PR adds a logger line to haputils.astrometric utils that specifies the astrometric catalog source.
> HLA-1122: Added log for astrometric catalog source

- drizzlepac/runastrodriz.py
Resolves [HLA-1120](https://jira.stsci.edu/browse/HLA-1120)
Closes # ---
This PR forces a consistent default value for do_verify_guiding() when used on the command line or  via the runastrodriz.process() API.  The do_verify_guiding() function is currently set to False (or turned off) for normal processing.  The alogorithm encapsulated in this function is still being worked and is considered experimental.
> HLA-1120: Force a consistent default value for do_verify_guiding 

- CHANGELOG.rst
- drizzlepac/hapsequencer.py
- drizzlepac/haputils/poller_utils.py
- drizzlepac/haputils/processing_utils.py
- drizzlepac/haputils/product.py
Resolves [HLA-1110](https://jira.stsci.edu/browse/HLA-1110)
Closes #1661 
This PR adds the aperture keyword to HAPProduct object as well as its child products (TotalProduct, FilterProduct, ExposureProduct). The code changes how the poller file data is used. 
Previously the code either  1) used the poller file filenames and pulled the other relevant data from the header keywords 2) used full poller files with all of the relevant data. We have now implemented a third option where if the poller file has two columns, it is assumed that the second column is the aperture keyword. This code will then update the aperture keyword in the output SVM data for only WFPC2. 
[How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression- …
> HLA-1110: aperture keyword from poller to header

- CHANGELOG.rst
- pyproject.toml
Resolves [HLA-1145](https://jira.stsci.edu/browse/HLA-1145)
Closes #
Need to pin astrocut due to conflicts with its latest version and urllib3 version when trying to generate the build YAML.  Build complained:
botocore 1.31.64 requires urllib3<1.27,>=1.25.4; python_version < "3.10", but you have urllib3 2.0.4 which is incompatible.
> HLA-1145: Pin astrocut to avoid urllib3 version conflict

- CHANGELOG.rst
- pyproject.toml
Resolves [HLA-1145](https://jira.stsci.edu/browse/HLA-1145)
Closes #
This PR incorporates the latest drizzlepac commits to master onto the release branch 3.6.2x as release candidate "rc2".
Pin astrocut to avoid urllib3 version conflict  (https://github.com/spacetelescope/drizzlepac/pull/1689)
commit https://github.com/spacetelescope/drizzlepac/commit/f6c7278d73d068cce3b2d1168549a82b9c900959
>  HLA-1145: New drizzlepac release candidate 3.6.2rc2 #1686 

- JenkinsfileRT
Test results and artifacts will continue to be reported and ingested from the `-dev` job, however it will not mark the entire run as failed when an error occurs. Rather, the pipeline will be marked "unstable" (yellow) until the failure conditions can be fixed up by a developer.
> RT: Allow -dev jobs to fail

- JenkinsfileRT
- requirements-dev.txt
This PR changes requirements-dev.txt to not install eggs, which causes problems for the regression tests on Jenkins, and fixes a typo in JenkinsfileRT. Thanks to @jhunkeler for pointing the solution.
Regression tests passing here
https://plwishmaster.stsci.edu:8081/job/RT/job/Drizzlepac-Developers-Pull-Requests/42/
> Update requirements-dev to not use eggs

- pyproject.toml
This PR should address a deprecation warning in the building of drizzlepac for the recent HCALDP Reunion branch build. The error is:
```
writing /srv/jenkins/tmp/pip-modern-metadata-lp4ht0h1/drizzlepac.egg-info/PKG-INFO
/srv/jenkins/tmp/pip-build-env-w6qtofwu/overlay/lib/python3.11/site-packages/setuptools/_core_metadata.py:157: SetuptoolsDeprecationWarning: Invalid config.
!!
********************************************************************************
newlines are not allowed in `summary` and will break in the future
********************************************************************************
!!
```
This fix moves the description in the pyproject.toml from multiple lines to one line. The summary in the PKGINFO appears to be taken from the pyproject.toml description. 
**Checklist …
> HLA-1203: Bug fix for HCALDP Reunion 

- drizzlepac/runastrodriz.py
Resolves [HLA-1144](https://jira.stsci.edu/browse/HLA-1144)
This PR addresses an issue when do_verify_guiding removes all of the usable datasets and results in a nonspecific error. This fix implements a system exit code of 65 (NO VIABLE DATA) in the cases when do_verify_guiding results in no god data and the force=True flag is not enabled. 
[Jenkins test](https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FDrizzlepac-Developers-Pull-Requests/detail/Drizzlepac-Developers-Pull-Requests/53/pipeline/335)
> HLA-1144: Runastrodriz: handle an empty list generated by do_verify_guiding

- CHANGELOG.rst
- drizzlepac/haputils/catalog_utils.py
- tests/hap/test_svm_hrcsbc.py
- tests/hap/test_svm_ibqk07.py
- tests/hap/test_svm_wfc3ir.py
Resolves [HLA-1187](https://jira.stsci.edu/browse/HLA-1187)
Closes #
Modified the value of **check_big_island_only** to be **True** even for Round 2 processing when identifying source regions in the segmentation image as suggested by R.White.  Moved the ratio of Gaussian to RickerWavelet big island values to be done using Round 2 values as the ratio criterion is used for Round 2.  Clarified "if" statements evaluating the RickerWavelet Round 2 results, and added log messages for overall clarity.
Update of regression tests will be done in a different ticket.
> HLA_1187: Modified the value of "check_big_island_only" to be True even for

- drizzlepac/haputils/cell_utils.py
This PR addresses two issues raised by SonarScan:
[<img width="830" alt="image" src="https://github.com/spacetelescope/drizzlepac/assets/16024299/f20f91e9-bb8f-482f-9bb6-ff52d9d78302">
](https://plsonarqube.stsci.edu/project/issues?resolved=false&inNewCodePeriod=true&types=BUG&id=drizzlepac&open=AY3yPaZh6KYUncGR2MCR)
> [SonarQube] raise exception class

- CHANGELOG.rst
- drizzlepac/haputils/catalog_utils.py
To remove bad rows from the "total" or white light source catalog, as well
as to remove the corresponding segments from the segmentation image, ensure the rows are first eliminated from the catalog before the segments are
removed from the segmentation image and reordered.   This dataset
seems to reveal an awareness by the catalog as the row lists, both
good and bad, based upon the original segment ordering cause a fatal
error if the segmentation image is trimmed/re-ordered before the catalog
rows are removed.
Resolves [HLA-1238](https://jira.stsci.edu/browse/HLA-1238)
> SVM: Reconcile removal of bad segments from segmentation image with removal of corresponding rows from the "total" or white light source catalog

- pyproject.toml
Resolves [HLA-1222](https://jira.stsci.edu/browse/HLA-1222)
Closes #
The stsci-imagestats v1.8.0 package contains a bug which causes drizzlepac to fail regression testing during the creation of an HSTDP release candidate.  Since the build/release candidate sequence is already in play, and the stsci-imagestats package is not on the list of a package which can be specified in the build GUI, the only way to force use of the latest version of stsci-imagestats is to have it specified in the pyproject.toml file of drizzlepac.
> Update pyproject.toml to force use of stsci-imagestats>=1.8.1

- CHANGELOG.rst
- pyproject.toml
Resolves [HLA-1222](https://jira.stsci.edu/browse/HLA-1222)
Closes #
Modified the pyproject.toml file in order to force the use of stsci-imagestats >= 1.8.1.  Version 1.8.1 contains a bug fix for lesser versions which caused drizzlepac to fail in Linux machines. 
> Newcandidate 370rc3

- doc/source/mast_data_products/hap_api.rst
- drizzlepac/haputils/analyze.py
Resolves [HLA-727](https://jira.stsci.edu/browse/HLA-727)
Closes #1302 
This PR adds documentaion describing the HAP exit codes. This includes a couple of short sentences host on the main HAP API readthedocs page. 
An additional warning code (not currently in use) was removed to avoid confusion as the code for _okay_ was the same as _error_ in another Class. 
> HLA-727 Description of Exit Codes in documentation

- pyproject.toml
Resolves [HLA-1222](https://jira.stsci.edu/browse/HLA-1222)
Remove the restriction on the stsci.imagestats package version.  This is specifically to help with the generation of a release candidate as a build sequence with is already in-play.  We need to use an older version of stsci.imagestats (1.6.3) at this time, and the previous release candidate was manually installed to force the use of stsci.imagestats 1.6.3.  This means the next release candidate is automatically restricted to use the same version of the package (which is what we want).
> HLA-1222: Remove the restriction on the version of stsci.imagestats

- JenkinsfileRT
This change allows one to set the `ARTIFACTORY_ENV` environment variable to point to an alternate test tree in Artifactory. 
* When unset, input and truth data will originate from `drizzlepac/dev`.
* When set, test data will originate from `drizzlepac/${ARTIFACTORY_ENV}`.
> Enable alternate test data trees

- CHANGELOG.rst
- drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n1.json
Resolves [HLA-1243](https://jira.stsci.edu/browse/HLA-1243)
Closes #1780 
This PR updates the final_bits value in the WFC3/IR SVM config file from 65535 to 528.
Some context from Jenn Mack
> Previously we treated all DQ flags as good pixels (final_bits=65535) with the idea that bad pixels typically do less harm than interpolating over those bad pixels (e.g. near the core of a star where the slope of the PSF is changing rapidly).
> 
> Single IR frames are more likely to be direct image counterparts of grism observations and are thus usually faint targets whose photometry would be more impacted by bad pixels. 
> 
> Therefore we want to treat DQ flags as bad pixels and reject them from the drizzled output.  The exception is DQ 512 (IR blobs) + DQ 16 (stable hot pixels), which are recommended …
> HLA-1243: final_bits value change in config json for single WFC3/IR SVM

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
use reusable workflow and make toxenv names explicit w/ Python version 
> include Python versions in toxenvs, install HDF5 for macOS tests

- CHANGELOG.rst
- drizzlepac/haputils/product.py
Resolves [HLA-1138(https://jira.stsci.edu/browse/HLA-1138)
Closes #
Exclude single filter images in the generation of the total detection
image to minimize cosmic ray contamination, unless there are only single filter images in the visit.
> HLA-1138: Exclude single filter images in the generation of the total detection image

- CHANGELOG.rst
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/ci_table.py
- drizzlepac/haputils/hapcut_utils.py
- drizzlepac/haputils/product.py
- drizzlepac/nicmosData.py
- drizzlepac/processInput.py
Resolves [HLA-1254](https://jira.stsci.edu/browse/HLA-1254)
Closes #
Address issues caught by SonarQube statis code analysis. This must be done according to ITSD requirements.
Deleted the deprecated parameter, dao_threshold, in
astrometric_utils.py/extract_sources(). Removed parameter from any calling functions.
> HLA-1254: Address issues caught by SonarQube

- CHANGELOG.rst
- doc/source/mast_data_products/catalog_generation.rst
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1257](https://jira.stsci.edu/browse/HLA-1257)
Closes #
Remove the use of a "custom" kernel for the segmentation algorithm as it has been shown to cause smearing issues. The default kernel is now a Gaussian which is produced by calling an exisiting astrometric_utils.py function, build_gaussian_kernel.  All internal comments in the catalog_utils.py regarding the "custom" kernel have been updated. This is only Step 1 of this update.
> HLA-1257: Remove the use of a custom smoothing kernel for catalog generation

- JenkinsfileRT
The sparse implementation of the `BuildConfig` class in `testenv`'s groovy "accessor" does not include the `runtime` list member.
```
Applying environment variables...
Traceback (most recent call last):
File "***/local/miniforge3/envs/TEMPORARY/bin/testenv", line 33, in <module>
sys.exit(load_entry_point('testenv', 'console_scripts', 'testenv')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "***/testenv/testenv/cli/main.py", line 135, in main
context = TestContext(pkg)
^^^^^^^^^^^^^^^^
File "***/testenv/testenv/testcontext.py", line 108, in __init__
self.apply_env_vars()
File "***/testenv/testenv/testcontext.py", line 191, in apply_env_vars
key, value = var.split('=')
```
The real error was:
```
$ groovy testenv/scripts/jfile_accessor.groovy REPO/JenkinsfileRT …
```
> Move environment variable declaration into env_vars list

- CHANGELOG.rst
- JenkinsfileRT
Resolves [HLA-1266](https://jira.stsci.edu/browse/HLA-1266)
Closes #
Update done by Joe to fix the JenkinsfileRT.  Move the runtime setting of CFLAGS into the environment variables setting for b3 (env_vars).  Also, fixed the mislabeled "b1" to be "b2".
> HLA-1266: Newcandidate Drizzlepac RC - 371rc2

- JenkinsfileRT
* Fixes missing python 3.11 test commands
> Fixes codecov

- JenkinsfileRT
adding pytest-cov to the pip install of the jenkins python 3.11 tests.
> Adding pytest-cov to pip install

- .readthedocs.yaml
The mambforge build version for readthedocs has been updated form 4.10 to 23.11.
> Testing readthedocs mambaforge versions to fix build failures. 

- CHANGELOG.rst
- drizzlepac/processInput.py
This PR addresses the case where the input filenames to `manageInputCopies` are full paths rather than base names. Previously, specifying a full path (for example if the input files were in a temp directory, like in the unit test I was trying to write for another package) would result in a `shutil.sameFileError` because the `copyname` would end up unchanged from the input. With this patch that case works.
[jenkins test](https://plwishmaster.stsci.edu:8081/job/RT/job/Drizzlepac-Developers-Pull-Requests/90/)
> Update manageInputCopies to work if input files aren't in working directory

- JenkinsfileRT
This PR addresses install issues in the `3.11-dev` Jenkins job where `stsci.tools` is not installed:
[<img width="701" alt="image" src="https://github.com/user-attachments/assets/3d768d56-f9d1-459e-a64d-6debf31c29ac">](https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FDrizzlepac-Developers-Pull-Requests/detail/Drizzlepac-Developers-Pull-Requests/96/pipeline/251#step-254-log-20)
It appears that multiple dependencies are missing,
[<img width="337" alt="image" src="https://github.com/user-attachments/assets/8cb66227-0eb4-4a3e-8de6-cc963814a45f">](https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FDrizzlepac-Developers-Pull-Requests/detail/Drizzlepac-Developers-Pull-Requests/96/pipeline/142#step-247-log-1)
due to environment resolution conflicts when …
> [Jenkins] fix install conflicts in `3.11-dev` job

- CHANGELOG.rst
- drizzlepac/haputils/deconvolve_utils.py
Resolves [HLA-1291](https://jira.stsci.edu/browse/HLA-1291)
Closes #
Modified the call to the hamming function in the **deconvolve_utils.py** module as SciPy deprecated the way window filtering functions can be invoked. These
functions can no longer be imported from the scipy.signal namespace but need to be accessed via scipy.signal.windows. 
Performed my own regression testing using results from caldp_20240509 (many differences due to many changes in drizzlepac), paying particular attention to the *trl.txt files to ensure the processing after the fix matches this previous build.
> HLA-1291: Updated the call to hamming function in deconvolve_utils.py

- CHANGELOG.rst
- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1295](https://jira.stsci.edu/browse/HLA-1295)
Closes #
Corrected the way the n1_exposure_time and tot_exposure_time values
are computed as these values are used in the computation for rejecting catalog creation based on expected cosmic ray detections.  Generalized the crfactor dictionary for all detectors. Ensure if any catalog type is rejected, all the catalog types are rejected.
> HLA-1295: Fixed the computations associated with rejection of catalogs due to cosmic rays

- CHANGELOG.rst
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1302](https://jira.stsci.edu/browse/HLA-1302)
Closes #
Added an if statement so the evaluation of possible rejection of catalogs due to not enough sources vs estimated cosmic rays is not done for ACS/SBC and WFC3/IR.  This oversight was found during regression testing.
> HLA-1302: Avoid application of cosmic ray threshold for ACS/SBC and WFC3/IR catalogs

- CHANGELOG.rst
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1302](https://jira.stsci.edu/browse/HLA-1302)
Catalogs based upon images which suffer from cosmic rays are evaluated based upon an estimate of the number of cosmic rays expected for a given exposure time.  If the total number of sources does not exceed the estimated number of cosmic rays (plus a fudge factor), the catalogs can be rejected. This evaluation does not apply to ACS/SBC and WFC3/IR detectors.
> HLA-1302: Avoid application of cosmic ray threshold for ACS/SBC and WFC3/IR

- .github/workflows/build.yml
Resolves [HLA-1307](https://jira.stsci.edu/browse/HLA-1307)
Since there are very few wheel packages on pypi right now for
Python 3.13, we must do a workaround and exclude 3.13 from the target list.  This is advice from Joe H. with an example from JWST.  This is necessary to do to push out the final Drizzlepac v3.7.1.
> Eliminate Python 3.13 from the target list

- CHANGELOG.rst
- JenkinsfileRT
- drizzlepac/haputils/processing_utils.py
- drizzlepac/haputils/product.py
Resolves [HLA-935](https://jira.stsci.edu/browse/HLA-935)
This PR adds two new HDRTABLE entries to MVM drizzled (drc/z) products. These include the name (SVMROOTNAME) and creation date (GENDATE) of each of the SVM images included within the MVM. 
[Jenkins test](https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FDrizzlepac-Developers-Pull-Requests/detail/Drizzlepac-Developers-Pull-Requests/119/pipeline)
> HLA-935: Update HDRTAB for MVM products

- drizzlepac/hapsequencer.py
- tests/hap/test_svm_j97e06.py
Resolves [HLA-1315](https://jira.stsci.edu/browse/HLA-1315)
Closes #
Fixed the code handling log/trailer file creation for Grism/Prism data in the "finally" block of run_hap_processing, as an error under PyTest 
was being generated as the designated log file could not be found to be copied and used as the Grism/Prism log file. The Grism/Prism log files are just placeholders, so an empty file is created if the designated log file cannot be found.  Added comments.  The code executes properly when not run under PyTest.
I manually ran test_svm_j97e06.py (test which revealed the problem) and test_svm_je281u.py in my workspace to test with Pytest.  I also ran both visits without PyTest.
[How to run regression tests on a …
> HLA-1315: Fix "finally" block handling Grism/Prism under PyTest

- drizzlepac/buildmask.py
This change is necessary as an int is being truncated in numpy 2.0. This change converts the int to a uint, which has more positive available characters and is fine as the values should never be negative.
> Small update to buildmask for Numpy 2.0

- drizzlepac/haputils/cell_utils.py
- pyproject.toml
Resolves [HLA-1323](https://jira.stsci.edu/browse/HLA-1323)
This PR fixes the s_region issues that we have been observing in the SVMs. It uses the simplify-polyline package instead of skimage.corner_harris. Results from initial testing are shown in the Jira ticket. 
These code changes were generously contributed by @rlwastro.
[Jenkins test](https://plwishmaster.stsci.edu:8081/job/RT/job/Drizzlepac-Developers-Pull-Requests/134/)
> HLA-1323: s_region fix using simplify-polyline

- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1284](https://jira.stsci.edu/browse/HLA-1284)
Closes #
Use the filter mask (illuminated vs non-illuminated pixels) when processing the  Filter product.  For all products, properly account for the number of pixels which are illuminated,  the number of pixels that contain true zero in the illuminated portion of the image, and non-illuminated pixels.
https://plwishmaster.stsci.edu:8081/job/RT/job/Drizzlepac-Developers-Pull-Requests/146/
First run done with unchanged reference/truth files in /dev and results are in /drizzlepac-results/wfc3/11Oct2024T.  Created drizzlepac/3.7.2 which is a copy of drizzlepac/dev, but the …
> HLA-1284/1287: Properly account for illuminated and non-illuminated pixels

- pyproject.toml
Resolves [HLA-1348](https://jira.stsci.edu/browse/HLA-1348)
Closes #1895 
This PR removes unused dependencies from the main dependencies list in the pyproject.toml file. Several dependencies are moved to the optional dependencies list. 
[jenkins test](https://plwishmaster.stsci.edu:8081/job/RT/job/Drizzlepac-Developers-Pull-Requests/149/)
> HLA-1348: Isolate dependencies to optional dependencies list if possible

- drizzlepac/hapsequencer.py
Resolves [HLA-1369](https://jira.stsci.edu/browse/HLA-1369)
Closes #
This PR addresses an issue where an incorrect error code is being returned in SVM processing. For the case of 
`There are no viable direct images in any Total Data Product for this visit`
The error code that was previous returned (0) has been changed to 65.
> HLA-1369: No viable data code 0 changed to code 65

- drizzlepac/staticMask.py
In investigating a build error ([HLA-1368](https://jira.stsci.edu/browse/HLA-1368)) we found an error where a nan in the science image array caused an error in a call to stsci.imagestats. The call to stsci.imagestats calculates a min and max (used for cuts), that results in nans for both. 
Here I am passing min and max values using np.nanmin and np.nanmax, which ignore nans in the calculation.
> Ignore nans in staticmask call to stsci.imagestats

- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1370](https://jira.stsci.edu/browse/HLA-1370)
Closes #
Fixed a bug associated with a previous commit when computing statistics on the illuminated portion only of the drizzled image.  The computation now uses the footprint_mask which is based on the DRZ CTX image which reports the number of images which contributed to the final pixel value.  If the CTX[i,j] > 0, then the pixel is illuminated.
> HLA-1370: Fixed a bug from a previous commit for computing statistics

- CHANGELOG.rst
- doc/ADRs.md
- pyproject.toml
- requirements-dev.txt
- tests/hap/test_svm_j97e06.py
Resolves [HLA-1401](https://jira.stsci.edu/browse/HLA-1401)
Closes #1921 
This PR cleans up the main branch. We have been making build-related changes on branch 3.9.0, however, there are some changes that are only on main that we don't want to clobber with a merge. I have therefore added difference manually in one go in order to avoid conflicts. 
These changes include changes to the pyproject.toml and requirements-dev.txt file that specify the requirement for numpy > 2.0. I have also updated the changelog, skipped two SVM tests (similar to build), and added an ADR about our dependency pinning strategy. 
[Jenkins …
> HLA-1401: Updating main branch based on changes on 3.9.0 (build-related changes)

- tests/resources.py
Some of the diff reports from pytests are unhelpfully long. This change truncates any ascii difference reports to the first 100 lines. This should be sufficient for understanding the initial differences.
> Truncate pytest failure report for ascii diffs

- CHANGELOG.rst
- tests/resources.py
Resolves [HLA-1406](https://jira.stsci.edu/browse/HLA-nnnn)
Closes #
This PR fixes the incorrect path to artifactory where new truth files are saved to. I was able to confirm this by running `tests/wfpc2/test_wfpc2.py` on our new github actions tests with the artifactory dev (truth) environment set to `3.7.0`. The command uses the gui and looks like this:
The results of the tests are [here](https://github.com/spacetelescope/RegressionTests/actions/runs/12817454877/job/35740771937) and an example of the location of the new files is [here](https://bytesalad.stsci.edu/ui/repos/tree/General/drizzlepac-results/2025-01-16_GITHUB_CI_Linux-X64-py3.11-790/wfpc2/test_wfpc2_single0/reference_single_mef.fits). 
The new truth files are now posted to the directories already being produced with summary …
> HLA-1406: Truth files saved to correct location on artifactory

- pyproject.toml
Closes issue [#212](https://github.com/spacetelescope/stwcs/issues/212) in STWCS.
> Pins drizzlepac to the most recent STWCS version that also requires numpy>2.0

- CHANGELOG.rst
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-407](https://jira.stsci.edu/browse/HLA-1407)
Closes #
Implemented fixes recommended by R.White to address uneven detection thresholds in the HAP catalogs due to bugs in the function, make_wht_masks, which intends to create weight masks covering the full drizzled output footprint. A somewhat related bug in the compute_threshold method associated with only the Segment catalog was also addressed. The "scale factor" which causes the RMS computation to be too small was deleted.  The RMS computation for the Point and Segment catalogs is now the same.
> HLA-1407: Implemented fixes to address uneven detection thresholds in HAP catalogs

- CHANGELOG.rst
- drizzlepac/haputils/astrometric_utils.py
Resolves [HLA-1413](https://jira.stsci.edu/browse/HLA-1413)
Closes #
The PR replaces the deprected class IntegratedGaussianPRF with CircularGaussianSigmaPRF.
> HLA-1413: Replaced deprecated class

- CHANGELOG.rst
- doc/source/mast_data_products/catalog_generation.rst
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
Resolves [HLA-1427](https://jira.stsci.edu/browse/HLA-1427)
Closes #
Added a third test using the size in pixels of the largest determined segment as a discriminant with regard to switching from a Gaussian to a Ricker-Wavelet kernel.  The kernel is used to convolve with the input image to increase the signal-to-noise ratio for the detection of faint sources.
> HLA-1427: Improve algorithm for switching to crowded field kernel for HAP segment catalogs

- CHANGELOG.rst
- drizzlepac/haputils/align_utils.py
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1433](https://jira.stsci.edu/browse/HLA-1433)
Closes #
Removed a parameter deprecated in Photutils 2.0, edge_method, from the instantiation of a Background2D.  The default for this parameter is now always equal to "pad" which was the setting in use in our code.
> HLA-1433: Remove parameter deprecated in Photutils 2.0

- CHANGELOG.rst
- pyproject.toml
Updated the Pyproject.toml file to force use of Photutils v2.0.0 or greater. This update is in support of the change addressed by #1950.
> Update the Pyproject.toml file to force use of Photutils >= 2.0.0

- drizzlepac/haputils/astrometric_utils.py
Resolves [HLA-1433](https://jira.stsci.edu/browse/HLA-1433)
Closes #
It turns out no actual code changes needed to be made at this time.  However, comments were added to describe the instantiation attributes for the IterativePSFPhotometry class to clarify understanding.
> HLA_1433: Add clarification comments to IterativePSFPhotometry instantiation

- CHANGELOG.rst
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
- tests/hap/test_svm_u2as01.py
- tests/hap/wfpc2_2as_01_input.out
Resolves [HLA-1448](https://jira.stsci.edu/browse/HLA-1448)
Closes #
Fixed the crfactor designation for the WFPC2 detector (PC) which caused the the computation for rejecting catalog creation based on expected cosmic ray detections to fail ONLY for WFPC2.  Also, updated the WFPC2 cr_residual factor from 0.0 to 0.05 as it had never be set correctly.  Created a PyTest for WFPC2 SVM processing.
> HLA-1448: Fix the crfactor designation for the WFPC2 detector to avoid failure

- drizzlepac/pars/hap_pars/mvm_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/acs/wfc/acs_wfc_quality_control_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
Updated the MVM ACS/WFC quality control JSON file to change the value
of "bthresh" to 5.0 to match the "bthresh" values in the other detector
quality control files, as well as its corresponding SVM file. Modified
all the MVM catalog JSON files to remove the "bthresh" variable.
> Updated the MVM ACS/WFC quality control JSON file

- .github/workflows/ci.yml
- CHANGELOG.rst
- pyproject.toml
We are removing support for python 3.10. 
We have specified that drizzlepac now requires python >=3.11 in the pyproject.toml and this removes the last (CI) test that we do under python 3.10.
> Dropping support for python 3.10

- drizzlepac/__init__.py
This issue is resolved by using _contextlib_ instead of a standalone function for silencing the teal import line from stsci.skypac.
> Fix for I/O astrometry database bug

- drizzlepac/runastrodriz.py
I recently added a simple logger and logged warning to runastrodriz without understanding the complicated nature of logging in drizzlepac. I am working on a full logging solution on [a different branch](https://github.com/spacetelescope/drizzlepac/tree/logging_spring_25), but in the meantime, this small change resulted in some duplicated lines from stwcs:
> Updating astrometry for ib4606c5q
> Updating astrometry for ib4606c5q
> Accessing AstrometryDB service :
> Accessing AstrometryDB service :
>         https://mast.stsci.edu/portal/astrometryDB/observation/read/ib4606c5q
>         https://mast.stsci.edu/portal/astrometryDB/observation/read/ib4606c5q
> AstrometryDB service call succeeded
> AstrometryDB service call succeeded
> Retrieving astrometrically-updated WCS "OPUS" for observation …
> Remove duplicated log lines from dependencies in runastrodriz

- CHANGELOG.rst
- drizzlepac/haputils/analyze.py
This PR comments out the behavior the recently added behavior for the EXPFLAG in #1968.
I have commented out code that was taking files with EXPFLAG not set as "NORMAL" and adding a no_procesing flag to them during alignment. This was resulting in these files not being aligned. As the fraction of these files is actually quite high, we have elected to remove this change for the time being until a more tempered solution is found.
> Reverting EXPFLAG change from PR #1968

- CHANGELOG.rst
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1484](https://jira.stsci.edu/browse/HLA-1484)
Closes #
Resolved the issue of duplicate "ID"s in the rows of the Total Point catalog. For "point"
source identification, looping is done over a list of weight masks, tp_masks, when invoking the "finder" algorithms. These algorithms return tables with a unique "id" number for each row/source in the table. When tp_masks > 1, the returned tables are "vstacked" to generate a final table. Unfortunately, the "id" number was not updated to reflect the stacking of the tables which created rows with the same "id".  This error did not cause the code to fail, but it did generate a garbled table.
It is believed this bug was introduced in HLA-1407/PR#1939 which is an update for this latest build (v3.10x) when the computation of the tp_masks …
> HLA-1484: Resolve issue of duplicate IDs in the Total Point Catalog product

- CHANGELOG.rst
- pyproject.toml
Resolves [HLA-1482](https://jira.stsci.edu/browse/HLA-1482)
Closes #
Force use of Astropy 6.1.7 in the Drizzlepac pyproject.toml at this time. Significant upgrades in the underlying functionality, particularly in astropy.modelling.fitting have not been accommodated in the drizzlepac code, resulting in a degradation of measurement results for the output Point product catalogs.
> HLA-1482: Force use of Astropy 6.1.7 for Drizzlepac

- CHANGELOG.rst
- drizzlepac/haputils/astrometric_utils.py
- pyproject.toml
Resolves [HLA-1482](https://jira.stsci.edu/browse/HLA-1482)
Resolves [HLA-1487](https://jira.stsci.edu/browse/HLA-1487)
Closes #
Added the parameter setting, _sub_shape_, to the IterativePSFPhotometry call to ensure a rectangular shape around the center of a star is defined when subtracting the fitted PSF models. The _sub_shape_ must be specified if the model does not have a "bounding_box" attribute.  This parameter no longer is set in the IterativePSFPhotometry class based upon the _fit_shape_.
> HLA-1482/HLA-1487: Added parameter setting to the IterativePSFPhotometry call

- CHANGELOG.rst
- drizzlepac/haputils/poller_utils.py
Resolves [HLA-1497](https://jira.stsci.edu/browse/HLA-1497)
Closes #
Corrected the use of a string comparison to "asn" in the build_poller_table routine of the poller_utils.py module as these characters are a valid portion of the root of an ipppssoot filename (e.g., u6kasn01m).  The comparison is now done against "_asn" when looking for association names in order to perform the proper actions.
> HLA-1497: Corrected the string comparison to "asn" in the poller_utils.py module

- CHANGELOG.rst
- drizzlepac/devutils/make_cfgobj_files.py
- drizzlepac/devutils/run_config_utils.py
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/svm_quality_analysis.py
- drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
- drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
Resolves [HLA-1501](https://jira.stsci.edu/browse/HLA-1501)
Closes #
Added an internal comment and moved two deprecated modules, make_cfgobj_files.py and run_config_utils.py, to the devutils subdirectory.
Updated the catalog configuration files:
1) Removed the deprecated variable, fwhm, from the sourcex object,
2) Removed the deprecated variable, TWEAK_THRESHOLD, from the dao object, 
3) Moved the variable (key/value pair), "TWEAK_FWHMPSF": <float>, to the
general object portion of the file as it applies to both catalogs.
Modified the catalog_utils.py module to read the TWEAK_FWHMPSF variable from the proper location in the catalog JSON file.  The Segmentation catalog now reports the proper value for the Gaussian Filter FWHM which is used to smooth the total detection image to enhance …
> HLA-1501: Clean-up values (move to proper section or delete) from catalog configuration files

- CHANGELOG.rst
- drizzlepac/hapsequencer.py
- drizzlepac/haputils/catalog_utils.py
Resolves [HLA-1503](https://jira.stsci.edu/browse/HLA-1503)
Closes #
Clarified the sigma value used to compute the threshold above which sources are detected for the segmentation catalog.  The sigma value is different when using the Gaussian or RickerWavelet smoothing kernel for Round 1 processing, as well as both being doubled for Round 2 processing if and only if switching from a sigma-clipped background to a Background2D. The value has been corrected in the output Segmentation
catalogs, and given greater visibility in the trailer log files.
> HLA-1503: Report correct sigma value for computing threshold for source detection

- CHANGELOG.rst
- drizzlepac/pars/hap_pars/mvm_parameters/acs/hrc/acs_hrc_alignment_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/acs/sbc/acs_sbc_alignment_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/acs/wfc/acs_wfc_alignment_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/wfc3/ir/wfc3_ir_alignment_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
- drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
Resolves [HLA-1479](https://jira.stsci.edu/browse/HLA-1479)
Closes #
Overwrote only the MVM "alignment" configuration files with the files stored in the SVM subdirectories.  It is understood these files are probably obsolete.  The files were out-of-sync, and they previously had been synchronized.
> HLA-1479: Overwrote the MVM "alignment" configuration files with the SMV files

- CHANGELOG.rst
- drizzlepac/haputils/catalog_utils.py
- drizzlepac/haputils/hla_flag_filter.py
Resolves [HLA-1512](https://jira.stsci.edu/browse/HLA-1512)
Closes #
Fixed scipy deprecations in catalog_utils.py and hap_flag_filter.py.   For example:
```
DeprecationWarning: Please import `binary_dilation` from the `scipy.ndimage` namespace; the `scipy.ndimage.morphology` namespace is deprecated and will be removed in SciPy 2.0.0.
dilate = scipy.ndimage.morphology.binary_dilation
```
> HLA-1512: Fix scipy deprecations

- CHANGELOG.rst
- drizzlepac/runastrodriz.py
Resolves [HLA-1464](https://jira.stsci.edu/browse/HLA-1464)
Closes #
This PR addresses a crash in OPS for HRC data "j9pb20010" during aposteriori processing. The issue was tracked down to update of the WCS with a headerlet which is missing IDCSCALE.
Regression tests passing: https://github.com/spacetelescope/RegressionTests/actions/runs/16349387771/job/46200642685
> HLA-1464: Missing IDCSCALE crashes processing

- CHANGELOG.rst
- drizzlepac/haputils/astrometric_utils.py
- drizzlepac/haputils/deconvolve_utils.py
- drizzlepac/imgclasses.py
- drizzlepac/runastrodriz.py
Resolves [HLA-1531](https://jira.stsci.edu/browse/HLA-1531)
Closes #2049
This PR addresses two DeprecationsWarnings in the regression tests. 
- Replaced log.warn with log.warning
- Replaced LMLSQFitter with TRFLSQFitter
Regression tests pass:
https://github.com/spacetelescope/RegressionTests/actions/runs/16352978260/job/4620432714
> Fix deprecations
